"""A local HTTP stub for the generated tests: standard library only.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, Dict, List, NamedTuple, Optional, Tuple
from urllib.parse import parse_qs, unquote, urlsplit

STUB_URL = "__STUB_URL__"


class Reply(NamedTuple):
    status: int
    body: str
    headers: Optional[Dict[str, str]] = None


class Request(NamedTuple):
    method: str
    path: str
    query: Dict[str, str]
    headers: Dict[str, str]
    body: bytes


class Stub:
    """Answers each request with the next reply (the last one repeats) and
    records what it received. Use as a context manager."""

    def __init__(self, replies: List[Reply]) -> None:
        self.replies = replies
        self.requests: List[Request] = []
        stub = self

        class Handler(BaseHTTPRequestHandler):
            def handle_one(self) -> None:
                length = int(self.headers.get("Content-Length") or 0)
                body = self.rfile.read(length) if length else b""
                parts = urlsplit(self.path)
                query = {key: values[0] for key, values in parse_qs(parts.query).items()}
                headers = {key.lower(): value for key, value in self.headers.items()}
                stub.requests.append(Request(self.command, unquote(parts.path), query, headers, body))
                reply = stub.replies[min(len(stub.requests), len(stub.replies)) - 1]
                payload = reply.body.replace(STUB_URL, stub.url).encode("utf-8")
                self.send_response(reply.status)
                self.send_header("Content-Type", "application/json")
                for name, value in (reply.headers or {}).items():
                    self.send_header(name, value.replace(STUB_URL, stub.url))
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                if self.command != "HEAD":
                    self.wfile.write(payload)

            do_GET = do_POST = do_PUT = do_PATCH = do_DELETE = do_HEAD = do_OPTIONS = handle_one

            def log_message(self, format: str, *args: Any) -> None:
                pass

        self._server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self.url = "http://127.0.0.1:%d" % self._server.server_address[1]
        self._thread = threading.Thread(target=self._server.serve_forever, kwargs={"poll_interval": 0.01}, daemon=True)

    def __enter__(self) -> "Stub":
        self._thread.start()
        return self

    def __exit__(self, *exc: Tuple[Any, ...]) -> None:
        self._server.shutdown()
        self._server.server_close()
        self._thread.join()
