"""typeship — account.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class AccountResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def retrieve(self, *, request_options: Optional[RequestOptions] = None) -> AccountRead:
        """The account behind the presented credentials

        Returns the account associated with your credential. The Typeship CLI uses this endpoint
        for `whoami`.

        GET /me
        """
        return self._core.request(
            "GET",
            "/me",
            errors={"401": "UnauthorizedError", "403": "ForbiddenError", "429": "RateLimitedError"},
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="account.retrieve",
        )


class AsyncAccountResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def retrieve(self, *, request_options: Optional[RequestOptions] = None) -> AccountRead:
        """The account behind the presented credentials

        Returns the account associated with your credential. The Typeship CLI uses this endpoint
        for `whoami`.

        GET /me
        """
        return await self._core.arequest(
            "GET",
            "/me",
            errors={"401": "UnauthorizedError", "403": "ForbiddenError", "429": "RateLimitedError"},
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="account.retrieve",
        )
