"""typeship — apiKeys.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class ApiKeysResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[ApiKeyRead]:
        """List API keys

        Lists key metadata and the last four characters of each key. Full keys are not returned.
        Create keys in the Console.

        GET /api-keys

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            "/api-keys",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ApiKeyListRead:
        """One page of "/api-keys", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/api-keys",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.list",
        )

    def get(
        self,
        api_key_id: str,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> ApiKeyResponseRead:
        """Get an API key

        Returns the key summary and its ETag for conditional revocation.

        GET /api-keys/{api_key_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/api-keys/{_quote(str(api_key_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.get",
        )

    def revoke(
        self,
        api_key_id: str,
        *,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ApiKeyResponseRead:
        """Revoke an API key

        Revokes a key. Repeating the request returns the same result.

        With OAuth, members can revoke their own keys; organization admins can revoke any key.
        Organization API keys can revoke any key in their organization.
        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        DELETE /api-keys/{api_key_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "412": "PreconditionFailedError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "DELETE",
            f"/api-keys/{_quote(str(api_key_id), safe='')}",
            headers=_headers,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.revoke",
        )


class AsyncApiKeysResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[ApiKeyRead]:
        """List API keys

        Lists key metadata and the last four characters of each key. Full keys are not returned.
        Create keys in the Console.

        GET /api-keys

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            "/api-keys",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ApiKeyListRead:
        """One page of "/api-keys", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/api-keys",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.list",
        )

    async def get(
        self,
        api_key_id: str,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> ApiKeyResponseRead:
        """Get an API key

        Returns the key summary and its ETag for conditional revocation.

        GET /api-keys/{api_key_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/api-keys/{_quote(str(api_key_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.get",
        )

    async def revoke(
        self,
        api_key_id: str,
        *,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ApiKeyResponseRead:
        """Revoke an API key

        Revokes a key. Repeating the request returns the same result.

        With OAuth, members can revoke their own keys; organization admins can revoke any key.
        Organization API keys can revoke any key in their organization.
        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        DELETE /api-keys/{api_key_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "412": "PreconditionFailedError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "DELETE",
            f"/api-keys/{_quote(str(api_key_id), safe='')}",
            headers=_headers,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="apiKeys.revoke",
        )
