"""typeship — definitionRevisions.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class DefinitionRevisionsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        definition_id: DefinitionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[DefinitionRevisionRead]:
        """List Definition Revisions

        Immutable snapshots of the complete resolved document graph this Definition observed,
        newest first. Content is available from the revision and document endpoints and is never
        embedded in a list response.

        GET /definitions/{definition_id}/revisions

        Args:
            limit: Maximum number of resources to return.
            cursor: Opaque cursor from the preceding page's next_cursor.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.paginate(
            "GET",
            f"/definitions/{_quote(str(definition_id), safe='')}/revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        definition_id: DefinitionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DefinitionRevisionListRead:
        """One page of "/definitions/{definition_id}/revisions", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/definitions/{_quote(str(definition_id), safe='')}/revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.list",
        )

    def retrieve(
        self,
        definition_revision_id: DefinitionRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DefinitionRevisionRead:
        """Retrieve a Definition Revision

        Metadata for one immutable resolved document graph. Fetch its canonical content or
        individual source documents from the content endpoints.

        GET /definition_revisions/{definition_revision_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/definition_revisions/{_quote(str(definition_revision_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.retrieve",
        )

    def retrieve_content(
        self,
        definition_revision_id: DefinitionRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> str:
        """Retrieve a Definition Revision's canonical content

        Returns the exact canonical resolved content identified by the revision's graph digest,
        suitable for saving or piping into a diff.

        GET /definition_revisions/{definition_revision_id}/content
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/definition_revisions/{_quote(str(definition_revision_id), safe='')}/content",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.retrieveContent",
        )

    def retrieve_document_content(
        self,
        definition_revision_id: DefinitionRevisionId,
        document_id: DefinitionDocumentId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> str:
        """Retrieve one source document from a Definition Revision

        GET /definition_revisions/{definition_revision_id}/documents/{document_id}/content
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/definition_revisions/{_quote(str(definition_revision_id), safe='')}/documents/{_quote(str(document_id), safe='')}/content",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.retrieveDocumentContent",
        )


class AsyncDefinitionRevisionsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        definition_id: DefinitionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[DefinitionRevisionRead]:
        """List Definition Revisions

        Immutable snapshots of the complete resolved document graph this Definition observed,
        newest first. Content is available from the revision and document endpoints and is never
        embedded in a list response.

        GET /definitions/{definition_id}/revisions

        Args:
            limit: Maximum number of resources to return.
            cursor: Opaque cursor from the preceding page's next_cursor.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.apaginate(
            "GET",
            f"/definitions/{_quote(str(definition_id), safe='')}/revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        definition_id: DefinitionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DefinitionRevisionListRead:
        """One page of "/definitions/{definition_id}/revisions", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/definitions/{_quote(str(definition_id), safe='')}/revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.list",
        )

    async def retrieve(
        self,
        definition_revision_id: DefinitionRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DefinitionRevisionRead:
        """Retrieve a Definition Revision

        Metadata for one immutable resolved document graph. Fetch its canonical content or
        individual source documents from the content endpoints.

        GET /definition_revisions/{definition_revision_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/definition_revisions/{_quote(str(definition_revision_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.retrieve",
        )

    async def retrieve_content(
        self,
        definition_revision_id: DefinitionRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> str:
        """Retrieve a Definition Revision's canonical content

        Returns the exact canonical resolved content identified by the revision's graph digest,
        suitable for saving or piping into a diff.

        GET /definition_revisions/{definition_revision_id}/content
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/definition_revisions/{_quote(str(definition_revision_id), safe='')}/content",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.retrieveContent",
        )

    async def retrieve_document_content(
        self,
        definition_revision_id: DefinitionRevisionId,
        document_id: DefinitionDocumentId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> str:
        """Retrieve one source document from a Definition Revision

        GET /definition_revisions/{definition_revision_id}/documents/{document_id}/content
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/definition_revisions/{_quote(str(definition_revision_id), safe='')}/documents/{_quote(str(document_id), safe='')}/content",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="definitionRevisions.retrieveDocumentContent",
        )
