"""typeship — drafts.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class DraftsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[DraftStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[DraftRead]:
        """List Drafts

        Lists open and merged Drafts, newest first. Each Target has one open Draft; each merge
        adds a merged Draft.

        GET /drafts

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            target_id: Only Drafts of this Target.
            status: Only Drafts with this status.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            "/drafts",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[DraftStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftListRead:
        """One page of "/drafts", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/drafts",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.list",
        )

    def get(
        self,
        draft_id: DraftId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Get a Draft

        Returns the Draft's status. An open Draft also reports its typed reason when action is
        required, next version and its source, compatibility and version assessment, blocking
        errors, checks, and conflict counts. The response carries an `ETag`; send it in
        `If-Match` when updating the Draft to avoid changing a newer version selection.

        GET /drafts/{draft_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/drafts/{_quote(str(draft_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.get",
        )

    def update(
        self,
        draft_id: DraftId,
        *,
        body: DraftUpdateRequest,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Select an exact Draft version or return to automatic versioning

        Checks your version choice against the required version bump, then regenerates the
        existing Draft pull request.

        Send the Draft's `ETag` in `If-Match` to reject an intervening change with 412
        precondition_failed before saving or regenerating. Omitting `If-Match` applies the
        selection to the current Draft. version_next is required; null restores automatic
        selection.

        A `502` response means the selected version was saved, but regeneration failed. Follow
        the error's retryable and suggested_action fields. Repeating an unfinished selection
        resumes generation; repeating a completed selection starts no new work. If using
        If-Match, retrieve the Draft and confirm the saved selection before retrying with its
        current ETag.
        A `409 draft_merged` means the Draft merged; retrieve the Target and select a version on
        its `draft_id`. A `409 target_busy` means the Target is publishing; wait and retry. A
        `409 version_occupied` means the version is already released; retrieve the Draft and
        releases, choose a new version, and retry.
        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        PATCH /drafts/{draft_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return self._core.request(
            "PATCH",
            f"/drafts/{_quote(str(draft_id), safe='')}",
            headers=_headers,
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.update",
        )

    def list_files(
        self,
        draft_id: DraftId,
        *,
        filter: Optional[Literal["conflicted", "customized", "history"]] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[DraftFileRead]:
        """List customized and conflicted files on a Draft

        Lists the Draft's files that differ from the last merged package or need a conflict
        decision, ordered by path, without file content. Each conflict names its kind, the saved
        decision, and the sides you can read with getFile. With `filter=history`, lists files
        affected by a default-branch history rewrite; the list is empty when none is pending.

        Returns `409 resource_changed` while Typeship is carrying the Draft's latest commit
        forward (status working), or when the Draft changes between pages.

        GET /drafts/{draft_id}/files

        Args:
            filter: conflicted: conflicts only. customized: files that differ from the
                last merged package. history: files affected by a default-branch
                history rewrite. Omit for conflicted and customized files.
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
        """
        _query = {
            "filter": filter,
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            f"/drafts/{_quote(str(draft_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.listFiles",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_files_page(
        self,
        draft_id: DraftId,
        *,
        filter: Optional[Literal["conflicted", "customized", "history"]] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftFileListRead:
        """One page of "/drafts/{draft_id}/files", exactly as the API returned it."""
        _query = {
            "filter": filter,
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/drafts/{_quote(str(draft_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.listFiles",
        )

    def resolve(
        self,
        draft_id: DraftId,
        *,
        body: DraftResolveRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Resolve selected Draft files

        Resolves conflicts on the Draft's head_sha: keep yours or generated, or supply final
        content as text or, for binary files, base64. Choosing generated for a customized path
        replaces it with the generated file, or deletes a Draft-only file.

        Conflict decisions are saved together and can be replaced until applied. Choosing
        generated for customized paths commits those changes together on the Draft branch.
        Returns the Draft. When every conflict has a decision, `conflicts.decided` equals
        `conflicts.total` and Typeship continues the Draft and runs checks. Paths that already
        match the Draft change nothing.

        POST /drafts/{draft_id}/resolve
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/drafts/{_quote(str(draft_id), safe='')}/resolve",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.resolve",
        )

    def recover(
        self,
        draft_id: DraftId,
        *,
        body: DraftRecoverRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Approve recovery from rewritten default-branch history

        When the Draft has status `action_required` and reason `history_rewritten`, review
        affected files with `listDraftFiles` and `filter=history`, then approve with the Draft's
        `history_recovery` revisions. Approval saves the recovery without changing Git and
        returns the Draft; the next generation rebuilds it from the rewritten default branch.
        The previous Draft branch stays available, and overlapping code comes back as conflicts
        to resolve. A rewritten Draft branch alone needs no approval.

        POST /drafts/{draft_id}/recover
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/drafts/{_quote(str(draft_id), safe='')}/recover",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.recover",
        )


class AsyncDraftsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[DraftStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[DraftRead]:
        """List Drafts

        Lists open and merged Drafts, newest first. Each Target has one open Draft; each merge
        adds a merged Draft.

        GET /drafts

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            target_id: Only Drafts of this Target.
            status: Only Drafts with this status.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            "/drafts",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[DraftStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftListRead:
        """One page of "/drafts", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/drafts",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.list",
        )

    async def get(
        self,
        draft_id: DraftId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Get a Draft

        Returns the Draft's status. An open Draft also reports its typed reason when action is
        required, next version and its source, compatibility and version assessment, blocking
        errors, checks, and conflict counts. The response carries an `ETag`; send it in
        `If-Match` when updating the Draft to avoid changing a newer version selection.

        GET /drafts/{draft_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/drafts/{_quote(str(draft_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.get",
        )

    async def update(
        self,
        draft_id: DraftId,
        *,
        body: DraftUpdateRequest,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Select an exact Draft version or return to automatic versioning

        Checks your version choice against the required version bump, then regenerates the
        existing Draft pull request.

        Send the Draft's `ETag` in `If-Match` to reject an intervening change with 412
        precondition_failed before saving or regenerating. Omitting `If-Match` applies the
        selection to the current Draft. version_next is required; null restores automatic
        selection.

        A `502` response means the selected version was saved, but regeneration failed. Follow
        the error's retryable and suggested_action fields. Repeating an unfinished selection
        resumes generation; repeating a completed selection starts no new work. If using
        If-Match, retrieve the Draft and confirm the saved selection before retrying with its
        current ETag.
        A `409 draft_merged` means the Draft merged; retrieve the Target and select a version on
        its `draft_id`. A `409 target_busy` means the Target is publishing; wait and retry. A
        `409 version_occupied` means the version is already released; retrieve the Draft and
        releases, choose a new version, and retry.
        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        PATCH /drafts/{draft_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return await self._core.arequest(
            "PATCH",
            f"/drafts/{_quote(str(draft_id), safe='')}",
            headers=_headers,
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.update",
        )

    def list_files(
        self,
        draft_id: DraftId,
        *,
        filter: Optional[Literal["conflicted", "customized", "history"]] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[DraftFileRead]:
        """List customized and conflicted files on a Draft

        Lists the Draft's files that differ from the last merged package or need a conflict
        decision, ordered by path, without file content. Each conflict names its kind, the saved
        decision, and the sides you can read with getFile. With `filter=history`, lists files
        affected by a default-branch history rewrite; the list is empty when none is pending.

        Returns `409 resource_changed` while Typeship is carrying the Draft's latest commit
        forward (status working), or when the Draft changes between pages.

        GET /drafts/{draft_id}/files

        Args:
            filter: conflicted: conflicts only. customized: files that differ from the
                last merged package. history: files affected by a default-branch
                history rewrite. Omit for conflicted and customized files.
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
        """
        _query = {
            "filter": filter,
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            f"/drafts/{_quote(str(draft_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.listFiles",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_files_page(
        self,
        draft_id: DraftId,
        *,
        filter: Optional[Literal["conflicted", "customized", "history"]] = None,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftFileListRead:
        """One page of "/drafts/{draft_id}/files", exactly as the API returned it."""
        _query = {
            "filter": filter,
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/drafts/{_quote(str(draft_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.listFiles",
        )

    async def resolve(
        self,
        draft_id: DraftId,
        *,
        body: DraftResolveRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Resolve selected Draft files

        Resolves conflicts on the Draft's head_sha: keep yours or generated, or supply final
        content as text or, for binary files, base64. Choosing generated for a customized path
        replaces it with the generated file, or deletes a Draft-only file.

        Conflict decisions are saved together and can be replaced until applied. Choosing
        generated for customized paths commits those changes together on the Draft branch.
        Returns the Draft. When every conflict has a decision, `conflicts.decided` equals
        `conflicts.total` and Typeship continues the Draft and runs checks. Paths that already
        match the Draft change nothing.

        POST /drafts/{draft_id}/resolve
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/drafts/{_quote(str(draft_id), safe='')}/resolve",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.resolve",
        )

    async def recover(
        self,
        draft_id: DraftId,
        *,
        body: DraftRecoverRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftResponseRead:
        """Approve recovery from rewritten default-branch history

        When the Draft has status `action_required` and reason `history_rewritten`, review
        affected files with `listDraftFiles` and `filter=history`, then approve with the Draft's
        `history_recovery` revisions. Approval saves the recovery without changing Git and
        returns the Draft; the next generation rebuilds it from the rewritten default branch.
        The previous Draft branch stays available, and overlapping code comes back as conflicts
        to resolve. A rewritten Draft branch alone needs no approval.

        POST /drafts/{draft_id}/recover
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/drafts/{_quote(str(draft_id), safe='')}/recover",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="drafts.recover",
        )
