"""typeship — generate.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class GenerateResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def run(
        self,
        *,
        body: GenerateRequest,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> GenerationResultRead:
        """Generate one Target from a Definition

        Returns one generated package without saving a Project or retaining source files or
        generated files.

        Anonymous and Free requests include the first 25 operations. Paid plans include all
        operations. Anonymous requests are rate limited by IP address. Check `limits` for
        omitted operations; an invalid API key returns `401`.

        An anonymous URL request without source headers may return `claim.url`. Sign in through
        that link within seven days to save the recipe as a Project.

        POST /generate

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "409": "ConflictError",
            "413": "PayloadTooLargeError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "default": "ApiResponseError",
        }
        return self._core.request(
            "POST",
            "/generate",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{},{"apiKey":[]}],
            request_options=request_options,
            schema_key="generate.run",
        )


class AsyncGenerateResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def run(
        self,
        *,
        body: GenerateRequest,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> GenerationResultRead:
        """Generate one Target from a Definition

        Returns one generated package without saving a Project or retaining source files or
        generated files.

        Anonymous and Free requests include the first 25 operations. Paid plans include all
        operations. Anonymous requests are rate limited by IP address. Check `limits` for
        omitted operations; an invalid API key returns `401`.

        An anonymous URL request without source headers may return `claim.url`. Sign in through
        that link within seven days to save the recipe as a Project.

        POST /generate

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "409": "ConflictError",
            "413": "PayloadTooLargeError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "default": "ApiResponseError",
        }
        return await self._core.arequest(
            "POST",
            "/generate",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{},{"apiKey":[]}],
            request_options=request_options,
            schema_key="generate.run",
        )
