"""typeship — generate.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class GenerateResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def run(self, *, spec: SpecInput, platforms: Optional[List[Literal["sdk", "cli", "mcp"]]] = None, language: Optional[Literal["typescript", "python", "go"]] = None, package_name: Optional[str] = None, config: Optional[Config] = None, request_options: Optional[RequestOptions] = None) -> GenerationResult:
        """Generate a package from a spec

        Stateless generation: nothing is stored. Returns the full generated
        package as files. Works without an API key: anonymous calls generate
        the first 25 operations, rate limited per IP address, and the
        response's `limits` object says what was held back and where to lift
        it; anonymous calls from a spec URL also carry `claim.url`, a link
        that turns the run into a project once a person signs in. With a key, the free plan generates the first 25 operations and
        paid plans generate the whole spec. A present but invalid key is a
        401, not a downgrade to anonymous.

        POST /generate

        Args:
            platforms: Artifacts to generate from the spec. Defaults to [sdk].
            language: Language to generate. Python and Go produce the SDK only; the CLI
                and MCP server are TypeScript artifacts and are skipped with a warning
                when requested alongside them.
            package_name: npm name override for the generated package.
        """
        _body = {
            "spec": spec,
            "platforms": platforms,
            "language": language,
            "package_name": package_name,
            "config": config,
        }
        _body = {k: v for k, v in _body.items() if v is not None}
        return self._core.request("POST", "/generate", body=_body, errors={"401": "UnauthorizedError", "413": "PayloadTooLargeError", "422": "UnprocessableEntityError", "default": "ApiResponseError"}, request_options=request_options, schema_key="generate.run")


class AsyncGenerateResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def run(self, *, spec: SpecInput, platforms: Optional[List[Literal["sdk", "cli", "mcp"]]] = None, language: Optional[Literal["typescript", "python", "go"]] = None, package_name: Optional[str] = None, config: Optional[Config] = None, request_options: Optional[RequestOptions] = None) -> GenerationResult:
        """Generate a package from a spec

        Stateless generation: nothing is stored. Returns the full generated
        package as files. Works without an API key: anonymous calls generate
        the first 25 operations, rate limited per IP address, and the
        response's `limits` object says what was held back and where to lift
        it; anonymous calls from a spec URL also carry `claim.url`, a link
        that turns the run into a project once a person signs in. With a key, the free plan generates the first 25 operations and
        paid plans generate the whole spec. A present but invalid key is a
        401, not a downgrade to anonymous.

        POST /generate

        Args:
            platforms: Artifacts to generate from the spec. Defaults to [sdk].
            language: Language to generate. Python and Go produce the SDK only; the CLI
                and MCP server are TypeScript artifacts and are skipped with a warning
                when requested alongside them.
            package_name: npm name override for the generated package.
        """
        _body = {
            "spec": spec,
            "platforms": platforms,
            "language": language,
            "package_name": package_name,
            "config": config,
        }
        _body = {k: v for k, v in _body.items() if v is not None}
        return await self._core.arequest("POST", "/generate", body=_body, errors={"401": "UnauthorizedError", "413": "PayloadTooLargeError", "422": "UnprocessableEntityError", "default": "ApiResponseError"}, request_options=request_options, schema_key="generate.run")

