"""typeship — generations.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
import asyncio
import time
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class GenerationsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[GenerationStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[GenerationSummaryRead]:
        """List generations

        GET /generations

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            project_id: Only Generations in this Project.
            target_id: Only Generations of this Target.
            status: Only Generations with this status.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            "/generations",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[GenerationStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> GenerationListRead:
        """One page of "/generations", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/generations",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.list",
        )

    def get(
        self,
        generation_id: GenerationId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> GenerationResponseRead:
        """Get a generation

        Returns the status of that Generation. `queued` and `running` mean generation is still
        in progress. `completed` means generated files are saved, not that repository delivery
        or a Draft is complete. List its files with listGenerationFiles and read each with
        getFile.

        GET /generations/{generation_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/generations/{_quote(str(generation_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.get",
        )

    def list_files(
        self,
        generation_id: GenerationId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[FileRead]:
        """List a Generation's files

        Lists the generated package's files, ordered by path. Read content with getFile.

        GET /generations/{generation_id}/files

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            f"/generations/{_quote(str(generation_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.listFiles",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_files_page(
        self,
        generation_id: GenerationId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> FileListRead:
        """One page of "/generations/{generation_id}/files", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/generations/{_quote(str(generation_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.listFiles",
        )

    def wait(self, generation_id: GenerationId, *, interval: float = 3.0,
             timeout: float = 600.0, request_options: Optional[RequestOptions] = None) -> GenerationResponseRead:
        """Poll until generated files are saved or the Generation fails."""
        deadline = time.monotonic() + timeout
        while True:
            result = self.get(generation_id, request_options=request_options)
            if result["status"] not in ("queued", "running"):
                return result
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TimeoutError(f"Timed out waiting for Generation {generation_id}.")
            time.sleep(min(interval, remaining))


class AsyncGenerationsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[GenerationStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[GenerationSummaryRead]:
        """List generations

        GET /generations

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            project_id: Only Generations in this Project.
            target_id: Only Generations of this Target.
            status: Only Generations with this status.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            "/generations",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        target_id: Optional[TargetId] = None,
        status: Optional[GenerationStatus] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> GenerationListRead:
        """One page of "/generations", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
            "target_id": target_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/generations",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.list",
        )

    async def get(
        self,
        generation_id: GenerationId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> GenerationResponseRead:
        """Get a generation

        Returns the status of that Generation. `queued` and `running` mean generation is still
        in progress. `completed` means generated files are saved, not that repository delivery
        or a Draft is complete. List its files with listGenerationFiles and read each with
        getFile.

        GET /generations/{generation_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/generations/{_quote(str(generation_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.get",
        )

    def list_files(
        self,
        generation_id: GenerationId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[FileRead]:
        """List a Generation's files

        Lists the generated package's files, ordered by path. Read content with getFile.

        GET /generations/{generation_id}/files

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            f"/generations/{_quote(str(generation_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.listFiles",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_files_page(
        self,
        generation_id: GenerationId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> FileListRead:
        """One page of "/generations/{generation_id}/files", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/generations/{_quote(str(generation_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="generations.listFiles",
        )

    async def wait(self, generation_id: GenerationId, *, interval: float = 3.0,
                   timeout: float = 600.0, request_options: Optional[RequestOptions] = None) -> GenerationResponseRead:
        """Poll until generated files are saved or the Generation fails."""
        deadline = time.monotonic() + timeout
        while True:
            result = await self.get(generation_id, request_options=request_options)
            if result["status"] not in ("queued", "running"):
                return result
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                raise TimeoutError(f"Timed out waiting for Generation {generation_id}.")
            await asyncio.sleep(min(interval, remaining))
