"""typeship — organization.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class OrganizationResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def get(self, *, request_options: Optional[RequestOptions] = None) -> OrganizationRead:
        """The organization behind the presented credentials

        Returns the organization associated with your credential. The Typeship CLI uses this
        endpoint for `whoami`.

        GET /organization
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/organization",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="organization.get",
        )


class AsyncOrganizationResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def get(self, *, request_options: Optional[RequestOptions] = None) -> OrganizationRead:
        """The organization behind the presented credentials

        Returns the organization associated with your credential. The Typeship CLI uses this
        endpoint for `whoami`.

        GET /organization
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/organization",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="organization.get",
        )
