"""typeship — publications.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class PublicationsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def get(
        self,
        publication_id: PublicationId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> PublicationResponseRead:
        """Get a Publication

        Returns the registry publishing status for a release. A status in another organization
        returns 404 resource_not_found.

        GET /publications/{publication_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/publications/{_quote(str(publication_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="publications.get",
        )

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        release_id: Optional[ReleaseId] = None,
        status: Optional[Literal["queued", "running", "completed", "failed"]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[PublicationRead]:
        """List Publications

        GET /publications

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            release_id: Only publications of this release.
            status: Only publications with this status.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "release_id": release_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            "/publications",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="publications.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        release_id: Optional[ReleaseId] = None,
        status: Optional[Literal["queued", "running", "completed", "failed"]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> PublicationListRead:
        """One page of "/publications", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "release_id": release_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/publications",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="publications.list",
        )


class AsyncPublicationsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def get(
        self,
        publication_id: PublicationId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> PublicationResponseRead:
        """Get a Publication

        Returns the registry publishing status for a release. A status in another organization
        returns 404 resource_not_found.

        GET /publications/{publication_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/publications/{_quote(str(publication_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="publications.get",
        )

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        release_id: Optional[ReleaseId] = None,
        status: Optional[Literal["queued", "running", "completed", "failed"]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[PublicationRead]:
        """List Publications

        GET /publications

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            release_id: Only publications of this release.
            status: Only publications with this status.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "release_id": release_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            "/publications",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="publications.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        release_id: Optional[ReleaseId] = None,
        status: Optional[Literal["queued", "running", "completed", "failed"]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> PublicationListRead:
        """One page of "/publications", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "release_id": release_id,
            "status": status,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/publications",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="publications.list",
        )
