"""typeship — releases.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class ReleasesResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[ReleaseRead]:
        """List releases

        GET /releases

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            target_id: Only releases of this Target.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            "/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseListRead:
        """One page of "/releases", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.list",
        )

    def get(
        self,
        release_id: ReleaseId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseResponseRead:
        """Get a release

        GET /releases/{release_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/releases/{_quote(str(release_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.get",
        )

    def retry(
        self,
        release_id: ReleaseId,
        *,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseResponseRead:
        """Retry publishing a release

        Queues every failed or queued Publication of the release and starts its repository
        publishing workflow again. Publishing uses that release's version and accepted commit,
        even if a newer Draft or release exists. Completed Publications are not repeated.

        Returns `202` with the Release. Get the Release until each Publication reaches
        `completed` or `failed`.

        A `409 publication_not_retryable` means no Publication is queued or failed. A `502
        repository_unavailable` means the repository publishing workflow could not be
        dispatched, and nothing was changed.

        POST /releases/{release_id}/retry

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return self._core.request(
            "POST",
            f"/releases/{_quote(str(release_id), safe='')}/retry",
            headers=_headers,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.retry",
        )


class AsyncReleasesResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[ReleaseRead]:
        """List releases

        GET /releases

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 input_invalid. List query parameters
                must appear only once; repeated or unrecognized parameters return 400
                query_param_invalid.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty or malformed cursors, and
                cursors issued for different filters, return 400 cursor_invalid; start
                again from the first page. Repeated cursors return 400
                query_param_invalid. The page limit may change between requests.
            target_id: Only releases of this Target.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            "/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        target_id: Optional[TargetId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseListRead:
        """One page of "/releases", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "target_id": target_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.list",
        )

    async def get(
        self,
        release_id: ReleaseId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseResponseRead:
        """Get a release

        GET /releases/{release_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/releases/{_quote(str(release_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.get",
        )

    async def retry(
        self,
        release_id: ReleaseId,
        *,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseResponseRead:
        """Retry publishing a release

        Queues every failed or queued Publication of the release and starts its repository
        publishing workflow again. Publishing uses that release's version and accepted commit,
        even if a newer Draft or release exists. Completed Publications are not repeated.

        Returns `202` with the Release. Get the Release until each Publication reaches
        `completed` or `failed`.

        A `409 publication_not_retryable` means no Publication is queued or failed. A `502
        repository_unavailable` means the repository publishing workflow could not be
        dispatched, and nothing was changed.

        POST /releases/{release_id}/retry

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return await self._core.arequest(
            "POST",
            f"/releases/{_quote(str(release_id), safe='')}/retry",
            headers=_headers,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="releases.retry",
        )
