"""typeship — specRevisions.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class SpecRevisionsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[SpecRevision]:
        """List specification revisions

        Immutable snapshots of the exact source text this project consumed, newest first. Raw
        content is available from each revision's content endpoint and is never embedded in a
        list response.

        GET /projects/{project_id}/spec_revisions

        Args:
            limit: Maximum number of resources to return.
            cursor: Opaque cursor from the preceding page's next_cursor.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.paginate(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/spec_revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionList:
        """One page of "/projects/{project_id}/spec_revisions", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/spec_revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.list",
        )

    def retrieve(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevision:
        """Retrieve a specification revision

        Metadata for one immutable source snapshot. Fetch raw source text from the content
        endpoint so metadata responses stay small and predictable.

        GET /spec_revisions/{spec_revision_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/spec_revisions/{_quote(str(spec_revision_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.retrieve",
        )

    def retrieve_content(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> str:
        """Retrieve a specification revision's raw text

        Returns the exact source text identified by the revision's SHA-256 digest, suitable for
        saving or piping directly into a diff.

        GET /spec_revisions/{spec_revision_id}/content
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/spec_revisions/{_quote(str(spec_revision_id), safe='')}/content",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.retrieveContent",
        )


class AsyncSpecRevisionsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[SpecRevision]:
        """List specification revisions

        Immutable snapshots of the exact source text this project consumed, newest first. Raw
        content is available from each revision's content endpoint and is never embedded in a
        list response.

        GET /projects/{project_id}/spec_revisions

        Args:
            limit: Maximum number of resources to return.
            cursor: Opaque cursor from the preceding page's next_cursor.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.apaginate(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/spec_revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionList:
        """One page of "/projects/{project_id}/spec_revisions", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/spec_revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.list",
        )

    async def retrieve(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevision:
        """Retrieve a specification revision

        Metadata for one immutable source snapshot. Fetch raw source text from the content
        endpoint so metadata responses stay small and predictable.

        GET /spec_revisions/{spec_revision_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/spec_revisions/{_quote(str(spec_revision_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.retrieve",
        )

    async def retrieve_content(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> str:
        """Retrieve a specification revision's raw text

        Returns the exact source text identified by the revision's SHA-256 digest, suitable for
        saving or piping directly into a diff.

        GET /spec_revisions/{spec_revision_id}/content
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/spec_revisions/{_quote(str(spec_revision_id), safe='')}/content",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="specRevisions.retrieveContent",
        )
