"""typeship — specRevisions.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class SpecRevisionsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        spec_id: Optional[SpecId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[SpecRevisionRead]:
        """List Spec Revisions

        Lists Spec Revisions, newest first. Source content is not included; list a revision's
        files with listSpecRevisionFiles.

        GET /spec-revisions

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
            spec_id: Only revisions of this Spec.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "spec_id": spec_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            "/spec-revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        spec_id: Optional[SpecId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionListRead:
        """One page of "/spec-revisions", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "spec_id": spec_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/spec-revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.list",
        )

    def get(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        include: Optional[Literal["diagnostics"]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionResponseRead:
        """Get a Spec Revision

        Returns metadata for a saved Spec Revision with a Diagnostics summary. Pass
        `include=diagnostics` to add every Diagnostic, evaluated with the Spec's current patches
        and Diagnostic policy. List its source files and resolved document with
        listSpecRevisionFiles.

        GET /spec-revisions/{spec_revision_id}

        Args:
            include: Add related data to the response. `diagnostics` adds the
                `diagnostics` and `patch_diagnostics` arrays.
        """
        _query = {
            "include": include,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/spec-revisions/{_quote(str(spec_revision_id), safe='')}",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.get",
        )

    def list_files(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[SpecRevisionFileRead]:
        """List a Spec Revision's files

        Lists the captured source files and the resolved document Typeship generated from,
        ordered by path. Read content with getFile.

        GET /spec-revisions/{spec_revision_id}/files

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            f"/spec-revisions/{_quote(str(spec_revision_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.listFiles",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_files_page(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionFileListRead:
        """One page of "/spec-revisions/{spec_revision_id}/files", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/spec-revisions/{_quote(str(spec_revision_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.listFiles",
        )


class AsyncSpecRevisionsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        spec_id: Optional[SpecId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[SpecRevisionRead]:
        """List Spec Revisions

        Lists Spec Revisions, newest first. Source content is not included; list a revision's
        files with listSpecRevisionFiles.

        GET /spec-revisions

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
            spec_id: Only revisions of this Spec.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "spec_id": spec_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            "/spec-revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        spec_id: Optional[SpecId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionListRead:
        """One page of "/spec-revisions", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "spec_id": spec_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/spec-revisions",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.list",
        )

    async def get(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        include: Optional[Literal["diagnostics"]] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionResponseRead:
        """Get a Spec Revision

        Returns metadata for a saved Spec Revision with a Diagnostics summary. Pass
        `include=diagnostics` to add every Diagnostic, evaluated with the Spec's current patches
        and Diagnostic policy. List its source files and resolved document with
        listSpecRevisionFiles.

        GET /spec-revisions/{spec_revision_id}

        Args:
            include: Add related data to the response. `diagnostics` adds the
                `diagnostics` and `patch_diagnostics` arrays.
        """
        _query = {
            "include": include,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/spec-revisions/{_quote(str(spec_revision_id), safe='')}",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.get",
        )

    def list_files(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[SpecRevisionFileRead]:
        """List a Spec Revision's files

        Lists the captured source files and the resolved document Typeship generated from,
        ordered by path. Read content with getFile.

        GET /spec-revisions/{spec_revision_id}/files

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            f"/spec-revisions/{_quote(str(spec_revision_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.listFiles",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_files_page(
        self,
        spec_revision_id: SpecRevisionId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRevisionFileListRead:
        """One page of "/spec-revisions/{spec_revision_id}/files", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/spec-revisions/{_quote(str(spec_revision_id), safe='')}/files",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specRevisions.listFiles",
        )
