"""typeship — specs.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class SpecsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def get(self, spec_id: SpecId, *, request_options: Optional[RequestOptions] = None) -> SpecRead:
        """Get a Spec

        GET /specs/{spec_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/specs/{_quote(str(spec_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specs.get",
        )

    def update(
        self,
        spec_id: SpecId,
        *,
        body: SpecUpdateRequest,
        if_match: Optional[str] = None,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRead:
        """Update a Spec

        Resolves the source files before saving the update and records a new Spec Revision when
        the source changes.
        Omitted fields remain unchanged; supplied objects and arrays replace the whole field.
        If the Spec or its Project configuration changes during validation, returns 409
        resource_changed without saving the rejected update. Retrieve the current Spec and
        Project, reconcile your changes,
        and submit a new request with a new Idempotency-Key if using one.

        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        PATCH /specs/{spec_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "If-Match": if_match,
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "PATCH",
            f"/specs/{_quote(str(spec_id), safe='')}",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specs.update",
        )

    def refresh(
        self,
        spec_id: SpecId,
        *,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRead:
        """Refresh a Spec

        Fetches the configured source now and creates a new Spec Revision only when its content
        changes. Diagnostics then reads that revision. If automatic generation is enabled,
        refresh queues generation for active Targets even when the source is unchanged. A `502
        follow_up_failed` means the new Spec Revision was recorded but generation could not be
        queued.

        POST /specs/{spec_id}/refresh

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return self._core.request(
            "POST",
            f"/specs/{_quote(str(spec_id), safe='')}/refresh",
            headers=_headers,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specs.refresh",
        )


class AsyncSpecsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def get(
        self,
        spec_id: SpecId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRead:
        """Get a Spec

        GET /specs/{spec_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/specs/{_quote(str(spec_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specs.get",
        )

    async def update(
        self,
        spec_id: SpecId,
        *,
        body: SpecUpdateRequest,
        if_match: Optional[str] = None,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRead:
        """Update a Spec

        Resolves the source files before saving the update and records a new Spec Revision when
        the source changes.
        Omitted fields remain unchanged; supplied objects and arrays replace the whole field.
        If the Spec or its Project configuration changes during validation, returns 409
        resource_changed without saving the rejected update. Retrieve the current Spec and
        Project, reconcile your changes,
        and submit a new request with a new Idempotency-Key if using one.

        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        PATCH /specs/{spec_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "If-Match": if_match,
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "PATCH",
            f"/specs/{_quote(str(spec_id), safe='')}",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specs.update",
        )

    async def refresh(
        self,
        spec_id: SpecId,
        *,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> SpecRead:
        """Refresh a Spec

        Fetches the configured source now and creates a new Spec Revision only when its content
        changes. Diagnostics then reads that revision. If automatic generation is enabled,
        refresh queues generation for active Targets even when the source is unchanged. A `502
        follow_up_failed` means the new Spec Revision was recorded but generation could not be
        queued.

        POST /specs/{spec_id}/refresh

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return await self._core.arequest(
            "POST",
            f"/specs/{_quote(str(spec_id), safe='')}/refresh",
            headers=_headers,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="specs.refresh",
        )
