"""typeship — targets.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class TargetsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        project_id: ProjectId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetListRead:
        """List a project's Targets

        GET /projects/{project_id}/targets
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.list",
        )

    def create(
        self,
        project_id: ProjectId,
        *,
        body: TargetFields,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetRead:
        """Create an independently configured Target

        Several Targets may use the same generator with distinct configuration, Deliveries, and
        release streams.

        POST /projects/{project_id}/targets
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "POST",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            body=body,
            errors=_errors,
            request_options=request_options,
            schema_key="targets.create",
        )

    def retrieve(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetRead:
        """Retrieve a Target

        GET /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.retrieve",
        )

    def delete(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete an unused Target

        Targets with Generation or release history, or an active release candidate, must be
        disabled instead.

        DELETE /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "DELETE",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
        )

    def update(
        self,
        target_id: TargetId,
        *,
        body: TargetUpdateRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetRead:
        """Update a Target, its Deliveries, or its next reviewed version

        PATCH /targets/{target_id}
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}",
            body=body,
            errors=_errors,
            request_options=request_options,
            schema_key="targets.update",
        )

    def list_releases(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseListRead:
        """List immutable releases for a Target

        GET /targets/{target_id}/releases
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/releases",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.listReleases",
        )

    def retrieve_release(
        self,
        target_release_id: TargetReleaseId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseRead:
        """Retrieve an immutable Target release

        GET /target_releases/{target_release_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return self._core.request(
            "GET",
            f"/target_releases/{_quote(str(target_release_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.retrieveRelease",
        )


class AsyncTargetsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def list(
        self,
        project_id: ProjectId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetListRead:
        """List a project's Targets

        GET /projects/{project_id}/targets
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.list",
        )

    async def create(
        self,
        project_id: ProjectId,
        *,
        body: TargetFields,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetRead:
        """Create an independently configured Target

        Several Targets may use the same generator with distinct configuration, Deliveries, and
        release streams.

        POST /projects/{project_id}/targets
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "POST",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            body=body,
            errors=_errors,
            request_options=request_options,
            schema_key="targets.create",
        )

    async def retrieve(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetRead:
        """Retrieve a Target

        GET /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.retrieve",
        )

    async def delete(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> None:
        """Delete an unused Target

        Targets with Generation or release history, or an active release candidate, must be
        disabled instead.

        DELETE /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "DELETE",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
        )

    async def update(
        self,
        target_id: TargetId,
        *,
        body: TargetUpdateRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetRead:
        """Update a Target, its Deliveries, or its next reviewed version

        PATCH /targets/{target_id}
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}",
            body=body,
            errors=_errors,
            request_options=request_options,
            schema_key="targets.update",
        )

    async def list_releases(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseListRead:
        """List immutable releases for a Target

        GET /targets/{target_id}/releases
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/releases",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.listReleases",
        )

    async def retrieve_release(
        self,
        target_release_id: TargetReleaseId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseRead:
        """Retrieve an immutable Target release

        GET /target_releases/{target_release_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
        }
        return await self._core.arequest(
            "GET",
            f"/target_releases/{_quote(str(target_release_id), safe='')}",
            errors=_errors,
            idempotent=True,
            request_options=request_options,
            schema_key="targets.retrieveRelease",
        )
