"""typeship — targets.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class TargetsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[TargetRead]:
        """List Targets

        GET /targets

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
            project_id: Only Targets in this Project.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            "/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetListRead:
        """One page of "/targets", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            "/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
        )

    def create(
        self,
        *,
        body: TargetCreateRequest,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Create an independently configured Target

        Creates a Target with its own configuration, Deliveries, and release history. Multiple
        Targets can use the same generator.

        POST /targets

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            "/targets",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.create",
        )

    def get(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Get a Target

        GET /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.get",
        )

    def delete(
        self,
        target_id: TargetId,
        *,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DeletedTargetRead:
        """Delete an unused Target

        Deletes a Target with no Generation history, release history, or active Draft. A `409
        resource_has_dependencies` means one of those resources still depends on it. Retrieve
        the Target, disable it instead, or resolve the dependency before retrying.

        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        DELETE /targets/{target_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "DELETE",
            f"/targets/{_quote(str(target_id), safe='')}",
            headers=_headers,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.delete",
        )

    def update(
        self,
        target_id: TargetId,
        *,
        body: TargetUpdateRequest,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Update a Target or its Deliveries

        Omitted fields keep their current values. Supplied config, checks, and deliveries
        replace their complete stored values.
        With Project auto_generate enabled, changing Target config, checks, or Deliveries queues
        that Target's Generation. A queued or running Target reuses that Generation.
        Omitting If-Match applies the update to the current resource; with If-Match, a stale
        ETag returns 412 precondition_failed without saving.
        Select the next version through PATCH /drafts/{draft_id} on the Target's draft_id.

        A `409 target_busy` means the Target is publishing; wait for it to finish. A `409
        delivery_conflict` means another Target owns the requested repository tree; retrieve
        both Targets, choose a free destination, and retry.
        A `502` response means the update was saved, but retiring an obsolete review or
        regenerating the Target failed. Retrieve the Target and follow the error's retryable and
        suggested_action fields.
        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        PATCH /targets/{target_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return self._core.request(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}",
            headers=_headers,
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.update",
        )

    def adopt(
        self,
        target_id: TargetId,
        *,
        body: TargetAdoption,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseResponseRead:
        """Adopt a verified existing package as the latest release

        Checks the repository tag, package metadata, and registry artifact, then records the
        package as an Imported latest release. Opens the first Typeship Draft at the next major
        version; review it to establish the baseline for preserving existing code.

        POST /targets/{target_id}/adopt

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/adopt",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.adopt",
        )


class AsyncTargetsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[TargetRead]:
        """List Targets

        GET /targets

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same organization, operation, filters, and ordering that issued it.
                Omit to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
            project_id: Only Targets in this Project.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            "/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        project_id: Optional[ProjectId] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetListRead:
        """One page of "/targets", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
            "project_id": project_id,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            "/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
        )

    async def create(
        self,
        *,
        body: TargetCreateRequest,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Create an independently configured Target

        Creates a Target with its own configuration, Deliveries, and release history. Multiple
        Targets can use the same generator.

        POST /targets

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            "/targets",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.create",
        )

    async def get(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Get a Target

        GET /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.get",
        )

    async def delete(
        self,
        target_id: TargetId,
        *,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DeletedTargetRead:
        """Delete an unused Target

        Deletes a Target with no Generation history, release history, or active Draft. A `409
        resource_has_dependencies` means one of those resources still depends on it. Retrieve
        the Target, disable it instead, or resolve the dependency before retrying.

        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        DELETE /targets/{target_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "DELETE",
            f"/targets/{_quote(str(target_id), safe='')}",
            headers=_headers,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.delete",
        )

    async def update(
        self,
        target_id: TargetId,
        *,
        body: TargetUpdateRequest,
        if_match: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Update a Target or its Deliveries

        Omitted fields keep their current values. Supplied config, checks, and deliveries
        replace their complete stored values.
        With Project auto_generate enabled, changing Target config, checks, or Deliveries queues
        that Target's Generation. A queued or running Target reuses that Generation.
        Omitting If-Match applies the update to the current resource; with If-Match, a stale
        ETag returns 412 precondition_failed without saving.
        Select the next version through PATCH /drafts/{draft_id} on the Target's draft_id.

        A `409 target_busy` means the Target is publishing; wait for it to finish. A `409
        delivery_conflict` means another Target owns the requested repository tree; retrieve
        both Targets, choose a free destination, and retry.
        A `502` response means the update was saved, but retiring an obsolete review or
        regenerating the Target failed. Retrieve the Target and follow the error's retryable and
        suggested_action fields.
        See [conditional writes](https://typeship.dev/docs/typeship-api#conditional-writes) for
        ETag and If-Match.

        PATCH /targets/{target_id}

        Args:
            if_match: ETag from a preceding response. The write applies only if the
                resource still has that version; otherwise it returns 412
                precondition_failed without changes. Omit to write the current version.
                See https://typeship.dev/docs/typeship-api#conditional-writes.
        """
        _headers = {
            "If-Match": if_match,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "412": "PreconditionFailedError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return await self._core.arequest(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}",
            headers=_headers,
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.update",
        )

    async def adopt(
        self,
        target_id: TargetId,
        *,
        body: TargetAdoption,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> ReleaseResponseRead:
        """Adopt a verified existing package as the latest release

        Checks the repository tag, package metadata, and registry artifact, then records the
        package as an Imported latest release. Opens the first Typeship Draft at the next major
        version; review it to establish the baseline for preserving existing code.

        POST /targets/{target_id}/adopt

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated organization and operation; generation
                without an organization uses a hashed network identity. Retrying the
                same method, path, query, If-Match header, and JSON body replays the
                original response. Reusing the key with changed intent returns 409.
                After expiry the key starts a new write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/adopt",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.adopt",
        )
