"""typeship — targets.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, AsyncIterator, Dict, Iterator, List, Literal, Optional, Union
from urllib.parse import quote as _quote

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class TargetsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[TargetRead]:
        """List a project's Targets

        GET /projects/{project_id}/targets

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same account, operation, filters, and ordering that issued it. Omit
                to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_page(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetListRead:
        """One page of "/projects/{project_id}/targets", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
        )

    def create(
        self,
        project_id: ProjectId,
        *,
        body: TargetFields,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Create an independently configured Target

        Creates a Target with its own configuration, Deliveries, and release history. Multiple
        Targets can use the same generator.

        POST /projects/{project_id}/targets

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.create",
        )

    def retrieve(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Retrieve a Target

        GET /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieve",
        )

    def delete(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DeletedTargetRead:
        """Delete an unused Target

        Deletes a Target with no Generation history, release history, or active Draft. Disable a
        Target instead if it has any of these.

        DELETE /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "DELETE",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.delete",
        )

    def update(
        self,
        target_id: TargetId,
        *,
        body: TargetUpdateRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Update a Target, its Deliveries, or its next reviewed version

        Omitted fields keep their current values. Supplied config, checks, and deliveries
        replace their complete stored values.
        Updates have no revision precondition. Concurrent updates preserve omitted fields, and
        the last saved update to a supplied field wins.
        Send proposed_version by itself; use the Draft endpoint for a version selection with an
        optional revision precondition.

        A `502` response means the selected version was saved, but regeneration failed.

        PATCH /targets/{target_id}
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return self._core.request(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.update",
        )

    def list_releases(
        self,
        target_id: TargetId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> Iterator[TargetReleaseRead]:
        """List immutable releases for a Target

        GET /targets/{target_id}/releases

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same account, operation, filters, and ordering that issued it. Omit
                to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.paginate(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.listReleases",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    def list_releases_page(
        self,
        target_id: TargetId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseListRead:
        """One page of "/targets/{target_id}/releases", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.listReleases",
        )

    def retrieve_draft(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetDraftResponseRead:
        """Retrieve a Target's rolling Draft release

        Returns Current's version, the proposed Draft version, readiness, and commit. Pass
        `revision` as `expected_revision` when updating the Draft to avoid changing a newer
        candidate.

        GET /targets/{target_id}/draft
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/draft",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveDraft",
        )

    def update_draft(
        self,
        target_id: TargetId,
        *,
        body: TargetDraftUpdate,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetDraftResponseRead:
        """Select an exact Draft version or return to automatic versioning

        Checks your version choice against the required version bump, then regenerates the
        existing Draft pull request.

        Send the last read revision as expected_revision to reject an intervening change with
        409 stale_release_revision before saving or regenerating.
        The precondition is optional; omitting it applies the selection to the current Draft.
        Version is required; null restores automatic selection.

        A `502` response means the selected version was saved, but regeneration failed.

        PATCH /targets/{target_id}/draft
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return self._core.request(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}/draft",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.updateDraft",
        )

    def adopt_release(
        self,
        target_id: TargetId,
        *,
        body: TargetAdoption,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseResponseRead:
        """Adopt a verified existing package as Current

        Checks the repository tag, package metadata, and registry artifact, then records the
        package as an Imported Current release. Opens the first Typeship Draft at the next major
        version; review it to establish the baseline for preserving existing code.

        POST /targets/{target_id}/adopt

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/adopt",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.adoptRelease",
        )

    def retrieve_release(
        self,
        target_release_id: TargetReleaseId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseResponseRead:
        """Retrieve an immutable Target release

        GET /target_releases/{target_release_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/target_releases/{_quote(str(target_release_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveRelease",
        )

    def republish_release(
        self,
        target_release_id: TargetReleaseId,
        *,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseResponseRead:
        """Retry publication of an exact Target release

        Retries publication of the specified release through its repository workflow. Uses that
        release's version and accepted commit, even if a newer Draft or release exists.

        A `502` response means the repository publication workflow could not be dispatched.

        POST /target_releases/{target_release_id}/republish

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return self._core.request(
            "POST",
            f"/target_releases/{_quote(str(target_release_id), safe='')}/republish",
            headers=_headers,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.republishRelease",
        )

    def retrieve_draft_customizations(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftCustomizationsResponseRead:
        """Inspect customizations on a Draft

        Returns the changed file paths from the latest Draft inspection. Read conflicts for all
        three file versions, and read the Draft for package-check readiness.

        GET /targets/{target_id}/draft/customizations
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/draft/customizations",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveDraftCustomizations",
        )

    def retrieve_draft_conflicts(
        self,
        target_id: TargetId,
        *,
        path: Optional[str] = None,
        after_path: Optional[str] = None,
        content_offset: Optional[int] = None,
        expected_head_revision: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftConflictsResponseRead:
        """Inspect conflicts on a Draft

        Returns every conflict with its base, repository, and incoming file bytes and modes in
        one response. An absent file is null. incoming_source distinguishes generated changes,
        default-branch changes, and recovered saved Draft code. Saved decisions require a
        separate Generate before conflicts clear.

        GET /targets/{target_id}/draft/conflicts

        Args:
            path: Inspect this conflict path only.
            after_path: Continue after next_path. Requires expected_head_revision.
            content_offset: Decoded byte offset for each side. Select one path and
                follow each side until next_offset is null.
            expected_head_revision: Exact Draft head from the preceding response.
                Required when continuing a page or byte offset.
        """
        _query = {
            "path": path,
            "after_path": after_path,
            "content_offset": content_offset,
            "expected_head_revision": expected_head_revision,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/draft/conflicts",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveDraftConflicts",
        )

    def resolve_draft_conflicts(
        self,
        target_id: TargetId,
        *,
        body: ResolveDraftConflicts,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftCodeUpdateResponseRead:
        """Resolve selected Draft conflicts

        Save deliberate decisions for the exact inspected Draft. Keep the repository or incoming
        side, or submit final file content, including binary bytes. Decisions save atomically.
        Use dry_run to preview them, then generate the Target separately to apply saved
        decisions and run its checks.

        POST /targets/{target_id}/draft/conflicts/resolve
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/draft/conflicts/resolve",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.resolveDraftConflicts",
        )

    def discard_draft_customizations(
        self,
        target_id: TargetId,
        *,
        body: DiscardDraftCustomizations,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftCodeUpdateResponseRead:
        """Discard selected Draft customizations

        Replace explicitly listed non-conflicting paths with generated files in one Draft
        commit. Listing a customer-only file deletes it. Use dry_run to inspect writes and
        deletions first. Resolve conflicts through the separate conflicts action. Generate
        afterward to refresh the Draft and its checks.

        POST /targets/{target_id}/draft/customizations/discard
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/draft/customizations/discard",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.discardDraftCustomizations",
        )

    def recover_draft_history(
        self,
        target_id: TargetId,
        *,
        body: RecoverDraftHistory,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftHistoryRecoveryResponseRead:
        """Review and recover rewritten repository history

        Preview a rewritten default branch and the Draft code to preserve. Approve the exact
        inspected revisions with dry_run false, then Generate separately. Recovery preserves the
        previous Draft branch, opens a new Draft from the current default branch, and requires
        explicit decisions for overlapping code. A rewritten Draft alone recovers automatically
        during Generate.

        POST /targets/{target_id}/draft/history/recover
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.request(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/draft/history/recover",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.recoverDraftHistory",
        )


class AsyncTargetsResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def list(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[TargetRead]:
        """List a project's Targets

        GET /projects/{project_id}/targets

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same account, operation, filters, and ordering that issued it. Omit
                to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_page(
        self,
        project_id: ProjectId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetListRead:
        """One page of "/projects/{project_id}/targets", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.list",
        )

    async def create(
        self,
        project_id: ProjectId,
        *,
        body: TargetFields,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Create an independently configured Target

        Creates a Target with its own configuration, Deliveries, and release history. Multiple
        Targets can use the same generator.

        POST /projects/{project_id}/targets

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/projects/{_quote(str(project_id), safe='')}/targets",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.create",
        )

    async def retrieve(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Retrieve a Target

        GET /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieve",
        )

    async def delete(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DeletedTargetRead:
        """Delete an unused Target

        Deletes a Target with no Generation history, release history, or active Draft. Disable a
        Target instead if it has any of these.

        DELETE /targets/{target_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "DELETE",
            f"/targets/{_quote(str(target_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.delete",
        )

    async def update(
        self,
        target_id: TargetId,
        *,
        body: TargetUpdateRequest,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetResponseRead:
        """Update a Target, its Deliveries, or its next reviewed version

        Omitted fields keep their current values. Supplied config, checks, and deliveries
        replace their complete stored values.
        Updates have no revision precondition. Concurrent updates preserve omitted fields, and
        the last saved update to a supplied field wins.
        Send proposed_version by itself; use the Draft endpoint for a version selection with an
        optional revision precondition.

        A `502` response means the selected version was saved, but regeneration failed.

        PATCH /targets/{target_id}
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "402": "PaymentRequiredError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return await self._core.arequest(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.update",
        )

    def list_releases(
        self,
        target_id: TargetId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> AsyncIterator[TargetReleaseRead]:
        """List immutable releases for a Target

        GET /targets/{target_id}/releases

        Args:
            limit: Maximum number of resources to return. Omit for 20; otherwise supply
                base-10 digits representing an integer from 1 to 100. Empty, malformed,
                or out-of-range values return 400 invalid_request. List query
                parameters must appear only once; unrecognized parameters also return
                400.
            cursor: Opaque cursor from the preceding page's next_cursor. Valid only for
                the same account, operation, filters, and ordering that issued it. Omit
                to start at the first page. Empty, malformed, or repeated cursors
                return 400 invalid_request. The page limit may change between requests.
        """
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return self._core.apaginate(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.listReleases",
            style="cursor",
            items_field="data",
            cursor_param="cursor",
            next_cursor_field="next_cursor",
            has_more_field="has_more",
            limit_param="limit",
        )

    async def list_releases_page(
        self,
        target_id: TargetId,
        *,
        limit: Optional[int] = None,
        cursor: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseListRead:
        """One page of "/targets/{target_id}/releases", exactly as the API returned it."""
        _query = {
            "limit": limit,
            "cursor": cursor,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/releases",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.listReleases",
        )

    async def retrieve_draft(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetDraftResponseRead:
        """Retrieve a Target's rolling Draft release

        Returns Current's version, the proposed Draft version, readiness, and commit. Pass
        `revision` as `expected_revision` when updating the Draft to avoid changing a newer
        candidate.

        GET /targets/{target_id}/draft
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/draft",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveDraft",
        )

    async def update_draft(
        self,
        target_id: TargetId,
        *,
        body: TargetDraftUpdate,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetDraftResponseRead:
        """Select an exact Draft version or return to automatic versioning

        Checks your version choice against the required version bump, then regenerates the
        existing Draft pull request.

        Send the last read revision as expected_revision to reject an intervening change with
        409 stale_release_revision before saving or regenerating.
        The precondition is optional; omitting it applies the selection to the current Draft.
        Version is required; null restores automatic selection.

        A `502` response means the selected version was saved, but regeneration failed.

        PATCH /targets/{target_id}/draft
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return await self._core.arequest(
            "PATCH",
            f"/targets/{_quote(str(target_id), safe='')}/draft",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.updateDraft",
        )

    async def adopt_release(
        self,
        target_id: TargetId,
        *,
        body: TargetAdoption,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseResponseRead:
        """Adopt a verified existing package as Current

        Checks the repository tag, package metadata, and registry artifact, then records the
        package as an Imported Current release. Opens the first Typeship Draft at the next major
        version; review it to establish the baseline for preserving existing code.

        POST /targets/{target_id}/adopt

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "422": "UnprocessableEntityError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/adopt",
            headers=_headers,
            body=body,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.adoptRelease",
        )

    async def retrieve_release(
        self,
        target_release_id: TargetReleaseId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseResponseRead:
        """Retrieve an immutable Target release

        GET /target_releases/{target_release_id}
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/target_releases/{_quote(str(target_release_id), safe='')}",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveRelease",
        )

    async def republish_release(
        self,
        target_release_id: TargetReleaseId,
        *,
        idempotency_key: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> TargetReleaseResponseRead:
        """Retry publication of an exact Target release

        Retries publication of the specified release through its repository workflow. Uses that
        release's version and accepted commit, even if a newer Draft or release exists.

        A `502` response means the repository publication workflow could not be dispatched.

        POST /target_releases/{target_release_id}/republish

        Args:
            idempotency_key: Identifies one logical write for 24 hours. The key is
                scoped to the authenticated account and operation; account-less
                generation uses a hashed network identity. Retrying the same method,
                path, query, and JSON body replays the original response. Reusing the
                key with changed intent returns 409. After expiry the key starts a new
                write.
        """
        _headers = {
            "Idempotency-Key": idempotency_key,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
            "502": "BadGatewayError",
        }
        return await self._core.arequest(
            "POST",
            f"/target_releases/{_quote(str(target_release_id), safe='')}/republish",
            headers=_headers,
            errors=_errors,
            idempotency_key_header="Idempotency-Key",
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.republishRelease",
        )

    async def retrieve_draft_customizations(
        self,
        target_id: TargetId,
        *,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftCustomizationsResponseRead:
        """Inspect customizations on a Draft

        Returns the changed file paths from the latest Draft inspection. Read conflicts for all
        three file versions, and read the Draft for package-check readiness.

        GET /targets/{target_id}/draft/customizations
        """
        _errors = {
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/draft/customizations",
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveDraftCustomizations",
        )

    async def retrieve_draft_conflicts(
        self,
        target_id: TargetId,
        *,
        path: Optional[str] = None,
        after_path: Optional[str] = None,
        content_offset: Optional[int] = None,
        expected_head_revision: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftConflictsResponseRead:
        """Inspect conflicts on a Draft

        Returns every conflict with its base, repository, and incoming file bytes and modes in
        one response. An absent file is null. incoming_source distinguishes generated changes,
        default-branch changes, and recovered saved Draft code. Saved decisions require a
        separate Generate before conflicts clear.

        GET /targets/{target_id}/draft/conflicts

        Args:
            path: Inspect this conflict path only.
            after_path: Continue after next_path. Requires expected_head_revision.
            content_offset: Decoded byte offset for each side. Select one path and
                follow each side until next_offset is null.
            expected_head_revision: Exact Draft head from the preceding response.
                Required when continuing a page or byte offset.
        """
        _query = {
            "path": path,
            "after_path": after_path,
            "content_offset": content_offset,
            "expected_head_revision": expected_head_revision,
        }
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "GET",
            f"/targets/{_quote(str(target_id), safe='')}/draft/conflicts",
            query=_query,
            errors=_errors,
            idempotent=True,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.retrieveDraftConflicts",
        )

    async def resolve_draft_conflicts(
        self,
        target_id: TargetId,
        *,
        body: ResolveDraftConflicts,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftCodeUpdateResponseRead:
        """Resolve selected Draft conflicts

        Save deliberate decisions for the exact inspected Draft. Keep the repository or incoming
        side, or submit final file content, including binary bytes. Decisions save atomically.
        Use dry_run to preview them, then generate the Target separately to apply saved
        decisions and run its checks.

        POST /targets/{target_id}/draft/conflicts/resolve
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/draft/conflicts/resolve",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.resolveDraftConflicts",
        )

    async def discard_draft_customizations(
        self,
        target_id: TargetId,
        *,
        body: DiscardDraftCustomizations,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftCodeUpdateResponseRead:
        """Discard selected Draft customizations

        Replace explicitly listed non-conflicting paths with generated files in one Draft
        commit. Listing a customer-only file deletes it. Use dry_run to inspect writes and
        deletions first. Resolve conflicts through the separate conflicts action. Generate
        afterward to refresh the Draft and its checks.

        POST /targets/{target_id}/draft/customizations/discard
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/draft/customizations/discard",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.discardDraftCustomizations",
        )

    async def recover_draft_history(
        self,
        target_id: TargetId,
        *,
        body: RecoverDraftHistory,
        request_options: Optional[RequestOptions] = None,
    ) -> DraftHistoryRecoveryResponseRead:
        """Review and recover rewritten repository history

        Preview a rewritten default branch and the Draft code to preserve. Approve the exact
        inspected revisions with dry_run false, then Generate separately. Recovery preserves the
        previous Draft branch, opens a new Draft from the current default branch, and requires
        explicit decisions for overlapping code. A rewritten Draft alone recovers automatically
        during Generate.

        POST /targets/{target_id}/draft/history/recover
        """
        _errors = {
            "400": "BadRequestError",
            "401": "UnauthorizedError",
            "403": "ForbiddenError",
            "404": "NotFoundError",
            "409": "ConflictError",
            "429": "RateLimitedError",
            "500": "InternalServerError",
        }
        return await self._core.arequest(
            "POST",
            f"/targets/{_quote(str(target_id), safe='')}/draft/history/recover",
            body=body,
            errors=_errors,
            security=[{"apiKey":[]}],
            request_options=request_options,
            schema_key="targets.recoverDraftHistory",
        )
