"""typeship — usage.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, Union

from .._core import HttpCore, RequestOptions
from ..models import *  # noqa: F401,F403 — generated payload types


class UsageResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    def retrieve(self, *, request_options: Optional[RequestOptions] = None) -> Usage:
        """Retrieve usage for this account

        What this account has consumed and what remains. A hosted generation can cost more than one unit: a project generating TypeScript, Python, and Go consumes three, so callers that would otherwise discover the limit by receiving a 402 can check first.

        GET /usage
        """
        return self._core.request("GET", "/usage", errors={"401": "UnauthorizedError"}, idempotent=True, request_options=request_options, schema_key="usage.retrieve")


class AsyncUsageResource:
    def __init__(self, core: HttpCore) -> None:
        self._core = core

    async def retrieve(self, *, request_options: Optional[RequestOptions] = None) -> Usage:
        """Retrieve usage for this account

        What this account has consumed and what remains. A hosted generation can cost more than one unit: a project generating TypeScript, Python, and Go consumes three, so callers that would otherwise discover the limit by receiving a 402 can check first.

        GET /usage
        """
        return await self._core.arequest("GET", "/usage", errors={"401": "UnauthorizedError"}, idempotent=True, request_options=request_options, schema_key="usage.retrieve")

