"""typeship — client.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

import functools
import os
from typing import Any, Callable, Dict, Literal, Mapping, Optional, Tuple, Union

from ._core import (
    DEFAULT_MAX_RETRIES,
    DEFAULT_MAX_RETRY_WAIT,
    DEFAULT_TIMEOUT,
    AuthValue,
    HttpCore,
    RequestOptions,
    Transport,
    _prefixed,
)
from .resources.projects import ProjectsResource, AsyncProjectsResource
from .resources.specs import SpecsResource, AsyncSpecsResource
from .resources.spec_revisions import SpecRevisionsResource, AsyncSpecRevisionsResource
from .resources.targets import TargetsResource, AsyncTargetsResource
from .resources.deliveries import DeliveriesResource, AsyncDeliveriesResource
from .resources.generations import GenerationsResource, AsyncGenerationsResource
from .resources.drafts import DraftsResource, AsyncDraftsResource
from .resources.releases import ReleasesResource, AsyncReleasesResource
from .resources.files import FilesResource, AsyncFilesResource
from .resources.packages import PackagesResource, AsyncPackagesResource
from .resources.organization import OrganizationResource, AsyncOrganizationResource
from .resources.api_keys import ApiKeysResource, AsyncApiKeysResource

VERSION = "0.25.0"
USER_AGENT = "typeship/0.25.0"


def _bearer(value: AuthValue) -> AuthValue:
    return _prefixed("Bearer ", value)


def _first_env(environ: Mapping[str, str], *names: str) -> Optional[str]:
    """The first variable set: a documented name, then its older generic name."""
    for name in names:
        if name in environ:
            return environ[name]
    return None


def _credentials(
    *,
    credentials: Optional[Mapping[str, Union[AuthValue, Tuple[str, str]]]] = None,
    bearer_token: Optional[AuthValue] = None,
    timeout: float,
    use_env: bool,
) -> Dict[str, Any]:
    """Every credential the client sends, keyed by security scheme."""
    environ: Mapping[str, str] = os.environ if use_env else {}
    auth_headers: Dict[str, Any] = {}
    auth_query: Dict[str, Any] = {}
    bearer_credential: Any = None
    oauth_credential: Any = None
    basic_credential: Any = None
    bearer = bearer_token if bearer_token is not None else _first_env(environ, "TYPESHIP_API_KEY", "TYPESHIP_TOKEN")
    if bearer is not None:
        bearer_credential = _bearer(bearer)
    allowed_credentials = {
        "apiKey",
    }
    unknown_credentials = set(credentials or {}) - set(allowed_credentials)
    if unknown_credentials:
        raise ValueError("Unknown security scheme: " + ", ".join(sorted(unknown_credentials)))
    credential_values: Dict[str, Any] = {}
    named = (credentials or {}).get("apiKey")
    if named is not None and not isinstance(named, str) and not callable(named):
        raise ValueError("Credential apiKey requires a string or token callback.")
    selected_value = (
        _bearer(named) if named is not None
        else (bearer_credential if bearer_credential is not None else oauth_credential)
    )
    if selected_value is not None:
        credential_values["apiKey"] = {"headers": {"Authorization": selected_value}}
    return credential_values


def _configure(
    *,
    base_url: Optional[str] = None,
    credentials: Optional[Mapping[str, Union[AuthValue, Tuple[str, str]]]] = None,
    bearer_token: Optional[AuthValue] = None,
    timeout: float = DEFAULT_TIMEOUT,
    max_retries: int = DEFAULT_MAX_RETRIES,
    max_retry_wait: float = DEFAULT_MAX_RETRY_WAIT,
    debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
    default_headers: Optional[Dict[str, str]] = None,
    transport: Optional[Transport] = None,
    on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
    on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
    on_error: Optional[Callable[[BaseException, str, str], None]] = None,
    validate: Union[bool, Literal["warn"], None] = None,
) -> Tuple[HttpCore, Callable[..., Dict[str, Any]]]:
    headers: Dict[str, Any] = dict(default_headers or {})
    query: Dict[str, Any] = {}
    credential_values = _credentials(
        credentials=credentials,
        bearer_token=bearer_token,
        timeout=timeout,
        use_env=True,
    )
    resolved_base = base_url or os.environ.get("TYPESHIP_BASE_URL") or "https://typeship.dev/api/v1"
    if not resolved_base:
        raise ValueError("No base URL: pass base_url or set TYPESHIP_BASE_URL.")
    if debug is None:
        debug = os.environ.get("TYPESHIP_DEBUG") == "1"
    core = HttpCore(
        base_url=resolved_base,
        headers=headers,
        query=query,
        credentials=credential_values,
        timeout=timeout,
        max_retries=max_retries,
        max_retry_wait=max_retry_wait,
        user_agent=USER_AGENT,
        debug=debug,
        transport=transport,
        on_request=on_request,
        on_response=on_response,
        on_error=on_error,
        validate=validate,
    )
    return core, functools.partial(_credentials, timeout=timeout, use_env=False)


class TypeshipClient:
    """typeship — v0.25.0.

    Methods raise on failure: a documented error response raises its typed
    exception, malformed successful JSON raises ResponseParseError, and a
    network failure raises TransportError.
    """

    def __init__(
        self,
        *,
        base_url: Optional[str] = None,
        credentials: Optional[Mapping[str, Union[str, Callable[[], str], Tuple[str, str]]]] = None,
        bearer_token: Optional[Union[str, Callable[[], str]]] = None,
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        max_retry_wait: float = DEFAULT_MAX_RETRY_WAIT,
        debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
        default_headers: Optional[Dict[str, str]] = None,
        transport: Optional[Transport] = None,
        on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
        on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
        on_error: Optional[Callable[[BaseException, str, str], None]] = None,
        validate: Union[bool, Literal["warn"], None] = None,
    ) -> None:
        core, credentials_for = _configure(
            base_url=base_url,
            credentials=credentials,
            bearer_token=bearer_token,
            timeout=timeout,
            max_retries=max_retries,
            max_retry_wait=max_retry_wait,
            debug=debug,
            default_headers=default_headers,
            transport=transport,
            on_request=on_request,
            on_response=on_response,
            on_error=on_error,
            validate=validate,
        )
        self._attach(core, credentials_for)

    def _attach(self, core: HttpCore, credentials_for: Callable[..., Dict[str, Any]]) -> None:
        self._core = core
        self._credentials_for = credentials_for
        self.projects = ProjectsResource(core)
        self.specs = SpecsResource(core)
        self.spec_revisions = SpecRevisionsResource(core)
        self.targets = TargetsResource(core)
        self.deliveries = DeliveriesResource(core)
        self.generations = GenerationsResource(core)
        self.drafts = DraftsResource(core)
        self.releases = ReleasesResource(core)
        self.files = FilesResource(core)
        self.packages = PackagesResource(core)
        self.organization = OrganizationResource(core)
        self.api_keys = ApiKeysResource(core)

    def with_credentials(
        self,
        *,
        credentials: Optional[Mapping[str, Union[str, Callable[[], str], Tuple[str, str]]]] = None,
        bearer_token: Optional[Union[str, Callable[[], str]]] = None,
    ) -> "TypeshipClient":
        """A client that sends these credentials instead of this client's.

        Takes the constructor's credential arguments and replaces every
        credential: nothing is inherited from this client and no environment
        variable is read. The base URL, transport and pooled connections,
        timeouts, retries, hooks, and default headers are shared. This client
        owns the connections, so closing the new one leaves them open.
        """
        clone = type(self).__new__(type(self))
        values = self._credentials_for(credentials=credentials, bearer_token=bearer_token)
        clone._attach(self._core.with_credentials(values), self._credentials_for)
        return clone

    def close(self) -> None:
        """Release pooled connections."""
        self._core.close()

    def __enter__(self) -> "TypeshipClient":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class AsyncTypeshipClient:
    """typeship — v0.25.0, awaitable.

    The same surface as the synchronous client: await each call, and
    async-iterate pages and streams. Requests run on the event loop's
    default executor, so nothing blocks the loop. Token and credential
    callbacks may be defined with async def; they are awaited on this loop.
    """

    def __init__(
        self,
        *,
        base_url: Optional[str] = None,
        credentials: Optional[Mapping[str, Union[AuthValue, Tuple[str, str]]]] = None,
        bearer_token: Optional[AuthValue] = None,
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        max_retry_wait: float = DEFAULT_MAX_RETRY_WAIT,
        debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
        default_headers: Optional[Dict[str, str]] = None,
        transport: Optional[Transport] = None,
        on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
        on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
        on_error: Optional[Callable[[BaseException, str, str], None]] = None,
        validate: Union[bool, Literal["warn"], None] = None,
    ) -> None:
        core, credentials_for = _configure(
            base_url=base_url,
            credentials=credentials,
            bearer_token=bearer_token,
            timeout=timeout,
            max_retries=max_retries,
            max_retry_wait=max_retry_wait,
            debug=debug,
            default_headers=default_headers,
            transport=transport,
            on_request=on_request,
            on_response=on_response,
            on_error=on_error,
            validate=validate,
        )
        self._attach(core, credentials_for)

    def _attach(self, core: HttpCore, credentials_for: Callable[..., Dict[str, Any]]) -> None:
        self._core = core
        self._credentials_for = credentials_for
        self.projects = AsyncProjectsResource(core)
        self.specs = AsyncSpecsResource(core)
        self.spec_revisions = AsyncSpecRevisionsResource(core)
        self.targets = AsyncTargetsResource(core)
        self.deliveries = AsyncDeliveriesResource(core)
        self.generations = AsyncGenerationsResource(core)
        self.drafts = AsyncDraftsResource(core)
        self.releases = AsyncReleasesResource(core)
        self.files = AsyncFilesResource(core)
        self.packages = AsyncPackagesResource(core)
        self.organization = AsyncOrganizationResource(core)
        self.api_keys = AsyncApiKeysResource(core)

    def with_credentials(
        self,
        *,
        credentials: Optional[Mapping[str, Union[AuthValue, Tuple[str, str]]]] = None,
        bearer_token: Optional[AuthValue] = None,
    ) -> "AsyncTypeshipClient":
        """A client that sends these credentials instead of this client's.

        Takes the constructor's credential arguments and replaces every
        credential: nothing is inherited from this client and no environment
        variable is read. The base URL, transport and pooled connections,
        timeouts, retries, hooks, and default headers are shared. This client
        owns the connections, so closing the new one leaves them open.
        """
        clone = type(self).__new__(type(self))
        values = self._credentials_for(credentials=credentials, bearer_token=bearer_token)
        clone._attach(self._core.with_credentials(values), self._credentials_for)
        return clone

    async def aclose(self) -> None:
        """Release pooled connections."""
        self._core.close()

    async def __aenter__(self) -> "AsyncTypeshipClient":
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.aclose()
