"""typeship — client.

Generated by typeship — https://typeship.dev
"""
from __future__ import annotations

import os
from typing import Any, Callable, Dict, Literal, Mapping, Optional, Tuple, Union

from ._core import DEFAULT_MAX_RETRIES, DEFAULT_TIMEOUT, HttpCore, RequestOptions, Transport
from .resources.projects import ProjectsResource, AsyncProjectsResource
from .resources.specs import SpecsResource, AsyncSpecsResource
from .resources.spec_revisions import SpecRevisionsResource, AsyncSpecRevisionsResource
from .resources.targets import TargetsResource, AsyncTargetsResource
from .resources.deliveries import DeliveriesResource, AsyncDeliveriesResource
from .resources.generations import GenerationsResource, AsyncGenerationsResource
from .resources.drafts import DraftsResource, AsyncDraftsResource
from .resources.releases import ReleasesResource, AsyncReleasesResource
from .resources.files import FilesResource, AsyncFilesResource
from .resources.generate import GenerateResource, AsyncGenerateResource
from .resources.organization import OrganizationResource, AsyncOrganizationResource
from .resources.api_keys import ApiKeysResource, AsyncApiKeysResource

VERSION = "0.25.0"
USER_AGENT = "typeship/0.25.0"


def _bearer(value: Union[str, Callable[[], str]]) -> Union[str, Callable[[], str]]:
    return (lambda: "Bearer " + value()) if callable(value) else "Bearer " + value


def _configure(
    *,
    base_url: Optional[str] = None,
    credentials: Optional[Mapping[str, Union[str, Callable[[], str], Tuple[str, str]]]] = None,
    bearer_token: Optional[Union[str, Callable[[], str]]] = None,
    timeout: float = DEFAULT_TIMEOUT,
    max_retries: int = DEFAULT_MAX_RETRIES,
    debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
    default_headers: Optional[Dict[str, str]] = None,
    transport: Optional[Transport] = None,
    on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
    on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
    on_error: Optional[Callable[[BaseException, str, str], None]] = None,
    validate: Union[bool, Literal["warn"], None] = None,
) -> HttpCore:
    headers: Dict[str, Any] = dict(default_headers or {})
    query: Dict[str, Any] = {}
    auth_headers: Dict[str, Any] = {}
    auth_query: Dict[str, Any] = {}
    bearer_credential: Any = None
    oauth_credential: Any = None
    basic_credential: Any = None
    bearer = bearer_token if bearer_token is not None else os.environ.get("TYPESHIP_TOKEN")
    if bearer is not None:
        bearer_credential = _bearer(bearer)
    allowed_credentials = {
        "apiKey",
    }
    unknown_credentials = set(credentials or {}) - set(allowed_credentials)
    if unknown_credentials:
        raise ValueError("Unknown security scheme: " + ", ".join(sorted(unknown_credentials)))
    credential_values: Dict[str, Any] = {}
    named = (credentials or {}).get("apiKey")
    if named is not None and not isinstance(named, str) and not callable(named):
        raise ValueError("Credential apiKey requires a string or token callback.")
    selected_value = (
        _bearer(named) if named is not None
        else (bearer_credential if bearer_credential is not None else oauth_credential)
    )
    if selected_value is not None:
        credential_values["apiKey"] = {"headers": {"Authorization": selected_value}}
    resolved_base = base_url or os.environ.get("TYPESHIP_BASE_URL") or "https://typeship.dev/api/v1"
    if not resolved_base:
        raise ValueError("No base URL: pass base_url or set TYPESHIP_BASE_URL.")
    if debug is None:
        debug = os.environ.get("TYPESHIP_DEBUG") == "1"
    return HttpCore(
        base_url=resolved_base,
        headers=headers,
        query=query,
        credentials=credential_values,
        timeout=timeout,
        max_retries=max_retries,
        user_agent=USER_AGENT,
        debug=debug,
        transport=transport,
        on_request=on_request,
        on_response=on_response,
        on_error=on_error,
        validate=validate,
    )


class TypeshipClient:
    """typeship — v0.25.0.

    Methods raise on failure: a documented error response raises its typed
    exception, malformed successful JSON raises ResponseParseError, and a
    network failure raises TransportError.
    """

    def __init__(
        self,
        *,
        base_url: Optional[str] = None,
        credentials: Optional[Mapping[str, Union[str, Callable[[], str], Tuple[str, str]]]] = None,
        bearer_token: Optional[Union[str, Callable[[], str]]] = None,
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
        default_headers: Optional[Dict[str, str]] = None,
        transport: Optional[Transport] = None,
        on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
        on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
        on_error: Optional[Callable[[BaseException, str, str], None]] = None,
        validate: Union[bool, Literal["warn"], None] = None,
    ) -> None:
        self._core = _configure(
            base_url=base_url,
            credentials=credentials,
            bearer_token=bearer_token,
            timeout=timeout,
            max_retries=max_retries,
            debug=debug,
            default_headers=default_headers,
            transport=transport,
            on_request=on_request,
            on_response=on_response,
            on_error=on_error,
            validate=validate,
        )
        self.projects = ProjectsResource(self._core)
        self.specs = SpecsResource(self._core)
        self.spec_revisions = SpecRevisionsResource(self._core)
        self.targets = TargetsResource(self._core)
        self.deliveries = DeliveriesResource(self._core)
        self.generations = GenerationsResource(self._core)
        self.drafts = DraftsResource(self._core)
        self.releases = ReleasesResource(self._core)
        self.files = FilesResource(self._core)
        self.generate = GenerateResource(self._core)
        self.organization = OrganizationResource(self._core)
        self.api_keys = ApiKeysResource(self._core)

    def close(self) -> None:
        """Release pooled connections."""
        self._core.close()

    def __enter__(self) -> "TypeshipClient":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class AsyncTypeshipClient:
    """typeship — v0.25.0, awaitable.

    The same surface as the synchronous client: await each call, and
    async-iterate pages and streams. Requests run on the event loop's
    default executor, so nothing blocks the loop.
    """

    def __init__(
        self,
        *,
        base_url: Optional[str] = None,
        credentials: Optional[Mapping[str, Union[str, Callable[[], str], Tuple[str, str]]]] = None,
        bearer_token: Optional[Union[str, Callable[[], str]]] = None,
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
        default_headers: Optional[Dict[str, str]] = None,
        transport: Optional[Transport] = None,
        on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
        on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
        on_error: Optional[Callable[[BaseException, str, str], None]] = None,
        validate: Union[bool, Literal["warn"], None] = None,
    ) -> None:
        self._core = _configure(
            base_url=base_url,
            credentials=credentials,
            bearer_token=bearer_token,
            timeout=timeout,
            max_retries=max_retries,
            debug=debug,
            default_headers=default_headers,
            transport=transport,
            on_request=on_request,
            on_response=on_response,
            on_error=on_error,
            validate=validate,
        )
        self.projects = AsyncProjectsResource(self._core)
        self.specs = AsyncSpecsResource(self._core)
        self.spec_revisions = AsyncSpecRevisionsResource(self._core)
        self.targets = AsyncTargetsResource(self._core)
        self.deliveries = AsyncDeliveriesResource(self._core)
        self.generations = AsyncGenerationsResource(self._core)
        self.drafts = AsyncDraftsResource(self._core)
        self.releases = AsyncReleasesResource(self._core)
        self.files = AsyncFilesResource(self._core)
        self.generate = AsyncGenerateResource(self._core)
        self.organization = AsyncOrganizationResource(self._core)
        self.api_keys = AsyncApiKeysResource(self._core)

    async def aclose(self) -> None:
        """Release pooled connections."""
        self._core.close()

    async def __aenter__(self) -> "AsyncTypeshipClient":
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.aclose()
