"""typeship — client.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

import os
from typing import Any, Callable, Dict, Literal, Mapping, Optional, Union

from ._core import DEFAULT_MAX_RETRIES, DEFAULT_TIMEOUT, HttpCore, RequestOptions, Transport
from .resources.generate import GenerateResource, AsyncGenerateResource
from .resources.projects import ProjectsResource, AsyncProjectsResource
from .resources.definitions import DefinitionsResource, AsyncDefinitionsResource
from .resources.targets import TargetsResource, AsyncTargetsResource
from .resources.generations import GenerationsResource, AsyncGenerationsResource
from .resources.definition_revisions import (
    DefinitionRevisionsResource,
    AsyncDefinitionRevisionsResource,
)

VERSION = "1.0.0"
USER_AGENT = "typeship/1.0.0 (typeship)"


def _configure(
    *,
    base_url: Optional[str] = None,
    bearer_token: Optional[Union[str, Callable[[], str]]] = None,
    timeout: float = DEFAULT_TIMEOUT,
    max_retries: int = DEFAULT_MAX_RETRIES,
    debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
    default_headers: Optional[Dict[str, str]] = None,
    transport: Optional[Transport] = None,
    on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
    on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
    on_error: Optional[Callable[[BaseException, str, str], None]] = None,
    validate: Union[bool, Literal["warn"], None] = None,
) -> HttpCore:
    headers: Dict[str, Any] = dict(default_headers or {})
    query: Dict[str, Any] = {}
    bearer = bearer_token if bearer_token is not None else os.environ.get("TYPESHIP_TOKEN")
    if bearer is not None:
        headers["Authorization"] = (lambda: "Bearer " + bearer()) if callable(bearer) else "Bearer " + bearer
    resolved_base = base_url or os.environ.get("TYPESHIP_BASE_URL") or "https://typeship.dev/api/v1"
    if not resolved_base:
        raise ValueError("No base URL: pass base_url or set TYPESHIP_BASE_URL.")
    if debug is None:
        debug = os.environ.get("TYPESHIP_DEBUG") == "1"
    return HttpCore(
        base_url=resolved_base,
        headers=headers,
        query=query,
        timeout=timeout,
        max_retries=max_retries,
        user_agent=USER_AGENT,
        debug=debug,
        transport=transport,
        on_request=on_request,
        on_response=on_response,
        on_error=on_error,
        validate=validate,
    )


class TypeshipClient:
    """typeship — v1.0.0.

    Methods raise on failure: a documented error response raises its typed
    exception, and a network failure raises TransportError.
    """

    def __init__(
        self,
        *,
        base_url: Optional[str] = None,
        bearer_token: Optional[Union[str, Callable[[], str]]] = None,
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
        default_headers: Optional[Dict[str, str]] = None,
        transport: Optional[Transport] = None,
        on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
        on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
        on_error: Optional[Callable[[BaseException, str, str], None]] = None,
        validate: Union[bool, Literal["warn"], None] = None,
    ) -> None:
        self._core = _configure(
            base_url=base_url,
            bearer_token=bearer_token,
            timeout=timeout,
            max_retries=max_retries,
            debug=debug,
            default_headers=default_headers,
            transport=transport,
            on_request=on_request,
            on_response=on_response,
            on_error=on_error,
            validate=validate,
        )
        self.generate = GenerateResource(self._core)
        self.projects = ProjectsResource(self._core)
        self.definitions = DefinitionsResource(self._core)
        self.targets = TargetsResource(self._core)
        self.generations = GenerationsResource(self._core)
        self.definition_revisions = DefinitionRevisionsResource(self._core)

    def close(self) -> None:
        """Release pooled connections."""
        self._core.close()

    def __enter__(self) -> "TypeshipClient":
        return self

    def __exit__(self, *exc: Any) -> None:
        self.close()


class AsyncTypeshipClient:
    """typeship — v1.0.0, awaitable.

    The same surface as the synchronous client: await each call, and
    async-iterate pages and streams. Requests run on the event loop's
    default executor, so nothing blocks the loop.
    """

    def __init__(
        self,
        *,
        base_url: Optional[str] = None,
        bearer_token: Optional[Union[str, Callable[[], str]]] = None,
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
        default_headers: Optional[Dict[str, str]] = None,
        transport: Optional[Transport] = None,
        on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
        on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
        on_error: Optional[Callable[[BaseException, str, str], None]] = None,
        validate: Union[bool, Literal["warn"], None] = None,
    ) -> None:
        self._core = _configure(
            base_url=base_url,
            bearer_token=bearer_token,
            timeout=timeout,
            max_retries=max_retries,
            debug=debug,
            default_headers=default_headers,
            transport=transport,
            on_request=on_request,
            on_response=on_response,
            on_error=on_error,
            validate=validate,
        )
        self.generate = AsyncGenerateResource(self._core)
        self.projects = AsyncProjectsResource(self._core)
        self.definitions = AsyncDefinitionsResource(self._core)
        self.targets = AsyncTargetsResource(self._core)
        self.generations = AsyncGenerationsResource(self._core)
        self.definition_revisions = AsyncDefinitionRevisionsResource(self._core)

    async def aclose(self) -> None:
        """Release pooled connections."""
        self._core.close()

    async def __aenter__(self) -> "AsyncTypeshipClient":
        return self

    async def __aexit__(self, *exc: Any) -> None:
        await self.aclose()
