"""HTTP transport. Generated by typeship — https://typeship.dev

Zero dependencies: built on http.client and urllib from the standard library,
with keep-alive connections pooled per client.
"""
from __future__ import annotations

import asyncio
import functools
import http.client
import inspect
import json as _json
import random
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
from typing import Any, AsyncIterator, Awaitable, Callable, Dict, Iterator, List, Literal, Mapping, Optional, Sequence, Tuple, TypedDict, Union

from ._errors import ApiError, PayloadError, RateLimitError, ResponseParseError, TransportError
from ._errors import SdkError, UnexpectedApiError, error_for_status, rate_limit_info
from ._schemas import DEFS, SCHEMAS
from ._validate import ValidationError, Violation, validate_against_schema

#: A credential: a string, or a callback resolved before every attempt. The
#: async client also accepts callbacks defined with async def.
AuthValue = Union[str, Callable[[], Union[str, Awaitable[str]]]]




class ResponseMeta:
    """HTTP-level result of a call: status, headers, and what they say.

    A 304 Not Modified answers a conditional request (If-None-Match): the
    call returns None and not_modified is True here.
    """

    def __init__(self, status: int, headers: Mapping[str, str], request_id: Optional[str]) -> None:
        self.status = status
        #: Lower-cased response headers.
        self.headers = headers
        self.request_id = request_id
        #: The ETag header, for a later If-None-Match.
        self.etag: Optional[str] = headers.get("etag")
        #: The Last-Modified header, for a later If-Modified-Since.
        self.last_modified: Optional[str] = headers.get("last-modified")
        self.not_modified = status == 304

    def __repr__(self) -> str:
        return "ResponseMeta(status=%d, etag=%r)" % (self.status, self.etag)


class RequestOptions(TypedDict, total=False):
    """Per-call overrides, passed as request_options= to any method."""

    timeout: float
    max_retries: int
    headers: Mapping[str, str]
    #: Receives this call's ResponseMeta once a response arrives, whether the
    #: call succeeded or failed.
    on_response: Callable[[ResponseMeta], None]




#: (method, url, headers, body, timeout) -> (status, headers, body).
#: Swap in your own to route through a proxy, add tracing, or test offline.
Transport = Callable[
    [str, str, Mapping[str, str], Optional[bytes], float],
    Tuple[int, Mapping[str, str], bytes],
]

RETRYABLE_STATUSES = frozenset({408, 429, 500, 502, 503, 504})
DEFAULT_TIMEOUT = 30.0
DEFAULT_MAX_RETRIES = 2
#: The longest server-requested wait (Retry-After, x-ratelimit-reset), in
#: seconds, that a retry honors; a longer one raises at once with the reset time.
DEFAULT_MAX_RETRY_WAIT = 60.0
_INITIAL_BACKOFF = 0.3
_MAX_BACKOFF = 10.0


# The event loop an async client call is waiting on, for the worker thread
# running that call: an async credential callback is awaited there.
_callback_loop = threading.local()


def _on_loop(loop: asyncio.AbstractEventLoop, fn: Callable[..., Any], *args: Any, **kwargs: Any) -> Any:
    """Run fn in this worker thread with async callbacks awaited on loop."""
    previous = getattr(_callback_loop, "loop", None)
    _callback_loop.loop = loop
    try:
        return fn(*args, **kwargs)
    finally:
        _callback_loop.loop = previous


def _resolve(value: Optional[AuthValue]) -> Optional[str]:
    """Credentials may be callables so expiring tokens work; resolve per attempt.

    An exception from a callback propagates unchanged and is never retried.
    """
    if value is None or isinstance(value, str):
        return value
    # After a 401, a callback that takes a "rejected" argument is told once
    # that the API refused the value it last returned.
    rejected = _take_rejected(value)
    callback: Any = value
    result = callback(rejected=True) if rejected and _accepts_rejected(value) else value()
    if isinstance(result, str):
        return result
    loop = getattr(_callback_loop, "loop", None)
    if loop is None:
        close = getattr(result, "close", None)
        if callable(close):
            close()  # never awaited; closing it silences the warning
        raise TypeError("An async credential callback requires the async client.")

    async def wait() -> str:
        return await result

    return asyncio.run_coroutine_threadsafe(wait(), loop).result()


_rejected_ids: Dict[int, Any] = {}
_rejected_lock = threading.Lock()


def _mark_rejected(value: Any) -> None:
    invalidate = getattr(value, "invalidate", None)
    if callable(invalidate):
        invalidate()
        return
    with _rejected_lock:
        _rejected_ids[id(value)] = value


def _take_rejected(value: Any) -> bool:
    with _rejected_lock:
        return _rejected_ids.pop(id(value), None) is value


def _accepts_rejected(value: Any) -> bool:
    try:
        parameters = inspect.signature(value).parameters.values()
    except (TypeError, ValueError):
        return False
    return any(p.name == "rejected" or p.kind == inspect.Parameter.VAR_KEYWORD for p in parameters)


class _Callback:
    """A callback credential with a fixed prefix, such as "Bearer "."""

    def __init__(self, prefix: str, source: Callable[[], Union[str, Awaitable[str]]]) -> None:
        self._prefix = prefix
        self._source = source

    def __call__(self) -> str:
        return self._prefix + (_resolve(self._source) or "")

    def invalidate(self) -> None:
        _mark_rejected(self._source)


def _prefixed(prefix: str, value: AuthValue) -> AuthValue:
    """Prefix a credential, resolving a callback only when a request is sent."""
    return _Callback(prefix, value) if callable(value) else prefix + value


def _reauthenticate(selected: Mapping[str, Mapping[str, AuthValue]]) -> bool:
    """After a 401, drop cached tokens behind the request's credentials.

    True when any of them is a callback or a client-credentials grant, so a
    resend can carry a fresh value. Static credentials are never resent.
    """
    dynamic = [value for location in selected.values() for value in location.values() if callable(value)]
    for value in dynamic:
        _mark_rejected(value)
    return bool(dynamic)


def delimited(value: Any, separator: str) -> Any:
    """Join a query list into one delimited value (ids=1,2) for parameters
    whose spec says explode: false. Other values pass through unchanged."""
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        return value
    return separator.join(
        ("true" if item else "false") if isinstance(item, bool) else str(item) for item in value
    )


def _encode_deep(params: Mapping[str, Any], sort_keys: bool = False) -> List[Tuple[str, str]]:
    """Nested values as bracketed pairs: {"created": {"gte": 5}} -> created[gte]=5.

    Top-level lists repeat the key (expand=a&expand=b) rather than indexing,
    matching how most APIs read repeated query parameters. Form bodies order
    pairs by key, so the three SDKs send identical bytes.
    """
    out: List[Tuple[str, str]] = []

    def add(key: str, value: Any, top: bool) -> None:
        if value is None:
            return
        if isinstance(value, bool):
            out.append((key, "true" if value else "false"))
        elif isinstance(value, (str, int, float)):
            out.append((key, str(value)))
        elif isinstance(value, Mapping):
            for k, v in value.items():
                add(key + "[" + str(k) + "]", v, False)
        elif isinstance(value, Sequence):
            for i, v in enumerate(value):
                add(key if top else key + "[" + str(i) + "]", v, False)
        else:
            out.append((key, str(value)))

    for key, value in params.items():
        add(key, value, True)
    # A stable sort by key: Go's url.Values order, with repeated keys in place.
    return sorted(out, key=lambda pair: pair[0]) if sort_keys else out


_MISSING: Any = object()


def _get_path(body: Any, path: Optional[str], missing: Any = None) -> Any:
    """Dot-path lookup so pagination can read meta.next_cursor."""
    if not path or body is None:
        return missing
    current = body
    for part in path.split("."):
        if not isinstance(current, Mapping) or part not in current:
            return missing
        current = current[part]
    return current


def _link_next(header: Optional[str]) -> Optional[str]:
    """The rel="next" target of an RFC 8288 Link header, or None."""
    for part in (header or "").split(","):
        part = part.strip()
        if not part.startswith("<") or ">" not in part:
            continue
        target, _, params = part[1:].partition(">")
        for param in params.split(";"):
            name, _, value = param.strip().partition("=")
            if name.strip().lower() == "rel" and "next" in value.strip().strip('"').lower().split():
                return target
    return None


def _select_security(requirements: Sequence[Mapping[str, Sequence[str]]], credentials: Mapping[str, Mapping[str, Mapping[str, AuthValue]]]) -> Dict[str, Dict[str, AuthValue]]:
    """Select one complete alternative without resolving unused callbacks."""
    for requirement in requirements:
        if not requirement or any(name not in credentials for name in requirement):
            continue
        selected: Dict[str, Dict[str, AuthValue]] = {"headers": {}, "query": {}}
        destinations = set()
        conflict = False
        for name in requirement:
            for location in ("headers", "query"):
                for wire, value in credentials[name].get(location, {}).items():
                    destination = (location, wire.lower() if location == "headers" else wire)
                    if destination in destinations:
                        conflict = True
                    destinations.add(destination)
                    selected[location][wire] = value
        if not conflict:
            return selected
    return {"headers": {}, "query": {}}


class HttpCore:
    def __init__(
        self,
        base_url: str,
        headers: Optional[Mapping[str, Optional[AuthValue]]] = None,
        query: Optional[Mapping[str, Optional[AuthValue]]] = None,
        timeout: float = DEFAULT_TIMEOUT,
        max_retries: int = DEFAULT_MAX_RETRIES,
        user_agent: str = "typeship",
        credentials: Optional[Mapping[str, Mapping[str, Mapping[str, AuthValue]]]] = None,
        debug: Optional[Union[bool, Callable[[Dict[str, Any]], None]]] = None,
        globals_: Optional[Mapping[str, Any]] = None,
        retry: Optional[Mapping[str, Any]] = None,
        transport: Optional[Transport] = None,
        on_request: Optional[Callable[[str, str, Dict[str, str]], None]] = None,
        on_response: Optional[Callable[[int, Mapping[str, str], bytes], None]] = None,
        on_error: Optional[Callable[[BaseException, str, str], None]] = None,
        validate: Union[bool, Literal["warn"], None] = None,
        max_retry_wait: float = DEFAULT_MAX_RETRY_WAIT,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.max_retry_wait = max_retry_wait
        self._headers = dict(headers or {})
        self._query = dict(query or {})
        self._credentials = dict(credentials or {})
        self.timeout = timeout
        self.max_retries = max_retries
        self.user_agent = user_agent
        self._debug = debug
        self._globals = dict(globals_ or {})
        self._retry = dict(retry or {})
        # Keep-alive pool by default; a custom transport replaces it wholesale.
        self._pool: Optional[_ConnectionPool] = None
        if transport is None:
            self._pool = _ConnectionPool()
            self._transport: Transport = self._pool
        else:
            self._transport = transport
        self._on_request = on_request
        self._on_response = on_response
        self._on_error = on_error
        # None/False off, True raises, "warn" logs and lets the call proceed.
        self._validate = validate

    def close(self) -> None:
        """Release pooled connections. Safe to call more than once."""
        if self._pool is not None:
            self._pool.close()

    def with_credentials(self, credentials: Mapping[str, Mapping[str, Mapping[str, AuthValue]]]) -> "HttpCore":
        """This core with its credentials replaced. The transport and its
        connections stay shared and owned by this core, so closing the copy
        leaves them open."""
        clone = HttpCore.__new__(HttpCore)
        clone.__dict__.update(self.__dict__)
        clone._credentials = dict(credentials)
        clone._pool = None
        return clone

    def global_value(self, name: str) -> Any:
        """Client-level value for a global parameter; per-call values win."""
        return self._globals.get(name)

    def _emit_debug(self, event: Dict[str, Any]) -> None:
        if not self._debug:
            return
        if callable(self._debug):
            self._debug(event)
            return
        import sys

        status = event.get("status")
        detail = str(status) if status is not None else event.get("error", "failed")
        sys.stderr.write(
            "%s %s -> %s (%dms)\n"
            % (event["method"], event["path"], detail, event["duration_ms"])
        )

    def request(
        self,
        method: str,
        path: str,
        query: Optional[Mapping[str, Any]] = None,
        headers: Optional[Mapping[str, Any]] = None,
        body: Any = None,
        body_kind: str = "json",
        content_type: Optional[str] = None,
        body_encoding: Optional[Mapping[str, Mapping[str, str]]] = None,
        errors: Optional[Mapping[str, str]] = None,
        idempotent: bool = False,
        idempotency_key_header: Optional[str] = None,
        timeout: Optional[float] = None,
        max_retries: Optional[int] = None,
        retry: Optional[Mapping[str, Any]] = None,
        security: Optional[Sequence[Mapping[str, Sequence[str]]]] = None,
        request_options: Optional[RequestOptions] = None,
        failure_flag: Optional[str] = None,
        absolute_url: Optional[str] = None,
        schema_key: Optional[str] = None,
    ) -> Any:
        """Perform one API call, retrying per policy. Raises on failure."""
        selected = _select_security(security or [], self._credentials)
        options: RequestOptions = dict(request_options or {})  # type: ignore[assignment]
        policy: Dict[str, Any] = dict(self._retry)
        policy.update(retry or {})
        # Per-call overrides win over the operation policy and the client.
        attempts = options.get("max_retries")
        if attempts is None:
            attempts = max_retries if max_retries is not None else policy.get("max_retries", self.max_retries)
        deadline = options.get("timeout")
        if deadline is None:
            deadline = timeout if timeout is not None else self.timeout
        statuses = frozenset(policy.get("statuses") or RETRYABLE_STATUSES)
        retry_allowed = (
            idempotent
            or method == "GET"
            or idempotency_key_header is not None
            or bool(policy.get("retry_non_idempotent"))
        )

        # One key per logical call, reused across retries — the point of
        # idempotency keys.
        auto_key = str(uuid.uuid4()) if idempotency_key_header else None

        payload, content_type = _encode_body(body, body_kind, content_type, body_encoding)

        op_schemas = SCHEMAS.get(schema_key or "") if self._validate else None
        if op_schemas and op_schemas.get("req") and body is not None and body_kind in ("json", "form"):
            self._report_violations("request", method, path, body, op_schemas["req"])

        attempt = 0
        reauthenticated = False
        while True:
            url = self._build_url(path, query, selected["query"], absolute_url)
            request_headers = self._request_headers(headers, content_type, idempotency_key_header, auto_key, selected["headers"])
            for key, value in (options.get("headers") or {}).items():
                request_headers[key] = value
            if self._on_request is not None:
                self._on_request(method, url, request_headers)
            started = time.monotonic()
            try:
                status, response_headers, raw = self._transport(method, url, request_headers, payload, deadline)
                response_headers = _lower_headers(response_headers.items())
            except Exception as exc:  # noqa: BLE001 — re-raised as TransportError below
                self._emit_debug({
                    "method": method,
                    "path": path,
                    "duration_ms": int((time.monotonic() - started) * 1000),
                    "attempt": attempt + 1,
                    "error": str(exc),
                })
                if attempt < attempts and retry_allowed:
                    time.sleep(_backoff(attempt, policy))
                    attempt += 1
                    continue
                error = TransportError(_transport_message(method, url, exc))
                if self._on_error is not None:
                    self._on_error(error, method, path)
                raise error from exc

            parse_error: Optional[BaseException] = None
            try:
                parsed = _parse_body(
                    status,
                    response_headers,
                    raw,
                    strict_json=method != "HEAD" and 200 <= status < 300,
                )
            except (ValueError, RecursionError) as exc:
                parsed = raw.decode("utf-8", "replace")
                parse_error = exc
            self._emit_debug({
                "method": method,
                "path": path,
                "status": status,
                "duration_ms": int((time.monotonic() - started) * 1000),
                "attempt": attempt + 1,
                "request_id": _request_id(response_headers, parsed),
            })

            if self._on_response is not None:
                self._on_response(status, response_headers, raw)

            on_response = options.get("on_response")
            if on_response is not None:
                on_response(ResponseMeta(status, response_headers, _request_id(response_headers, parsed)))

            # A conditional request matched: nothing changed, and nothing failed.
            if status == 304:
                return None

            if 200 <= status < 300 and response_headers.get("content-type", "").lower().startswith("text/event-stream"):
                # stream=True on the JSON method: its events cannot be
                # returned as the JSON the method is typed to return.
                error = SdkError(
                    "The API answered with a server-sent event stream, which this method does not read. "
                    "Call the operation's streaming method (its name ends in _stream) instead.",
                    "unexpected_stream", status, None, _request_id(response_headers),
                )
                if self._on_error is not None:
                    self._on_error(error, method, path)
                raise error

            if parse_error is not None:
                error = ResponseParseError(status, parsed, _request_id(response_headers))
                if self._on_error is not None:
                    self._on_error(error, method, path)
                raise error from parse_error

            if 200 <= status < 300:
                # Checked before validation: a failure body rarely matches
                # the success schema, and the failure is the news.
                if failure_flag and isinstance(parsed, Mapping) and parsed.get(failure_flag) is False:
                    error = PayloadError(status, parsed, _request_id(response_headers, parsed))
                    if self._on_error is not None:
                        self._on_error(error, method, path)
                    raise error
                if op_schemas and op_schemas.get("res") and parsed is not None:
                    self._report_violations("response", method, path, parsed, op_schemas["res"])
                return parsed

            # A token from a callback or a client-credentials grant can be
            # revoked before it expires: resend once with a fresh one. The
            # resend is not a retry and does not use the retry budget.
            if status == 401 and not reauthenticated and _reauthenticate(selected):
                reauthenticated = True
                continue

            # 429 is safe to retry for any verb; other retryable statuses, and
            # a rate-limited 403, only when the call is idempotent. A
            # server-requested wait beyond max_retry_wait raises now, with the
            # reset time, rather than holding the caller.
            limit = rate_limit_info(status, response_headers)
            retryable = status in statuses or (limit is not None and status == 403)
            wait = limit.retry_after if limit is not None else None
            if wait is None:
                wait = _retry_after(response_headers)
            if (attempt < attempts and retryable and (retry_allowed or status == 429)
                    and (wait is None or wait <= self.max_retry_wait)):
                time.sleep(wait if wait is not None else _backoff(attempt, policy))
                attempt += 1
                continue

            error = _api_error(status, parsed, response_headers, errors)
            if self._on_error is not None:
                self._on_error(error, method, path)
            raise error

    def _report_violations(self, direction: str, method: str, path: str, value: Any, schema: Any) -> None:
        """Raise, or warn and continue, when a body disagrees with the spec."""
        violations: List[Violation] = []
        validate_against_schema(value, schema, direction, violations, DEFS)
        if not violations:
            return
        error = ValidationError(direction, violations)
        if self._validate == "warn":
            import warnings

            warnings.warn("%s %s: %s" % (method, path, error), stacklevel=2)
            return
        if self._on_error is not None:
            self._on_error(error, method, path)
        raise error

    def paginate(
        self,
        method: str,
        path: str,
        *,
        style: str,
        items_field: str,
        query: Optional[Mapping[str, Any]] = None,
        cursor_param: Optional[str] = None,
        next_cursor_field: Optional[str] = None,
        has_more_field: Optional[str] = None,
        id_field: Optional[str] = None,
        page_param: Optional[str] = None,
        offset_param: Optional[str] = None,
        limit_param: Optional[str] = None,
        next_url_field: Optional[str] = None,
        first_page: int = 1,
        total_field: Optional[str] = None,
        total_pages_field: Optional[str] = None,
        request_options: Optional[RequestOptions] = None,
        **kwargs: Any,
    ) -> Iterator[Any]:
        """Yield every item across every page, fetching lazily."""
        params: Dict[str, Any] = dict(query or {})
        # Start where the caller pointed: list(page=3) walks 3, 4, 5, ...
        start_page = params.get(page_param) if page_param else None
        page_number: int = start_page if isinstance(start_page, int) else first_page
        start_offset = params.get(offset_param) if offset_param else None
        offset: int = start_offset if isinstance(start_offset, int) else 0
        # The Link header is read from each response's metadata.
        seen: Dict[str, Any] = {}
        options: Dict[str, Any] = dict(request_options or {})
        caller_hook = options.get("on_response")

        def capture(meta: ResponseMeta) -> None:
            seen["meta"] = meta
            if caller_hook is not None:
                caller_hook(meta)

        options["on_response"] = capture
        next_url: Optional[str] = None
        count = 0
        while True:
            if next_url is not None:
                body = self.request(method, path, absolute_url=next_url, request_options=options, **kwargs)  # type: ignore[arg-type]
            else:
                body = self.request(method, path, query=params, request_options=options, **kwargs)  # type: ignore[arg-type]
            meta = seen.get("meta")
            if meta is not None and meta.not_modified:
                return
            items = body if items_field == "" else _get_path(body, items_field, _MISSING)
            if items is None and items_field != "":
                items = []
            if not isinstance(items, list):
                # A page without its item array is a contract break, not an
                # empty page: iterating it would silently end the walk.
                raise SdkError(
                    ("The list response is not an array" if items_field == "" else "The list response has no " + repr(items_field) + " array")
                    + ". Check the API response against the spec, or configure this operation's pagination.",
                    "pagination_error",
                )
            for item in items:
                yield item
            count += len(items)

            has_more = _get_path(body, has_more_field) if has_more_field else None
            if has_more is False:
                return
            total = _get_path(body, total_field) if total_field else None
            if isinstance(total, (int, float)) and not isinstance(total, bool) and count >= total:
                return
            if style in ("nextUrl", "link"):
                if style == "nextUrl":
                    candidate = _get_path(body, next_url_field)
                else:
                    candidate = _link_next(meta.headers.get("link") if meta is not None else None)
                if not isinstance(candidate, str) or not candidate.strip():
                    return
                next_url = self._same_origin(candidate)
                continue
            # An explicit cursor is authoritative even when filtering or
            # permissions produced an empty page. Page/offset styles have no
            # such signal, so an empty page remains their stop condition.
            if not items and style != "cursor":
                return

            if style == "cursor":
                nxt = _get_path(body, next_cursor_field) if next_cursor_field else None
                if not nxt or nxt == params.get(cursor_param or "cursor"):
                    return
                params[cursor_param or "cursor"] = nxt
            else:
                return

    def _same_origin(self, url: str) -> str:
        """A next-page URL resolved against the base URL, refused when it
        leaves the API's origin: the request carries the client's credentials."""
        target = urllib.parse.urljoin(self.base_url + "/", url)
        if _origin(target) != _origin(self.base_url):
            raise SdkError(
                "The next page is on another origin (" + target + "); refusing to send credentials there.",
                "pagination_error",
            )
        return target

    # ---- async surface ------------------------------------------------------
    # The async client shares this core: each blocking call runs on the event
    # loop's default executor, so await client.x.get() never blocks the loop
    # and the standard library stays the only dependency.

    async def arequest(self, *args: Any, **kwargs: Any) -> Any:
        """request(), awaitable."""
        loop = asyncio.get_running_loop()
        return await loop.run_in_executor(None, functools.partial(_on_loop, loop, self.request, *args, **kwargs))

    async def apaginate(self, *args: Any, **kwargs: Any) -> AsyncIterator[Any]:
        """paginate(), as an async iterator: pages are fetched off-loop as needed."""
        async for item in _aiter(self.paginate(*args, **kwargs)):
            yield item


    def _build_url(
        self, path: str, query: Optional[Mapping[str, Any]], auth_query: Optional[Mapping[str, AuthValue]] = None,
        absolute_url: Optional[str] = None,
    ) -> str:
        # A next-page URL (already checked against the base origin) replaces
        # the path and query; credentials in the query still ride along.
        url = absolute_url if absolute_url is not None else self.base_url + path
        pairs: List[Tuple[str, str]] = []
        for key, value in {**self._query, **(auth_query or {})}.items():
            resolved = _resolve(value)
            if resolved is not None:
                pairs.append((key, resolved))
        if query:
            pairs.extend(_encode_deep({k: v for k, v in query.items() if v is not None}))
        if pairs:
            url += ("&" if "?" in url else "?") + urllib.parse.urlencode(pairs)
        return url

    def _request_headers(
        self,
        headers: Optional[Mapping[str, Any]],
        content_type: Optional[str],
        idempotency_key_header: Optional[str],
        auto_key: Optional[str],
        auth_headers: Optional[Mapping[str, AuthValue]] = None,
    ) -> Dict[str, str]:
        out: Dict[str, str] = {"User-Agent": self.user_agent, "Accept": "application/json"}
        for key, value in {**self._headers, **(auth_headers or {})}.items():
            resolved = _resolve(value)
            if resolved is not None:
                out[key] = resolved
        if content_type:
            out["Content-Type"] = content_type
        if idempotency_key_header and auto_key:
            out[idempotency_key_header] = auto_key
        for key, value in (headers or {}).items():
            if value is None:
                continue
            # Booleans travel as JSON spells them, not as Python's True/False.
            out[key] = ("true" if value else "false") if isinstance(value, bool) else str(value)
        return out


_END = object()


async def _aiter(source: Iterator[Any]) -> AsyncIterator[Any]:
    """Drive a blocking iterator from a coroutine, one step per executor hop."""
    loop = asyncio.get_running_loop()
    while True:
        item = await loop.run_in_executor(None, _on_loop, loop, next, source, _END)
        if item is _END:
            return
        yield item


_REDIRECT_STATUSES = frozenset({301, 302, 303, 307, 308})
_MAX_REDIRECTS = 5
_IDLE_SECONDS = 60.0
# A burst of concurrent requests opens one connection per thread. Keeping
# every one of them afterwards would hold a socket per thread for as long as
# the client lives, so the pool keeps a working set and closes the rest at
# once. Wide enough that a repeated fan-out is not re-dialled every time.
_MAX_IDLE_PER_HOST = 16
# Dropped when a redirect crosses to another origin — the rule fetch and
# net/http apply for us in the other two languages, and this client follows
# redirects itself. A Location pointing at object storage must not carry the
# credential to a host the spec never named.
_SENSITIVE_HEADERS = frozenset({"authorization", "cookie", "cookie2", "proxy-authorization", "www-authenticate"})


def _origin(url: str) -> Tuple[str, str, int]:
    """Scheme, host, and port — what has to match for a redirect to keep the
    credential. Compared exactly, as fetch does, rather than by parent domain."""
    parts = urllib.parse.urlsplit(url)
    scheme = parts.scheme or "https"
    return scheme, (parts.hostname or "").lower(), parts.port or (443 if scheme == "https" else 80)


class _ConnectionPool:
    """Keep-alive connections on http.client, one pool per client.

    A connection is reused for the same scheme://host:port until the server
    closes it or it has sat idle for a minute. A request that fails on a
    reused connection before any response arrived is retried once on a fresh
    one — the server closed an idle keep-alive, the same case net/http
    retries — so pooling never turns into spurious transport errors.

    Idle connections are bounded and do expire. A checkout cannot be what
    enforces that: a burst followed by a lull leaves sockets parked with no
    further checkout coming, so while anything is parked one daemon thread
    sweeps the pool and closes what has aged out. It exits as soon as the
    pool drains, so an idle client costs nothing.
    """

    def __init__(self) -> None:
        self._idle: Dict[Tuple[str, str, int], List[Tuple[http.client.HTTPConnection, float]]] = {}
        self._lock = threading.Lock()
        self._proxies = urllib.request.getproxies()
        self._reaper: Optional[threading.Thread] = None
        self._wake = threading.Event()

    def close(self) -> None:
        with self._lock:
            idle, self._idle = self._idle, {}
        # The reaper checks the pool when woken and stops once it is empty.
        self._wake.set()
        for entries in idle.values():
            for connection, _ in entries:
                connection.close()

    def __call__(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        payload: Optional[bytes],
        timeout: float,
    ) -> Tuple[int, Dict[str, str], bytes]:
        status, response_headers, body = self._once(method, url, headers, payload, timeout)
        for _ in range(_MAX_REDIRECTS):
            if status not in _REDIRECT_STATUSES or "location" not in response_headers:
                break
            # The same policy urllib applies: GET/HEAD follow every redirect,
            # 303 turns a write into a GET, and 307/308 replay the request.
            if status in (301, 302, 303) and method not in ("GET", "HEAD"):
                if status != 303:
                    return status, response_headers, body
                method, payload = "GET", None
                headers = {k: v for k, v in headers.items() if k.lower() not in ("content-type", "content-length")}
            target = urllib.parse.urljoin(url, response_headers["location"])
            if _origin(target) != _origin(url):
                headers = {k: v for k, v in headers.items() if k.lower() not in _SENSITIVE_HEADERS}
            url = target
            status, response_headers, body = self._once(method, url, headers, payload, timeout)
        return status, response_headers, body

    def _once(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        payload: Optional[bytes],
        timeout: float,
    ) -> Tuple[int, Dict[str, str], bytes]:
        parts = urllib.parse.urlsplit(url)
        scheme = parts.scheme or "https"
        host = parts.hostname or ""
        port = parts.port or (443 if scheme == "https" else 80)
        path = (parts.path or "/") + ("?" + parts.query if parts.query else "")
        key = (scheme, host, port)
        connection, reused = self._acquire(key, scheme, host, port, timeout)
        request_target = path
        if connection.host != host and scheme == "http":
            request_target = url  # plain-http proxy: absolute-form request line
        try:
            if connection.sock is not None:
                connection.sock.settimeout(timeout)
            connection.request(method, request_target, body=payload, headers=dict(headers))
            response = connection.getresponse()
            body = response.read()
        except (http.client.RemoteDisconnected, http.client.BadStatusLine, ConnectionResetError, BrokenPipeError) as exc:
            connection.close()
            if reused:
                # The server closed an idle keep-alive under us; nothing was
                # answered, so a fresh connection is safe for any method.
                connection, _ = self._acquire(key, scheme, host, port, timeout, fresh=True)
                try:
                    if connection.sock is not None:
                        connection.sock.settimeout(timeout)
                    connection.request(method, request_target, body=payload, headers=dict(headers))
                    response = connection.getresponse()
                    body = response.read()
                except Exception:
                    connection.close()
                    raise
            else:
                raise exc
        except Exception:
            connection.close()
            raise
        response_headers = {k.lower(): v for k, v in response.getheaders()}
        if response.will_close:
            connection.close()
        else:
            self._release(key, connection)
        return response.status, response_headers, body

    def _acquire(
        self, key: Tuple[str, str, int], scheme: str, host: str, port: int, timeout: float, fresh: bool = False
    ) -> Tuple[http.client.HTTPConnection, bool]:
        if not fresh:
            with self._lock:
                entries = self._idle.get(key) or []
                while entries:
                    connection, idle_since = entries.pop()
                    if time.monotonic() - idle_since < _IDLE_SECONDS:
                        return connection, True
                    connection.close()
        proxy = self._proxies.get(scheme)
        if proxy and not urllib.request.proxy_bypass(host):
            proxy_parts = urllib.parse.urlsplit(proxy if "://" in proxy else "http://" + proxy)
            proxy_host = proxy_parts.hostname or ""
            proxy_port = proxy_parts.port or (443 if proxy_parts.scheme == "https" else 80)
            if scheme == "https":
                connection: http.client.HTTPConnection = http.client.HTTPSConnection(proxy_host, proxy_port, timeout=timeout)
                connection.set_tunnel(host, port)
                return connection, False
            return http.client.HTTPConnection(proxy_host, proxy_port, timeout=timeout), False
        if scheme == "https":
            return http.client.HTTPSConnection(host, port, timeout=timeout), False
        return http.client.HTTPConnection(host, port, timeout=timeout), False

    def _sweep(self, now: float) -> List[http.client.HTTPConnection]:
        """Drop what has aged out or overflows the cap. Call under the lock;
        the connections it returns are closed by the caller, outside it."""
        stale: List[http.client.HTTPConnection] = []
        for key in list(self._idle):
            entries = self._idle[key]
            fresh = [entry for entry in entries if now - entry[1] < _IDLE_SECONDS]
            stale.extend(connection for connection, since in entries if now - since >= _IDLE_SECONDS)
            if len(fresh) > _MAX_IDLE_PER_HOST:
                # Oldest first: the newest connections are the ones a burst
                # is most likely to want again.
                overflow = len(fresh) - _MAX_IDLE_PER_HOST
                stale.extend(connection for connection, _ in fresh[:overflow])
                fresh = fresh[overflow:]
            if fresh:
                self._idle[key] = fresh
            else:
                del self._idle[key]
        return stale

    def _reap(self) -> None:
        """Close aged-out connections until the pool is empty, then stop."""
        while True:
            self._wake.wait(_IDLE_SECONDS)
            with self._lock:
                self._wake.clear()
                stale = self._sweep(time.monotonic())
                done = not self._idle
                if done:
                    self._reaper = None
            for connection in stale:
                connection.close()
            if done:
                return

    def _release(self, key: Tuple[str, str, int], connection: http.client.HTTPConnection) -> None:
        with self._lock:
            self._idle.setdefault(key, []).append((connection, time.monotonic()))
            stale = self._sweep(time.monotonic())
            if self._idle and self._reaper is None:
                reaper = threading.Thread(target=self._reap, name="http-idle-reaper", daemon=True)
                try:
                    reaper.start()
                except RuntimeError:
                    # Interpreter shutting down: no thread can be started, so
                    # keeping the connection would leave it unreaped.
                    stale.extend(c for entries in self._idle.values() for c, _ in entries)
                    self._idle.clear()
                else:
                    self._reaper = reaper
        for dead in stale:
            dead.close()





def _lower_headers(items: Any) -> Dict[str, str]:
    return {str(k).lower(): str(v) for k, v in items}


def _encode_body(
    body: Any, kind: str, content_type: Optional[str] = None, encoding: Optional[Mapping[str, Mapping[str, str]]] = None
) -> Tuple[Optional[bytes], Optional[str]]:
    if body is None:
        return None, None
    if kind == "json":
        return _json.dumps(body).encode("utf-8"), "application/json"
    if kind == "form":
        fields = dict(body)
        # An unexploded array (encoding explode: false) is one delimited value.
        for key, rule in (encoding or {}).items():
            delimiter = rule.get("delimiter")
            if delimiter is not None and isinstance(fields.get(key), (list, tuple)):
                fields[key] = delimiter.join(
                    ("true" if item else "false") if isinstance(item, bool) else str(item) for item in fields[key]
                )
        return (
            urllib.parse.urlencode(_encode_deep(fields, sort_keys=True)).encode("utf-8"),
            "application/x-www-form-urlencoded",
        )

    if kind == "text":
        return str(body).encode("utf-8"), "text/plain"
    if kind == "binary":
        return _read_bytes(body), content_type or "application/octet-stream"
    if isinstance(body, bytes):
        return body, content_type
    return _json.dumps(body).encode("utf-8"), "application/json"


def _read_bytes(value: Any) -> bytes:
    """bytes, bytearray, or anything with .read() (an open file)."""
    if isinstance(value, (bytes, bytearray)):
        return bytes(value)
    if hasattr(value, "read"):
        data = value.read()
        return data if isinstance(data, bytes) else str(data).encode("utf-8")
    return str(value).encode("utf-8")





def _reject_json_constant(value: str) -> Any:
    """Python accepts NaN and Infinity by default; JSON does not."""
    raise ValueError("invalid JSON constant " + value)


def _parse_body(status: int, headers: Mapping[str, str], raw: bytes, strict_json: bool = False) -> Any:
    if status in (204, 205) or not raw:
        return None
    content_type = headers.get("content-type", "")
    media_type = content_type.split(";", 1)[0].strip().lower()
    subtype = media_type.split("/", 1)[1] if "/" in media_type else ""
    if subtype == "json" or subtype.endswith("+json"):
        try:
            text = raw.decode("utf-8")
            if strict_json:
                return _json.loads(text, parse_constant=_reject_json_constant)
            return _json.loads(text)
        except (ValueError, RecursionError):
            if strict_json:
                raise
            return raw.decode("utf-8", "replace")
    if media_type.startswith("text/"):
        return raw.decode("utf-8", "replace")
    return raw


def _api_error(
    status: int,
    body: Any,
    headers: Mapping[str, str],
    errors: Optional[Mapping[str, str]],
) -> ApiError:
    name = None
    if errors:
        name = errors.get(str(status)) or errors.get(str(status // 100) + "XX") or errors.get("default")
    cls = error_for_status(name)
    request_id = _request_id(headers, body)
    # A rate limit is its own error whatever the status: a 403 that means
    # "wait" must not read as "your credential lacks access". A 429 the spec
    # documents keeps its generated class (which carries rate_limit).
    if rate_limit_info(status, headers) is not None and not (status == 429 and errors and errors.get("429")):
        return RateLimitError(status, body, request_id, headers=headers)
    if cls is None:
        return UnexpectedApiError(status, body, request_id, headers=headers)
    return cls(status, body, request_id, headers=headers)


def _request_id(headers: Mapping[str, str], body: Any = None) -> Optional[str]:
    """Prefer JSON response metadata; raw responses fall back to headers."""
    value = None
    if isinstance(body, Mapping):
        candidate = body.get("request_id") or body.get("requestId")
        if isinstance(candidate, str) and candidate:
            value = candidate
    if not value:
        for name in _REQUEST_ID_HEADERS:
            if headers.get(name):
                value = headers[name]
                break
    return value


#: Response headers that carry a request identifier, most specific first.
_REQUEST_ID_HEADERS = ("request-id", "x-request-id", "x-github-request-id", "twilio-request-id", "x-amzn-requestid", "x-slack-req-id", "cf-ray")


def _retry_after(headers: Mapping[str, str]) -> Optional[float]:
    """Retry-After in seconds on a retryable status that is not a rate limit."""
    value = headers.get("retry-after")
    if not value:
        return None
    try:
        return max(float(value), 0.0)
    except ValueError:
        return None


def _backoff(attempt: int, policy: Mapping[str, Any]) -> float:
    initial = policy.get("initial_delay_ms")
    maximum = policy.get("max_delay_ms")
    base = (initial / 1000.0) if isinstance(initial, (int, float)) else _INITIAL_BACKOFF
    cap = (maximum / 1000.0) if isinstance(maximum, (int, float)) else _MAX_BACKOFF
    return random.random() * min(base * (2 ** attempt), cap)


def _transport_message(method: str, url: str, exc: BaseException) -> str:
    """Bare "connection failed" is useless in a bug report; surface the cause."""
    detail = str(exc) or exc.__class__.__name__
    cause = getattr(exc, "reason", None)
    if cause is not None and str(cause) not in detail:
        detail += ": " + str(cause)
    return method + " " + url + " failed: " + detail
