"""Typed exceptions. Generated by typeship — https://typeship.dev"""
from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Mapping, Optional, Type


class SdkError(Exception):
    """Base class with a stable code and request context for every failure."""

    def __init__(self, message: str, code: str = "sdk_error", status: Optional[int] = None,
                 body: Any = None, request_id: Optional[str] = None) -> None:
        self.code = code
        self.status = status
        self.body = body
        self.request_id = request_id
        super().__init__(message)


class TransportError(SdkError):
    """No HTTP response at all: network failure, timeout, or DNS."""

    def __init__(self, message: str) -> None:
        super().__init__(message + ". Check the connection and retry.", "transport_error")


class ResponseParseError(SdkError):
    """A successful response declared JSON but carried malformed JSON."""

    def __init__(self, status: int, body: str, request_id: Optional[str] = None) -> None:
        suffix = " (request " + request_id + ")" if request_id else ""
        message = ("HTTP " + str(status) + " response body was not valid JSON" + suffix
                   + ". Check the API response or contact its provider.")
        super().__init__(message,
                         "response_parse_error", status, body, request_id)


class RateLimitInfo:
    """When a rate-limited call can be retried; both fields are None when the
    API did not say."""

    def __init__(self, retry_at: Optional[datetime] = None, retry_after: Optional[float] = None) -> None:
        #: The instant the limit resets (from Retry-After or x-ratelimit-reset).
        self.retry_at = retry_at
        #: Seconds from when the response arrived until retry_at.
        self.retry_after = retry_after

    def __repr__(self) -> str:
        return "RateLimitInfo(retry_at=%r)" % (self.retry_at,)


def rate_limit_info(
    status: int, headers: Optional[Mapping[str, str]], now: Optional[float] = None
) -> Optional[RateLimitInfo]:
    """Whether a response is a rate limit, and when to retry. A 429 always is;
    a 403 is when it says the quota is spent (x-ratelimit-remaining: 0) or
    asks the caller to wait (Retry-After), which is how GitHub signals its
    limits. None for every other response."""
    headers = headers or {}
    retry_after = headers.get("retry-after")
    remaining = headers.get("x-ratelimit-remaining") or headers.get("ratelimit-remaining")
    spent = remaining is not None and remaining.strip() == "0"
    limited = status == 429 or (status == 403 and (retry_after is not None or spent))
    if not limited:
        return None
    now = time.time() if now is None else now
    wait: Optional[float] = None
    if retry_after and retry_after.strip():
        try:
            wait = max(float(retry_after), 0.0)
        except ValueError:
            try:
                from email.utils import parsedate_to_datetime

                wait = max(parsedate_to_datetime(retry_after).timestamp() - now, 0.0)
            except (TypeError, ValueError, IndexError):
                wait = None
    reset = headers.get("x-ratelimit-reset") or headers.get("ratelimit-reset")
    if wait is None and reset and reset.strip():
        try:
            value = float(reset)
            # An epoch timestamp (GitHub) or seconds until the reset (IETF).
            wait = max(value - now if value > 1e9 else value, 0.0)
        except ValueError:
            wait = None
    if wait is None:
        return RateLimitInfo()
    return RateLimitInfo(datetime.fromtimestamp(now + wait, tz=timezone.utc), wait)


def _rate_limit_step(info: RateLimitInfo) -> str:
    if info.retry_at is None:
        return "Rate limited: wait before retrying."
    # Round up to the second so "wait until" is never early.
    seconds = int(-(-info.retry_at.timestamp() // 1))
    at = datetime.fromtimestamp(seconds, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return "Rate limited: wait until " + at + ", then retry."


def _next_step(status: int) -> str:
    if 200 <= status < 300:
        return "It arrived in a successful HTTP response; the body says why."
    if status == 401:
        return "Check the credential and retry."
    if status == 403:
        return "Check the credential's permissions and retry."
    if status == 404:
        return "Check the requested identifier or path."
    if status == 409:
        return "Refresh the resource and retry the change."
    if status in (400, 422):
        return "Correct the request and retry."
    if status == 429:
        return "Wait before retrying the request."
    if status >= 500:
        return "Retry later; contact the API provider if this continues."
    return "Inspect the error body and correct the request before retrying."


class ApiError(SdkError):
    """An error response from the API.

    status  the HTTP status code
    body    the parsed response body, typed per operation in the docs
    request_id  the API's request id, when it sent one
    """

    status: int = 0
    #: Set when the API said this call was rate limited: when to retry.
    rate_limit: Optional[RateLimitInfo] = None

    def __init__(self, status: int, body: Any = None, request_id: Optional[str] = None,
                 headers: Optional[Mapping[str, str]] = None, summary: Optional[str] = None) -> None:
        detail = ""
        limit = rate_limit_info(status, headers)
        code = "rate_limited" if limit is not None else "http_" + str(status)
        if isinstance(body, dict):
            if isinstance(body.get("code"), str) and body["code"]:
                code = body["code"]
            first = body.get("errors", [None])
            first = first[0] if isinstance(first, list) and first else None
            if isinstance(first, dict) and isinstance(first.get("code"), str) and first["code"]:
                code = first["code"]
            elif isinstance(first, dict) and type(first.get("code")) is int:
                code = str(first["code"])
            elif not body.get("code") and isinstance(body.get("error"), str) and _looks_like_code(body["error"]):
                # Slack-style {"ok": false, "error": "invalid_auth"}.
                code = body["error"]
            message = body.get("message") or body.get("error") or body.get("detail")
            if not message and isinstance(first, dict):
                message = first.get("message")
            if isinstance(message, str):
                # An API message usually ends its own sentence; do not double it.
                detail = ": " + message.rstrip(".!?")
        suffix = " (request " + request_id + ")" if request_id else ""
        step = _rate_limit_step(limit) if limit is not None else _next_step(status)
        super().__init__((summary or "HTTP " + str(status)) + detail + suffix + ". " + step,
                         code, status, body, request_id)
        self.rate_limit = limit


def _looks_like_code(value: str) -> bool:
    return 0 < len(value) <= 64 and value[0].isalpha() and all(c.isalnum() or c in "_.-" for c in value)


class UnexpectedApiError(ApiError):
    """A status the spec did not document."""


class RateLimitError(ApiError):
    """The API rate limited the call: a 403 whose headers say the quota is
    spent, or a 429 the spec did not document. rate_limit.retry_at says when
    to try again; every ApiError carries rate_limit when it applies."""


class PayloadError(ApiError):
    """A 2xx response whose payload reported a failure: a declared envelope
    flag set to false ({"ok": false}, {"success": false}), or a GraphQL
    result that is one of the schema's error types.

    typename  the GraphQL error type the result resolved to, if any
    """

    def __init__(self, status: int, body: Any = None, request_id: Optional[str] = None,
                 headers: Optional[Mapping[str, str]] = None, typename: Optional[str] = None) -> None:
        self.typename = typename
        if typename:
            summary = "The operation returned " + typename
        else:
            summary = "The API reported a failure"
        super().__init__(status, body, request_id, headers=headers, summary=summary)


class BadRequestError(ApiError):
    """Invalid name, Spec source, or field value."""
    status = 400


class UnauthorizedError(ApiError):
    """Missing, invalid, expired, or revoked credentials."""
    status = 401


class PaymentRequiredError(ApiError):
    """The plan does not include another project or the requested target configuration."""
    status = 402


class ForbiddenError(ApiError):
    """The credentials are valid but cannot act on the requested organization."""
    status = 403


class ConflictError(ApiError):
    """A Delivery conflicts, or the key identifies changed intent."""
    status = 409


class UnprocessableEntityError(ApiError):
    """The configured source could not be read and analyzed, so the project was not created."""
    status = 422


class RateLimitedError(ApiError):
    """Too many requests, or an identical write is still in progress. Wait for Retry-After before retrying."""
    status = 429


class InternalServerError(ApiError):
    """Project setup failed unexpectedly; the key reservation is released."""
    status = 500


class NotFoundError(ApiError):
    """No such resource in this organization."""
    status = 404


class PreconditionFailedError(ApiError):
    """The resource changed since the ETag supplied in If-Match. No write was applied."""
    status = 412


class BadGatewayError(ApiError):
    """Dependent work failed while completing the request."""
    status = 502


class PayloadTooLargeError(ApiError):
    """The Spec exceeds the supported size."""
    status = 413


class ApiResponseError(ApiError):
    """Unexpected error."""


_BY_NAME: Dict[str, Type[ApiError]] = {
    "BadRequestError": BadRequestError,
    "UnauthorizedError": UnauthorizedError,
    "PaymentRequiredError": PaymentRequiredError,
    "ForbiddenError": ForbiddenError,
    "ConflictError": ConflictError,
    "UnprocessableEntityError": UnprocessableEntityError,
    "RateLimitedError": RateLimitedError,
    "InternalServerError": InternalServerError,
    "NotFoundError": NotFoundError,
    "PreconditionFailedError": PreconditionFailedError,
    "BadGatewayError": BadGatewayError,
    "PayloadTooLargeError": PayloadTooLargeError,
    "ApiResponseError": ApiResponseError,
}


def error_for_status(name: Optional[str]) -> Optional[Type[ApiError]]:
    """Resolve a generated error class by name, or None when undocumented."""
    if name is None:
        return None
    return _BY_NAME.get(name)
