"""Typed exceptions. Generated by typeship — https://typeship.dev"""
from __future__ import annotations

from typing import Any, Dict, List, Optional, Type


class TypeshipError(Exception):
    """Base class for everything this SDK raises."""


class TransportError(TypeshipError):
    """No HTTP response at all: network failure, timeout, or DNS."""


class ResponseParseError(TypeshipError):
    """A successful response declared JSON but carried malformed JSON."""

    def __init__(self, status: int, body: str, request_id: Optional[str] = None) -> None:
        self.status = status
        self.body = body
        self.request_id = request_id
        suffix = " (request " + request_id + ")" if request_id else ""
        super().__init__("HTTP " + str(status) + " response body was not valid JSON" + suffix)


class ApiError(TypeshipError):
    """An error response from the API.

    status  the HTTP status code
    body    the parsed response body, typed per operation in the docs
    request_id  the API's request id, when it sent one
    """

    status: int = 0

    def __init__(self, status: int, body: Any = None, request_id: Optional[str] = None) -> None:
        self.status = status
        self.body = body
        self.request_id = request_id
        detail = ""
        if isinstance(body, dict):
            message = body.get("message") or body.get("error") or body.get("detail")
            if isinstance(message, str):
                detail = ": " + message
        suffix = " (request " + request_id + ")" if request_id else ""
        super().__init__("HTTP " + str(status) + detail + suffix)


class UnexpectedApiError(ApiError):
    """A status the spec did not document."""


class BadRequestError(ApiError):
    """The request body, Definition source, target selection, or package name is invalid."""
    status = 400


class UnauthorizedError(ApiError):
    """Missing, invalid, expired, or revoked credentials."""
    status = 401


class ForbiddenError(ApiError):
    """The credentials are valid but cannot act on the requested organization."""
    status = 403


class ConflictError(ApiError):
    """The key identifies changed intent."""
    status = 409


class PayloadTooLargeError(ApiError):
    """Spec exceeds the 10MB limit."""
    status = 413


class UnprocessableEntityError(ApiError):
    """The Definition could not be resolved or understood."""
    status = 422


class RateLimitedError(ApiError):
    """Too many requests, or an identical write is still in progress. Wait for Retry-After before retrying."""
    status = 429


class InternalServerError(ApiError):
    """An unexpected error prevented the request from completing."""
    status = 500


class ApiResponseError(ApiError):
    """Unexpected error."""


class NotFoundError(ApiError):
    """No such resource in this account."""
    status = 404


class PaymentRequiredError(ApiError):
    """The plan does not include another project or the requested target configuration."""
    status = 402


class BadGatewayError(ApiError):
    """Dependent work failed while completing the request."""
    status = 502


class PreconditionFailedError(ApiError):
    """The Draft's version selection changed since the ETag in If-Match."""
    status = 412


_BY_NAME: Dict[str, Type[ApiError]] = {
    "BadRequestError": BadRequestError,
    "UnauthorizedError": UnauthorizedError,
    "ForbiddenError": ForbiddenError,
    "ConflictError": ConflictError,
    "PayloadTooLargeError": PayloadTooLargeError,
    "UnprocessableEntityError": UnprocessableEntityError,
    "RateLimitedError": RateLimitedError,
    "InternalServerError": InternalServerError,
    "ApiResponseError": ApiResponseError,
    "NotFoundError": NotFoundError,
    "PaymentRequiredError": PaymentRequiredError,
    "BadGatewayError": BadGatewayError,
    "PreconditionFailedError": PreconditionFailedError,
}


def error_for_status(name: Optional[str]) -> Optional[Type[ApiError]]:
    """Resolve a generated error class by name, or None when undocumented."""
    if name is None:
        return None
    return _BY_NAME.get(name)
