"""Typed exceptions. Generated by typeship — https://typeship.dev"""
from __future__ import annotations

import time
from datetime import datetime, timezone
from typing import Any, Dict, List, Mapping, Optional, Tuple, Type


class SdkError(Exception):
    """Base class with a stable code and request context for every failure."""

    def __init__(self, message: str, code: str = "sdk_error", status: Optional[int] = None,
                 body: Any = None, request_id: Optional[str] = None) -> None:
        self.code = code
        self.status = status
        self.body = body
        self.request_id = request_id
        super().__init__(message)


class TransportError(SdkError):
    """No HTTP response at all: network failure, timeout, or DNS."""

    def __init__(self, message: str) -> None:
        super().__init__(message + ". Check the connection and retry.", "transport_error")


class ResponseParseError(SdkError):
    """A successful response declared JSON but carried malformed JSON."""

    def __init__(self, status: int, body: str, request_id: Optional[str] = None) -> None:
        suffix = " (request " + request_id + ")" if request_id else ""
        message = ("HTTP " + str(status) + " response body was not valid JSON" + suffix
                   + ". Check the API response or contact its provider.")
        super().__init__(message,
                         "response_parse_error", status, body, request_id)


class PaginationError(SdkError):
    """A list response the pagination rules cannot read, or a next page the
    client refuses to fetch. The code is "pagination_error"."""

    def __init__(self, message: str, status: Optional[int] = None, body: Any = None,
                 request_id: Optional[str] = None) -> None:
        super().__init__(message, "pagination_error", status, body, request_id)


class RateLimitInfo:
    """When a rate-limited call can be retried; both fields are None when the
    API did not say."""

    def __init__(self, retry_at: Optional[datetime] = None, retry_after: Optional[float] = None) -> None:
        #: The instant the limit resets (from Retry-After or x-ratelimit-reset).
        self.retry_at = retry_at
        #: Seconds from when the response arrived until retry_at.
        self.retry_after = retry_after

    def __repr__(self) -> str:
        return "RateLimitInfo(retry_at=%r)" % (self.retry_at,)


def rate_limit_info(
    status: int, headers: Optional[Mapping[str, str]], now: Optional[float] = None
) -> Optional[RateLimitInfo]:
    """Whether a response is a rate limit, and when to retry. A 429 always is;
    a 403 is when it says the quota is spent (x-ratelimit-remaining: 0) or
    asks the caller to wait (Retry-After), which is how GitHub signals its
    limits. None for every other response."""
    headers = headers or {}
    retry_after = headers.get("retry-after")
    remaining = headers.get("x-ratelimit-remaining") or headers.get("ratelimit-remaining")
    spent = remaining is not None and remaining.strip() == "0"
    limited = status == 429 or (status == 403 and (retry_after is not None or spent))
    if not limited:
        return None
    now = time.time() if now is None else now
    wait: Optional[float] = None
    if retry_after and retry_after.strip():
        try:
            wait = max(float(retry_after), 0.0)
        except ValueError:
            try:
                from email.utils import parsedate_to_datetime

                wait = max(parsedate_to_datetime(retry_after).timestamp() - now, 0.0)
            except (TypeError, ValueError, IndexError):
                wait = None
    reset = headers.get("x-ratelimit-reset") or headers.get("ratelimit-reset")
    if wait is None and reset and reset.strip():
        try:
            value = float(reset)
            # An epoch timestamp (GitHub) or seconds until the reset (IETF).
            wait = max(value - now if value > 1e9 else value, 0.0)
        except ValueError:
            wait = None
    if wait is None:
        return RateLimitInfo()
    return RateLimitInfo(datetime.fromtimestamp(now + wait, tz=timezone.utc), wait)


def _rate_limit_step(info: RateLimitInfo) -> str:
    if info.retry_at is None:
        return "Rate limited: wait before retrying."
    # Round up to the second so "wait until" is never early.
    seconds = int(-(-info.retry_at.timestamp() // 1))
    at = datetime.fromtimestamp(seconds, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return "Rate limited: wait until " + at + ", then retry."


def _next_step(status: int) -> str:
    if 200 <= status < 300:
        return "It arrived in a successful HTTP response; the body says why."
    if status == 401:
        return "Check the credential and retry."
    if status == 403:
        return "Check the credential's permissions and retry."
    if status == 404:
        return "Check the requested identifier or path."
    if status == 409:
        return "Refresh the resource and retry the change."
    if status == 413:
        return "Send less data in one request."
    if status in (400, 422):
        return "Correct the request and retry."
    if status == 429:
        return "Wait before retrying the request."
    if status >= 500:
        return "Retry later; contact the API provider if this continues."
    return "Inspect the error body and correct the request before retrying."


class ApiError(SdkError):
    """An error response from the API.

    status  the HTTP status code
    body    the parsed response body, typed per operation in the docs
    request_id  the API's request id, when it sent one
    """

    status: int = 0
    #: Set when the API said this call was rate limited: when to retry.
    rate_limit: Optional[RateLimitInfo] = None

    def __init__(self, status: int, body: Any = None, request_id: Optional[str] = None,
                 headers: Optional[Mapping[str, str]] = None, summary: Optional[str] = None) -> None:
        limit = rate_limit_info(status, headers)
        code = _error_code(body) or ("rate_limited" if limit is not None else "http_" + str(status))
        message = _error_message(body)
        # An API message usually ends its own sentence; do not double it.
        detail = ": " + message.rstrip(".!?") if message else ""
        suffix = " (request " + request_id + ")" if request_id else ""
        step = _rate_limit_step(limit) if limit is not None else _next_step(status)
        super().__init__((summary or "HTTP " + str(status)) + detail + suffix + ". " + step,
                         code, status, body, request_id)
        self.rate_limit = limit


def _error_parts(body: Any) -> Tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any]]:
    if not isinstance(body, dict):
        return {}, {}, {}
    nested = body.get("error")
    errors = body.get("errors")
    first = errors[0] if isinstance(errors, list) and errors else None
    return body, nested if isinstance(nested, dict) else {}, first if isinstance(first, dict) else {}


def _error_code(body: Any) -> Optional[str]:
    """The API's own error code: error.code, code, error.type, then
    errors[0].code; numeric codes (Twilio's 20404) as strings."""
    value, nested, first = _error_parts(body)
    for code in (nested.get("code"), value.get("code"), nested.get("type"), first.get("code")):
        if isinstance(code, str) and code.strip():
            return code
        if isinstance(code, int) and not isinstance(code, bool):
            return str(code)
    error = value.get("error")
    if isinstance(error, str) and _looks_like_code(error):
        # Slack-style {"ok": false, "error": "invalid_auth"}.
        return error
    return None


def _error_message(body: Any) -> Optional[str]:
    """The API's own message: error.message, message, errors[0].message,
    detail, error_description, then a string error."""
    value, nested, first = _error_parts(body)
    for message in (nested.get("message"), value.get("message"), first.get("message"),
                    value.get("detail"), value.get("error_description"), value.get("error")):
        if isinstance(message, str) and message.strip():
            return message.strip()
    return None


def _looks_like_code(value: str) -> bool:
    return 0 < len(value) <= 64 and value[0].isalpha() and all(c.isalnum() or c in "_.-" for c in value)


class UnexpectedApiError(ApiError):
    """A status with no family class (a 402, 405 or 410, say) that the
    operation did not document."""


class BadRequestError(ApiError):
    """HTTP 400: the API rejected the request as malformed. Raised for every
    400, documented or not."""

    status = 400


class UnauthorizedError(ApiError):
    """HTTP 401: the credential is missing, invalid or expired."""

    status = 401


class ForbiddenError(ApiError):
    """HTTP 403: the credential lacks access. A 403 that signals a rate
    limit raises RateLimitError instead."""

    status = 403


class NotFoundError(ApiError):
    """HTTP 404: the resource or path does not exist."""

    status = 404


class ConflictError(ApiError):
    """HTTP 409: the request conflicts with the resource's current state."""

    status = 409


class UnprocessableEntityError(ApiError):
    """HTTP 422: the request was well formed but failed validation."""

    status = 422


class RateLimitError(ApiError):
    """The API rate limited the call: every 429, and a 403 whose headers say
    the quota is spent. rate_limit.retry_at says when to try again; every
    ApiError carries rate_limit when it applies."""


class ServerError(ApiError):
    """Any 5xx: the API failed to handle a valid request."""


def status_family(status: int) -> Optional[Type[ApiError]]:
    """The class raised for a status whatever the operation documents."""
    family = _FAMILIES.get(status)
    if family is None and 500 <= status < 600:
        return ServerError
    return family


_FAMILIES: Dict[int, Type[ApiError]] = {
    400: BadRequestError,
    401: UnauthorizedError,
    403: ForbiddenError,
    404: NotFoundError,
    409: ConflictError,
    422: UnprocessableEntityError,
    429: RateLimitError,
}


class PayloadError(ApiError):
    """A 2xx response whose payload reported a failure: a declared envelope
    flag set to false ({"ok": false}, {"success": false}), or a GraphQL
    result that is one of the schema's error types.

    typename  the GraphQL error type the result resolved to, if any
    """

    def __init__(self, status: int, body: Any = None, request_id: Optional[str] = None,
                 headers: Optional[Mapping[str, str]] = None, typename: Optional[str] = None) -> None:
        self.typename = typename
        if typename:
            summary = "The operation returned " + typename
        else:
            summary = "The API reported a failure"
        super().__init__(status, body, request_id, headers=headers, summary=summary)


class PaymentRequiredError(ApiError):
    """Raised for HTTP 402 responses."""
    status = 402


class PreconditionFailedError(ApiError):
    """Raised for HTTP 412 responses."""
    status = 412


class PayloadTooLargeError(ApiError):
    """Raised for HTTP 413 responses."""
    status = 413


class ApiResponseError(ApiError):
    """Raised for "default" responses."""


RateLimitedError = RateLimitError  # Deprecated: catch RateLimitError.
InternalServerError = ServerError  # Deprecated: catch ServerError.
BadGatewayError = ServerError  # Deprecated: catch ServerError.


_BY_NAME: Dict[str, Type[ApiError]] = {
    "PaymentRequiredError": PaymentRequiredError,
    "PreconditionFailedError": PreconditionFailedError,
    "PayloadTooLargeError": PayloadTooLargeError,
    "ApiResponseError": ApiResponseError,
}


def error_for_status(name: Optional[str]) -> Optional[Type[ApiError]]:
    """Resolve a generated error class by name, or None when undocumented."""
    if name is None:
        return None
    return _BY_NAME.get(name)
