"""typeship — API types.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union


class GeneratedFile(TypedDict):
    # Repo-relative path inside the generated package.
    path: str
    content: str


GeneratorKindRead = Union[Literal["typescript-sdk", "python-sdk", "go-sdk", "cli", "mcp"], str]


class DiagnosticSummary(TypedDict):
    """Counts distinguish decisions from the number of affected schema locations."""
    # Number of grouped rule diagnostics.
    diagnostics: int
    # Total affected locations across all diagnostics.
    occurrences: int
    # Grouped correctness errors.
    errors: int
    # Grouped material risks.
    warnings: int
    # Grouped improvements.
    suggestions: int
    # Diagnostics with exact reviewable Definition patches.
    auto_fixable: int


class GenerationMetaReadDiagnostics(TypedDict):
    """Deterministic Diagnostic summary for the exact Definition Revision consumed."""
    format: Union[Literal["openapi", "graphql"], str]
    summary: DiagnosticSummary


class _GenerationMetaReadRequired(TypedDict):
    title: str
    # Version declared by the customer's API Definition. It never controls package releases.
    api_version: str
    # Package version selected by the Target's release stream for this generation.
    version: str
    # Detected OpenAPI version, "2.0", "3.0", or "3.1".
    oas_version: str
    # Ecosystem-neutral identity of the generated artifact.
    artifact_name: str
    client_name: str
    # Generator implementations present in this artifact. Persisted Target identity is reported on
    # Generation.
    generators: List[Union[GeneratorKindRead, str]]


class GenerationMetaRead(_GenerationMetaReadRequired, total=False):
    spec_format: Union[Literal["openapi", "graphql"], str]
    # True when the input was Swagger 2.0 and was converted.
    converted: bool
    resource_count: int
    operation_count: int
    schema_count: int
    paginated_operation_count: int
    # Operations beyond the plan's endpoint allowance, not generated.
    omitted_operation_count: int
    # Pull request opened by this regeneration, when one was.
    pr_url: Optional[str]
    pr_number: Optional[int]
    # Whether a destination pull request opened, was unnecessary because the generated tree already
    # matched, or could not be opened.
    pr_status: Union[Literal["opened", "no_changes", "blocked"], str]
    # Why the configured destination pull request was not opened. Generation itself still succeeded;
    # fix this action and regenerate.
    pr_error: str
    # Markdown changelog entry for this regeneration, from the API surface diff. Absent on a first
    # generation or when nothing changed.
    changelog: str
    # Breaking changes in the diff; removed methods and fields, changed types, inputs that became
    # required.
    breaking_count: int
    # What the diff was measured against; "destination" means the .typeship/surface.json merged in
    # the destination repository.
    baseline: Union[Literal["destination", "none"], str]
    # Objective compatibility of the generated API surface against the merged destination baseline.
    api_compatibility: Union[Literal["compatible", "breaking", "unknown"], str]
    # Objective compatibility of public package entry points and selected targets against the merged
    # destination baseline.
    package_compatibility: Union[Literal["compatible", "breaking", "unknown"], str]
    # Whether the generated package version satisfies the cumulative change. Null when there is no
    # prior version or analysis is unavailable.
    version_correct: Optional[bool]
    # The destination pull request's combined readiness decision for the exact bot-generated head.
    # Compatibility and version correctness remain separate fields above.
    release_readiness: Union[Literal["success", "failure", "error"], str]
    # The release-readiness decision in one line, as the commit status describes it.
    release_readiness_note: str
    # The package version the destination had before this regeneration.
    previous_version: str
    file_count: int
    total_lines: int
    # Deterministic Diagnostic summary for the exact Definition Revision consumed.
    diagnostics: GenerationMetaReadDiagnostics


class _GenerationLimitsReadRequired(TypedDict):
    # How many operations this generation was allowed to include.
    max_operations: int
    # How many operations are present in the generated package.
    generated_operations: int
    # How many operations in the Definition were left out.
    omitted_operations: int
    # How many operations Typeship found in the complete Definition.
    total_operations: int
    reason: Union[Literal["anonymous", "free_plan"], str]
    # Where the cap is lifted.
    upgrade_url: str


class GenerationLimitsRead(_GenerationLimitsReadRequired, total=False):
    """Present when the generation was capped: by the free plan, or because the call was
    anonymous. Absent on uncapped generations.
    """
    # Anonymous calls only. Where to create an account.
    signup_url: str


class GenerationResultReadClaimVariant1(TypedDict):
    url: str
    # Format: date-time.
    expires_at: str


class _GenerationResultReadRequired(TypedDict):
    files: List[GeneratedFile]
    warnings: List[str]
    meta: GenerationMetaRead


class GenerationResultRead(_GenerationResultReadRequired, total=False):
    limits: GenerationLimitsRead
    # Anonymous, URL-sourced generations only. A link a signed-in person can open to turn this run
    # into a project in their organization (same Definition, Target, and config). Lasts seven days.
    # Null for inline Definitions; absent on keyed calls.
    claim: Optional[GenerationResultReadClaimVariant1]


class _UrlDefinitionInputRequired(TypedDict):
    # URL of an OpenAPI document, a GraphQL SDL file, or a GraphQL endpoint (introspected
    # automatically). Fetched server-side. Format: uri.
    url: str


class UrlDefinitionInput(_UrlDefinitionInputRequired, total=False):
    # Request headers for a protected URL. Sent on the document GET and GraphQL introspection POST,
    # never returned or retained by stateless generation.
    headers: Dict[str, str]


class InlineDefinitionInput(TypedDict):
    # Raw Definition text (OpenAPI JSON/YAML or GraphQL SDL). Up to 10MB.
    inline: str


DefinitionInput = Union[UrlDefinitionInput, InlineDefinitionInput]


GeneratorKind = Literal["typescript-sdk", "python-sdk", "go-sdk", "cli", "mcp"]


class GenerateRequestTarget(TypedDict):
    """Stateless generator descriptor; no persisted Target is created."""
    generator: GeneratorKind


class RetryTuning(TypedDict, total=False):
    """Retry behavior. Top-level fields adjust every operation; operations maps operationId
    or "METHOD /path" keys to per-operation overrides.
    """
    max_retries: int
    # Replaces the default retryable set (408, 429, 500, 502, 503, 504).
    statuses: List[int]
    initial_delay_ms: int
    max_delay_ms: int
    # Also retry non-idempotent methods (POST/PATCH).
    retry_non_idempotent: bool
    # Shorthand for max_retries 0.
    disabled: bool
    operations: Dict[str, RetryTuning]


class _PaginationRuleRequired(TypedDict):
    # Response field holding the item array.
    items_field: str


class PaginationRule(_PaginationRuleRequired, total=False):
    style: Literal["cursor", "cursorFromLastId", "page", "offset"]
    cursor_param: str
    next_cursor_field: str
    has_more_field: str
    id_field: str
    page_param: str
    offset_param: str
    limit_param: str


class GraphqlSettingsEnvironmentsItem(TypedDict):
    name: str
    # Format: uri.
    url: str


class GraphqlSettings(TypedDict, total=False):
    """What a GraphQL schema cannot say about itself. Ignored for OpenAPI specs."""
    # The URL every request is POSTed to; the generated client's default baseUrl. Defaults to the
    # URL the schema was fetched from. Without either, baseUrl is a required client option. Format:
    # uri.
    endpoint: str
    # Named endpoints (sandbox, production). Each becomes a client environment; the first is the
    # default unless endpoint is set.
    environments: List[GraphqlSettingsEnvironmentsItem]
    # How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs
    # (public key as username, private key as password); api_key sends a header named by
    # api_key_header; none generates no auth option.
    auth: Literal["bearer", "basic", "api_key", "none"]
    # Header carrying the key when auth is api_key. Required for that mode; Typeship does not invent
    # a vendor-specific header name.
    api_key_header: str
    # The API's name; drives the package and client names ("Acme" gives acme and AcmeClient).
    # Defaults to a name derived from the endpoint's host.
    title: str
    # JSON representation of each custom scalar, keyed by GraphQL scalar name. Unmapped scalars
    # generate as the language's untyped JSON value and produce a warning. Unmatched keys warn.
    scalars: Dict[str, Literal["string", "integer", "number", "boolean", "json"]]


class CliBehavior(TypedDict, total=False):
    """How the generated CLI behaves. Part of Config."""
    # Command users run, independent of how the CLI is distributed.
    command_name: Optional[str]
    # resource.method of a zero-argument GET that the generated CLI's whoami command calls.
    # Overrides auto-detection; a value that matches nothing is reported as a generation warning.
    whoami_operation: Optional[str]
    # OAuth client id baked into the generated CLI for device-flow login. Without it, login prompts
    # for a pasted credential.
    oauth_client_id: Optional[str]
    # Scopes requested during device-flow login. Include offline_access if the authorization server
    # gates refresh tokens behind it.
    oauth_scopes: List[str]
    # Audience sent with the device-authorization request, for authorization servers that require
    # one to issue API-valid access tokens.
    oauth_audience: Optional[str]
    # Opt in to a once-a-day registry check that prints an upgrade hint. Off by default; generated
    # code phones nobody unless this is enabled.
    update_notice: bool
    # Where the generated CLI's feedback command sends users. GitHub issues/new URLs get a prefilled
    # title and environment details.
    support_url: Optional[str]
    # Base URL of the browser-approval endpoint pair used by CLI login. The CLI keeps the verifier
    # and receives the credential directly; no key is pasted through a conversation.
    auth_url: Optional[str]
    # Hosted MCP endpoint installed by the generated CLI instead of launching the package's local
    # stdio server.
    mcp_url: Optional[str]
    # GitHub owner/name of the skills package the generated CLI offers to install during init.
    skills_repo: Optional[str]


class McpBehavior(TypedDict, total=False):
    """How the generated MCP server and the hosted endpoint behave. Part of Config."""
    # Stable official MCP registry name, independent of the server runtime.
    registry_name: Optional[str]
    # MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so
    # large APIs don't flood an agent's context window. Auto considers the serialized tool schemas,
    # switching near 10k tokens or above 100 operations.
    tool_mode: Literal["auto", "operations", "meta"]
    # Guidance appended to the MCP server's instructions, which agents read once when they connect
    # (server/discover): what to call first, conventions the spec does not state, what not to do.
    # Carried by the package's server and the hosted endpoint alike.
    instructions: Optional[str]
    # Hand-written MCP tool descriptions keyed by operationId or "METHOD /path". Each replaces the
    # text typeship derives for that operation (summary, first sentence, method and path,
    # deprecation and auth notes). For flows the spec cannot describe, such as a multi-step upload.
    # Keys that match no operation are reported as generation warnings.
    tool_descriptions: Dict[str, str]


class PackageBehavior(TypedDict, total=False):
    """Published-package metadata the API spec does not own. Repository is derived from each
    destination.
    """
    # Homepage written into registry metadata.
    homepage: Optional[str]
    # SPDX identifier written into registry metadata. Defaults to info.license.
    license: Optional[str]
    # Exact LICENSE file contents. Supply this for licences the engine does not build in; MIT is
    # built in when copyright is also set.
    license_text: Optional[str]
    # Copyright line used in generated license files.
    copyright: Optional[str]
    # Go identifier when the destination repository name is unsuitable.
    go_package_name: Optional[str]


class Config(TypedDict, total=False):
    """Everything Typeship needs beyond the Definition, in one object: generation
    customization (globals, retries, pagination) and how the generated tooling behaves
    (cli, mcp, package, docs_url). Plain configuration. Typeship never requires vendor
    extensions inside the Definition itself. Stateless generation also accepts GraphQL
    settings here; stored projects keep those settings on their Definition.
    """
    # Wire names of query/header parameters that become settable once on the generated client and
    # auto-apply to every operation that accepts them; per-call values win. Names that match nothing
    # are reported as generation warnings.
    globals: List[str]
    retries: RetryTuning
    # Per-operation pagination control, keyed by operationId or "METHOD /path". Unmatched keys are
    # reported as generation warnings.
    pagination: Dict[str, Union[PaginationRule, bool]]
    graphql: GraphqlSettings
    cli: CliBehavior
    mcp: McpBehavior
    package: PackageBehavior
    # The API's documentation site. Read through its llms.txt by the generated CLI's docs command,
    # the MCP server's docs tools, and the package's AGENTS.md. Defaults to the Definition's
    # externalDocs URL.
    docs_url: Optional[str]


class _GenerateRequestRequired(TypedDict):
    definition: DefinitionInput
    # Stateless generator descriptor; no persisted Target is created.
    target: GenerateRequestTarget


class GenerateRequest(_GenerateRequestRequired, total=False):
    # npm package or Python distribution override. Valid only for the TypeScript and Python SDK
    # targets.
    package_name: str
    # Go module path override. Valid only for the Go SDK. Linked projects derive this from the Go
    # destination repository by default.
    module_path: str
    config: Config


ListObjectRead = Literal["list"]


ProjectId = str


DefinitionId = str


class ProjectSummaryRead(TypedDict):
    """Lean Project identity returned by collection endpoints. Retrieve the Project or list
    its Targets for the complete aggregate.
    """
    id: ProjectId
    object: Literal["project"]
    name: str
    definition_id: DefinitionId
    auto_generate: bool
    # Format: date-time.
    created_at: str
    # Format: date-time.
    updated_at: str


class ProjectListRead(TypedDict):
    object: ListObjectRead
    data: List[ProjectSummaryRead]
    # Whether another page is available after this one.
    has_more: bool
    # Pass this value as cursor to retrieve the next page; null on the last page.
    next_cursor: Optional[str]


TargetId = str


class TargetReadVersionPolicy(TypedDict):
    mode: Literal["reviewed_semver"]
    pre1_breaking: Literal["minor"]


class _PaginationRuleReadRequired(TypedDict):
    # Response field holding the item array.
    items_field: str


class PaginationRuleRead(_PaginationRuleReadRequired, total=False):
    style: Union[Literal["cursor", "cursorFromLastId", "page", "offset"], str]
    cursor_param: str
    next_cursor_field: str
    has_more_field: str
    id_field: str
    page_param: str
    offset_param: str
    limit_param: str


class McpBehaviorRead(TypedDict, total=False):
    """How the generated MCP server and the hosted endpoint behave. Part of Config."""
    # Stable official MCP registry name, independent of the server runtime.
    registry_name: Optional[str]
    # MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so
    # large APIs don't flood an agent's context window. Auto considers the serialized tool schemas,
    # switching near 10k tokens or above 100 operations.
    tool_mode: Union[Literal["auto", "operations", "meta"], str]
    # Guidance appended to the MCP server's instructions, which agents read once when they connect
    # (server/discover): what to call first, conventions the spec does not state, what not to do.
    # Carried by the package's server and the hosted endpoint alike.
    instructions: Optional[str]
    # Hand-written MCP tool descriptions keyed by operationId or "METHOD /path". Each replaces the
    # text typeship derives for that operation (summary, first sentence, method and path,
    # deprecation and auth notes). For flows the spec cannot describe, such as a multi-step upload.
    # Keys that match no operation are reported as generation warnings.
    tool_descriptions: Dict[str, str]


class ProjectConfigRead(TypedDict, total=False):
    """Shared generated-client and tooling behavior for a stored Project. Every Target
    inherits these defaults. Target.config is merged over them for one Target; top-level
    values replace defaults while cli, mcp, and package merge by field. GraphQL-only
    source settings live on the Project's Definition and are rejected in both stored
    config scopes.
    """
    # Wire names of query/header parameters that become settable once on the generated client and
    # auto-apply to every operation that accepts them; per-call values win. Names that match nothing
    # are reported as generation warnings.
    globals: List[str]
    retries: RetryTuning
    # Per-operation pagination control, keyed by operationId or "METHOD /path". Unmatched keys are
    # reported as generation warnings.
    pagination: Dict[str, Union[PaginationRuleRead, bool]]
    cli: CliBehavior
    mcp: McpBehaviorRead
    package: PackageBehavior
    # The API's documentation site. Read through its llms.txt by the generated CLI's docs command,
    # the MCP server's docs tools, and the package's AGENTS.md. Defaults to the Definition's
    # externalDocs URL.
    docs_url: Optional[str]


DeliveryId = str


class RepositoryReferenceRead(TypedDict):
    # GitHub is the only launch provider; the field is stable for future adapters.
    provider: Union[Literal["github"], str]
    # Provider-native repository identity, opaque outside its adapter.
    identifier: str


class RepositoryDeliveryRead(TypedDict):
    id: DeliveryId
    object: Literal["delivery"]
    target_id: TargetId
    kind: Literal["repository"]
    state: Union[Literal["active", "disabled"], str]
    repository: RepositoryReferenceRead
    directory: Optional[str]
    package_name: Optional[str]
    module_path: Optional[str]
    # Format: date-time.
    created_at: str
    # Format: date-time.
    updated_at: str


class HostedMcpDeliveryRead(TypedDict):
    id: DeliveryId
    object: Literal["delivery"]
    target_id: TargetId
    kind: Literal["hosted_mcp"]
    state: Union[Literal["active", "disabled"], str]
    # Format: uri.
    url: Optional[str]
    # Format: date-time.
    created_at: str
    # Format: date-time.
    updated_at: str


DeliveryRead = Union[RepositoryDeliveryRead, HostedMcpDeliveryRead, Dict[str, Any]]


class TargetRead(TypedDict):
    id: TargetId
    object: Literal["target"]
    project_id: ProjectId
    definition_id: DefinitionId
    name: str
    generator: Union[GeneratorKindRead, str]
    state: Union[Literal["active", "disabled"], str]
    edition: str
    release_channel: Union[Literal["stable", "prerelease"], str]
    version_policy: TargetReadVersionPolicy
    current_version: str
    proposed_version: Optional[str]
    # Target-specific overrides merged over Project.config. GraphQL settings are Definition-owned
    # and never appear here.
    config: Optional[ProjectConfigRead]
    deliveries: List[DeliveryRead]
    # Format: date-time.
    created_at: str
    # Format: date-time.
    updated_at: str


class ProjectRead(TypedDict):
    id: ProjectId
    object: Literal["project"]
    name: str
    definition_id: DefinitionId
    # All configured Targets, including disabled Targets and their saved Deliveries.
    targets: List[TargetRead]
    # Flattened convenience view derived from the same Target bundles. Every Delivery retains
    # target_id so ownership is explicit.
    deliveries: List[DeliveryRead]
    # Regenerate when the Definition changes: on every push to the default branch for a repository
    # source, every 30 minutes for a URL source. Off by default: the first generation is always one
    # you asked for. Off means only "generate now" and POST /projects/{project_id}/generations
    # regenerate.
    auto_generate: bool
    # Whether the webhook relay is on, letting the generated CLI's webhooks listen command mint
    # relay sessions. Requires the cli target and Pro; turning the target off turns this off.
    relay_enabled: bool
    # Shared defaults inherited by every Target. A Target's config overrides these defaults; GraphQL
    # settings remain Definition-owned.
    config: Optional[ProjectConfigRead]
    # Format: date-time.
    created_at: str
    # When the project configuration last changed. Format: date-time.
    updated_at: str


class _UrlDefinitionSourceInputRequired(TypedDict):
    kind: Literal["url"]
    # URL of an OpenAPI document, GraphQL SDL file, or GraphQL endpoint. Format: uri.
    url: str


class UrlDefinitionSourceInput(_UrlDefinitionSourceInputRequired, total=False):
    # Request headers for a protected URL. Values are never returned or recorded in revision
    # history. When updating the same URL, omit headers to preserve the stored values or pass null
    # to remove them. Changing the URL without headers clears the old values so a credential is
    # never forwarded to a different source.
    headers: Optional[Dict[str, str]]


class RepositoryReference(TypedDict):
    # GitHub is the only launch provider; the field is stable for future adapters.
    provider: Literal["github"]
    # Provider-native repository identity, opaque outside its adapter.
    identifier: str


class RepositoryDefinitionSourceInput(TypedDict):
    kind: Literal["repository"]
    repository: RepositoryReference
    # Repository-relative Definition entrypoint.
    path: str


DefinitionSourceInput = Union[UrlDefinitionSourceInput, RepositoryDefinitionSourceInput]


class _DefinitionPatchRequired(TypedDict):
    op: Literal["set", "append", "remove", "rename"]
    # JSON-Pointer-style path. Pattern segments enable bulk fixes: * (any child), ** (any depth),
    # [key=value] (filter), e.g. /paths/**/parameters/[name=account_id]/schema/type. Renaming a
    # schema under /components/schemas also rewrites its $refs.
    path: str


class DefinitionPatch(_DefinitionPatchRequired, total=False):
    """A fix applied to the resolved Definition before generation. Paths are JSON Pointers
    into the document. A patch whose target no longer exists is skipped and reported as a
    warning on the generation, never silently.
    """
    # set only; the replacement value.
    value: Any
    # rename only; the new key name.
    to: Optional[str]
    reason: Optional[str]


class _DiagnosticSuppressionRequired(TypedDict):
    rule_id: str
    # The reviewed product decision behind this exception.
    reason: str


class DiagnosticSuppression(_DiagnosticSuppressionRequired, total=False):
    # Exact schema coordinate. Omit only to suppress every occurrence of the rule.
    path: str


class DiagnosticPolicy(TypedDict):
    """Source pull-request enforcement threshold, new-versus-complete baseline, and
    explicitly reviewed rule or location exceptions.
    """
    # Severity threshold that fails the API change review check.
    fail_on: Literal["never", "error", "warning"]
    # Enforce only occurrences introduced by the proposed source change.
    only_new: bool
    suppressions: List[DiagnosticSuppression]


class _DefinitionFieldsRequired(TypedDict):
    source: DefinitionSourceInput


class DefinitionFields(_DefinitionFieldsRequired, total=False):
    patches: List[DefinitionPatch]
    # GraphQL-only endpoint, auth, environment, title, and scalar settings.
    graphql: Optional[GraphqlSettings]
    diagnostic_policy: DiagnosticPolicy


class ProjectConfig(TypedDict, total=False):
    """Shared generated-client and tooling behavior for a stored Project. Every Target
    inherits these defaults. Target.config is merged over them for one Target; top-level
    values replace defaults while cli, mcp, and package merge by field. GraphQL-only
    source settings live on the Project's Definition and are rejected in both stored
    config scopes.
    """
    # Wire names of query/header parameters that become settable once on the generated client and
    # auto-apply to every operation that accepts them; per-call values win. Names that match nothing
    # are reported as generation warnings.
    globals: List[str]
    retries: RetryTuning
    # Per-operation pagination control, keyed by operationId or "METHOD /path". Unmatched keys are
    # reported as generation warnings.
    pagination: Dict[str, Union[PaginationRule, bool]]
    cli: CliBehavior
    mcp: McpBehavior
    package: PackageBehavior
    # The API's documentation site. Read through its llms.txt by the generated CLI's docs command,
    # the MCP server's docs tools, and the package's AGENTS.md. Defaults to the Definition's
    # externalDocs URL.
    docs_url: Optional[str]


class _RepositoryDeliveryInputRequired(TypedDict):
    kind: Literal["repository"]
    repository: RepositoryReference


class RepositoryDeliveryInput(_RepositoryDeliveryInputRequired, total=False):
    directory: Optional[str]
    # npm or Python registry identity where applicable.
    package_name: Optional[str]
    # Explicit Go module path where applicable.
    module_path: Optional[str]


class HostedMcpDeliveryInput(TypedDict):
    kind: Literal["hosted_mcp"]


DeliveryInput = Union[RepositoryDeliveryInput, HostedMcpDeliveryInput]


class _InitialTargetFieldsRequired(TypedDict):
    name: str
    generator: GeneratorKind


class InitialTargetFields(_InitialTargetFieldsRequired, total=False):
    state: Literal["active", "disabled"]
    edition: str
    release_channel: Literal["stable", "prerelease"]
    proposed_version: Optional[str]
    # Target-specific overrides merged over Project.config. GraphQL settings are rejected here and
    # belong to the Definition.
    config: Optional[ProjectConfig]
    deliveries: List[DeliveryInput]


class _CreateProjectRequestRequired(TypedDict):
    name: str
    definition: DefinitionFields
    # Initial first-class Targets. More than one may use the same generator with different
    # identities or Deliveries.
    targets: List[InitialTargetFields]


class CreateProjectRequest(_CreateProjectRequestRequired, total=False):
    # Whether Typeship should regenerate automatically when the source changes.
    auto_generate: bool
    # Enable webhook relay sessions. Requires the CLI target and Pro.
    relay_enabled: bool
    # Shared defaults inherited by every Target. GraphQL settings belong in definition.graphql.
    config: Optional[ProjectConfig]


class DeletedProjectRead(TypedDict):
    id: ProjectId
    object: Literal["project"]
    deleted: Literal[True]


class UpdateProjectRequest(TypedDict, total=False):
    name: str
    auto_generate: bool
    # Enable webhook relay sessions. Requires the CLI target and Pro.
    relay_enabled: bool
    # Replaces the Project's shared Target defaults. Send null to clear them.
    config: Optional[ProjectConfig]


DefinitionRevisionId = str


class _DiagnosticLocationRequired(TypedDict):
    # JSON Pointer for OpenAPI, or schema coordinate for GraphQL.
    path: str


class DiagnosticLocation(_DiagnosticLocationRequired, total=False):
    """One exact place where a Diagnostic rule found evidence."""
    # Source document coordinate when the Definition contains multiple files.
    document: str
    # Human-readable operation coordinate when the location belongs to an operation.
    operation: str
    # Occurrence-specific evidence. This is not a remediation instruction.
    evidence: str


class _DefinitionPatchReadRequired(TypedDict):
    op: Union[Literal["set", "append", "remove", "rename"], str]
    # JSON-Pointer-style path. Pattern segments enable bulk fixes: * (any child), ** (any depth),
    # [key=value] (filter), e.g. /paths/**/parameters/[name=account_id]/schema/type. Renaming a
    # schema under /components/schemas also rewrites its $refs.
    path: str


class DefinitionPatchRead(_DefinitionPatchReadRequired, total=False):
    """A fix applied to the resolved Definition before generation. Paths are JSON Pointers
    into the document. A patch whose target no longer exists is skipped and reported as a
    warning on the generation, never silently.
    """
    # set only; the replacement value.
    value: Any
    # rename only; the new key name.
    to: Optional[str]
    reason: Optional[str]


class _DiagnosticFixReadRequired(TypedDict):
    # Concise action for the API author.
    title: str
    # spec_patch is an exact OpenAPI edit Typeship can derive; source_edit requires author intent or
    # a lossless GraphQL source edit.
    kind: Union[Literal["spec_patch", "source_edit"], str]


class DiagnosticFixRead(_DiagnosticFixReadRequired, total=False):
    """A reviewable remediation that does not invent API behavior."""
    # Exact patches when kind is spec_patch.
    patches: List[DefinitionPatchRead]
    # Source-level guidance when an exact patch would invent intent.
    instructions: str


class _DiagnosticReadRequired(TypedDict):
    # Stable rule identifier for automation and suppressions.
    id: str
    # Whether the rule reports invalid behavior, material risk, or an improvement.
    severity: Union[Literal["error", "warning", "suggestion"], str]
    # Product dimension affected by the diagnostic.
    category: Union[Literal["correctness", "sdk_ergonomics", "agent_usability", "safety"], str]
    # Concise statement of the root cause.
    title: str
    # What the API author should change.
    description: str
    # Why consumers of generated SDK, CLI, or MCP surfaces care.
    impact: str
    # Public surfaces affected by the root cause.
    surfaces: List[Union[Literal["api", "sdk", "cli", "mcp"], str]]
    # All affected coordinates, kept under one grouped diagnostic.
    locations: List[DiagnosticLocation]
    # Grounded instructions an agent can use to edit the source. The brief preserves existing
    # behavior and requires owner input when the contract cannot prove the missing product decision.
    authoring_brief: str


class DiagnosticRead(_DiagnosticReadRequired, total=False):
    """Every occurrence of one stable Diagnostic rule, grouped into one decision."""
    fix: DiagnosticFixRead


class DiagnosticPolicyRead(TypedDict):
    """Source pull-request enforcement threshold, new-versus-complete baseline, and
    explicitly reviewed rule or location exceptions.
    """
    # Severity threshold that fails the API change review check.
    fail_on: Union[Literal["never", "error", "warning"], str]
    # Enforce only occurrences introduced by the proposed source change.
    only_new: bool
    suppressions: List[DiagnosticSuppression]


class DiagnosticReferenceRead(TypedDict):
    """Compact rule and location reference; full guidance appears once in diagnostics."""
    rule_id: str
    severity: Union[Literal["error", "warning", "suggestion"], str]
    title: str
    locations: List[DiagnosticLocation]


class DiagnosticEvaluationRead(TypedDict):
    state: Union[Literal["pass", "fail"], str]
    blocking: List[DiagnosticReferenceRead]
    considered_occurrences: int
    suppressed_occurrences: int


class DiagnosticDeltaRead(TypedDict):
    added: List[DiagnosticReferenceRead]
    resolved: List[DiagnosticReferenceRead]
    baseline_definition_revision_id: Optional[DefinitionRevisionId]


class DiagnosticReportRead(TypedDict):
    """Deterministic Diagnostics for one immutable Definition Revision after existing
    patches. No model-generated facts or silent edits.
    """
    object: Literal["diagnostic_report"]
    # Contract format Typeship analyzed.
    format: Union[Literal["openapi", "graphql"], str]
    project_id: ProjectId
    definition_revision_id: DefinitionRevisionId
    # SHA-256 digest of the immutable raw source revision.
    source_sha256: str
    # SHA-256 digest after applying the Definition's current patches.
    analyzed_sha256: str
    # Loud misses or conflicts from the Definition's existing patches.
    patch_diagnostics: List[str]
    summary: DiagnosticSummary
    # Stable grouped diagnostics, ordered by severity and rule identifier.
    diagnostics: List[DiagnosticRead]
    policy: DiagnosticPolicyRead
    evaluation: DiagnosticEvaluationRead
    delta: DiagnosticDeltaRead


class _DiagnosticRemediationReadRequired(TypedDict):
    object: Literal["diagnostic_remediation"]
    kind: Union[Literal["overlay", "source_review"], str]
    patches_applied: int


class DiagnosticRemediationRead(_DiagnosticRemediationReadRequired, total=False):
    # Source pull request for repository projects; absent for URL overlays. Format: uri.
    review_url: Optional[str]


class DiagnosticRemediationRequest(TypedDict):
    # Stable IDs of current diagnostics whose exact patches should be reviewed and applied.
    diagnostic_ids: List[str]


class RepositoryHealthIssueRead(TypedDict):
    code: Union[
        Literal[
            "connection_missing",
            "definition_unreadable",
            "contents_write_missing",
            "review_write_missing",
            "breaking_acknowledgement_missing",
            "provider_unavailable",
        ],
        str,
    ]
    message: str


class _RepositoryHealthReadRequired(TypedDict):
    repository: RepositoryReferenceRead
    roles: List[Union[Literal["source", "destination"], str]]
    status: Union[Literal["ready", "action_required"], str]
    issues: List[RepositoryHealthIssueRead]


class RepositoryHealthRead(_RepositoryHealthReadRequired, total=False):
    default_branch: str
    capabilities: List[str]
    # Whether a source repository has the optional typeship:breaking-approved policy label. Null
    # when the repository is not a source or labels could not be read.
    breaking_acknowledgement: Optional[bool]
    definition: Union[Literal["readable", "missing"], str]


class RepositoryIntegrationHealthReadRequiredChecks(TypedDict):
    source: List[str]
    destination: List[str]


class RepositoryEventHealthRead(TypedDict):
    provider: str
    id: str
    event: str
    status: Union[Literal["queued", "processing", "succeeded", "failed", "superseded"], str]
    error: Optional[str]
    # Format: date-time.
    created_at: str


class RepositoryIntegrationHealthRead(TypedDict):
    object: Literal["repository_integration_health"]
    project_id: ProjectId
    status: Union[Literal["ready", "action_required"], str]
    repositories: List[RepositoryHealthRead]
    required_checks: RepositoryIntegrationHealthReadRequiredChecks
    last_event: Optional[RepositoryEventHealthRead]


GenerationId = str


class FileStub(TypedDict):
    path: str
    bytes: int


class GenerationReadProvenance(TypedDict):
    # Pinned generator contract edition.
    generator_edition: str
    # Exact engine build identifier used for replay and support.
    engine_build: str
    # Immutable effective Target configuration used by this run; source credentials are never
    # included.
    resolved_config: Optional[Dict[str, Any]]
    config_hash: Optional[str]
    # Resolved generator and entitlement plan used to select the emitted public surface.
    surface_plan: Optional[Dict[str, Any]]
    surface_plan_hash: Optional[str]
    entitlement_cap: Optional[int]
    package_version: Optional[str]


class _GenerationReadRequired(TypedDict):
    id: GenerationId
    object: Literal["generation"]
    project_id: ProjectId
    definition_revision_id: Optional[DefinitionRevisionId]
    status: Union[Literal["succeeded", "failed"], str]
    trigger: Union[Literal["manual", "webhook", "poll", "preview"], str]
    # Persisted Target identity. Null only for stateless generation.
    target_id: Optional[TargetId]
    # Resolved generator implementation; provenance rather than resource identity.
    generator: Union[GeneratorKindRead, str]
    provenance: GenerationReadProvenance
    # Null only for a failed or legacy generation that produced no metadata.
    meta: Optional[GenerationMetaRead]
    warnings: List[str]
    error: Optional[str]
    # Format: date-time.
    created_at: str


class GenerationRead(_GenerationReadRequired, total=False):
    # Present and true when the generated target was too large to inline; files_index lists paths,
    # fetched one at a time via GET /generations/{generation_id}/file.
    files_omitted: bool
    files_index: List[FileStub]
    # Present on retrieve and create; omitted in lists.
    files: List[GeneratedFile]


class GenerationListRead(TypedDict):
    object: ListObjectRead
    data: List[GenerationRead]
    # Whether another page is available after this one.
    has_more: bool
    # Pass this value as cursor to retrieve the next page; null on the last page.
    next_cursor: Optional[str]


class GenerationFailureRead(TypedDict):
    """A selected target that did not generate in a multi-target run."""
    target_id: TargetId
    generator: Union[GeneratorKindRead, str]
    status: Literal["failed"]
    error: str


class GenerationBatchRead(TypedDict):
    data: List[Union[GenerationRead, GenerationFailureRead]]


class UrlDefinitionSourceRead(TypedDict):
    kind: Literal["url"]
    # URL fetched for every generation. Format: uri.
    url: str
    # Whether Typeship has stored write-only request headers for this URL.
    headers_configured: bool


class RepositoryDefinitionSourceRead(TypedDict):
    kind: Literal["repository"]
    repository: RepositoryReferenceRead
    # Repository-relative Definition entrypoint.
    path: str


DefinitionSourceRead = Union[
    UrlDefinitionSourceRead,
    RepositoryDefinitionSourceRead,
    Dict[str, Any],
]


class GraphqlSettingsReadEnvironmentsItem(TypedDict):
    name: str
    # Format: uri.
    url: str


class GraphqlSettingsRead(TypedDict, total=False):
    """What a GraphQL schema cannot say about itself. Ignored for OpenAPI specs."""
    # The URL every request is POSTed to; the generated client's default baseUrl. Defaults to the
    # URL the schema was fetched from. Without either, baseUrl is a required client option. Format:
    # uri.
    endpoint: str
    # Named endpoints (sandbox, production). Each becomes a client environment; the first is the
    # default unless endpoint is set.
    environments: List[GraphqlSettingsReadEnvironmentsItem]
    # How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs
    # (public key as username, private key as password); api_key sends a header named by
    # api_key_header; none generates no auth option.
    auth: Union[Literal["bearer", "basic", "api_key", "none"], str]
    # Header carrying the key when auth is api_key. Required for that mode; Typeship does not invent
    # a vendor-specific header name.
    api_key_header: str
    # The API's name; drives the package and client names ("Acme" gives acme and AcmeClient).
    # Defaults to a name derived from the endpoint's host.
    title: str
    # JSON representation of each custom scalar, keyed by GraphQL scalar name. Unmapped scalars
    # generate as the language's untyped JSON value and produce a warning. Unmatched keys warn.
    scalars: Dict[str, Union[Literal["string", "integer", "number", "boolean", "json"], str]]


class DefinitionRead(TypedDict):
    id: DefinitionId
    object: Literal["definition"]
    project_id: ProjectId
    source: DefinitionSourceRead
    format: Optional[Union[Literal["openapi", "graphql"], str]]
    patches: List[DefinitionPatchRead]
    graphql: Optional[GraphqlSettingsRead]
    diagnostic_policy: DiagnosticPolicyRead
    latest_revision_id: Optional[DefinitionRevisionId]
    # Format: date-time.
    created_at: str
    # Format: date-time.
    updated_at: str


class DefinitionUpdateRequest(TypedDict, total=False):
    source: DefinitionSourceInput
    patches: List[DefinitionPatch]
    graphql: Optional[GraphqlSettings]
    diagnostic_policy: DiagnosticPolicy


class TargetListRead(TypedDict):
    object: ListObjectRead
    data: List[TargetRead]
    has_more: bool
    next_cursor: Optional[str]


class _TargetFieldsRequired(TypedDict):
    name: str
    definition_id: DefinitionId
    generator: GeneratorKind


class TargetFields(_TargetFieldsRequired, total=False):
    state: Literal["active", "disabled"]
    edition: str
    release_channel: Literal["stable", "prerelease"]
    # Optional larger or prerelease SemVer for the next reviewed release.
    proposed_version: Optional[str]
    # Target-specific overrides merged over Project.config. GraphQL settings are rejected here and
    # belong to the Definition.
    config: Optional[ProjectConfig]
    deliveries: List[DeliveryInput]


class TargetUpdateRequest(TypedDict, total=False):
    name: str
    state: Literal["active", "disabled"]
    edition: str
    release_channel: Literal["stable", "prerelease"]
    proposed_version: Optional[str]
    # Target-specific overrides merged over Project.config. GraphQL settings are rejected here and
    # belong to the Definition.
    config: Optional[ProjectConfig]
    deliveries: List[DeliveryInput]


TargetReleaseId = str


class TargetReleaseRead(TypedDict):
    id: TargetReleaseId
    object: Literal["target_release"]
    target_id: TargetId
    generation_id: GenerationId
    # Immutable package version released from this Target.
    version: str
    channel: Union[Literal["stable", "prerelease"], str]
    # Delivery provider that accepted the release.
    provider: str
    repository: Optional[RepositoryReferenceRead]
    definition_revision_id: Optional[DefinitionRevisionId]
    # Immutable provider-native revision that was merged or published.
    delivery_revision: str
    # Format: date-time.
    created_at: str


class TargetReleaseListRead(TypedDict):
    object: ListObjectRead
    data: List[TargetReleaseRead]
    has_more: bool
    next_cursor: Optional[str]


DefinitionDocumentId = str


class DefinitionDocumentRead(TypedDict):
    id: DefinitionDocumentId
    role: Union[Literal["entrypoint", "reference"], str]
    # Repository-relative path or same-origin URL captured in this revision.
    coordinate: str
    sha256: str
    size_bytes: int


class UrlDefinitionRevisionSourceRead(TypedDict):
    kind: Literal["url"]
    # Format: uri.
    url: str


class _RepositoryDefinitionRevisionSourceReadRequired(TypedDict):
    kind: Literal["repository"]
    repository: RepositoryReferenceRead
    # Repository-relative Definition entrypoint path.
    path: str


class RepositoryDefinitionRevisionSourceRead(
    _RepositoryDefinitionRevisionSourceReadRequired,
    total=False,
):
    # Git ref resolved for this revision, when recorded.
    ref: Optional[str]
    # Exact Git commit consumed, when recorded.
    commit_sha: Optional[str]


DefinitionRevisionSourceRead = Union[
    UrlDefinitionRevisionSourceRead,
    RepositoryDefinitionRevisionSourceRead,
    Dict[str, Any],
]


class _DefinitionRevisionReadRequired(TypedDict):
    id: DefinitionRevisionId
    object: Literal["definition_revision"]
    project_id: ProjectId
    definition_id: DefinitionId
    format: Union[Literal["openapi", "graphql"], str]
    document_count: int
    # SHA-256 digest of every document coordinate, digest, and size in the resolved graph.
    sha256: str
    # Total bytes across all source documents.
    size_bytes: int
    # Origin recorded when this immutable revision was created.
    source: Optional[DefinitionRevisionSourceRead]
    # Format: date-time.
    created_at: str


class DefinitionRevisionRead(_DefinitionRevisionReadRequired, total=False):
    # Present on retrieve; list responses use document_count.
    documents: List[DefinitionDocumentRead]


class DefinitionRevisionListRead(TypedDict):
    object: ListObjectRead
    data: List[DefinitionRevisionRead]
    # Whether another page is available after this one.
    has_more: bool
    # Pass this value as cursor to retrieve the next page; null on the last page.
    next_cursor: Optional[str]


class AccountRead(TypedDict):
    """The organization an API key belongs to. Members share its projects, keys, and plan;
    sign-in identity is not part of the API.
    """
    id: str
    object: Literal["account"]
    # The organization's display name.
    name: str
    plan: Union[Literal["free", "pro", "enterprise"], str]
    # Format: date-time.
    created_at: str


class ApiKeyRead(TypedDict):
    id: str
    object: Literal["api_key"]
    name: str
    # Last four characters of the secret; the secret itself is never stored.
    last4: str
    revoked: bool
    # Format: date-time.
    last_used_at: Optional[str]
    # Format: date-time.
    created_at: str


class ApiKeyListRead(TypedDict):
    object: ListObjectRead
    data: List[ApiKeyRead]
    # Whether another page is available after this one.
    has_more: bool
    # Pass this value as cursor to retrieve the next page; null on the last page.
    next_cursor: Optional[str]


__all__ = [
    "GeneratedFile",
    "GeneratorKindRead",
    "DiagnosticSummary",
    "GenerationMetaReadDiagnostics",
    "GenerationMetaRead",
    "GenerationLimitsRead",
    "GenerationResultReadClaimVariant1",
    "GenerationResultRead",
    "UrlDefinitionInput",
    "InlineDefinitionInput",
    "DefinitionInput",
    "GeneratorKind",
    "GenerateRequestTarget",
    "RetryTuning",
    "PaginationRule",
    "GraphqlSettingsEnvironmentsItem",
    "GraphqlSettings",
    "CliBehavior",
    "McpBehavior",
    "PackageBehavior",
    "Config",
    "GenerateRequest",
    "ListObjectRead",
    "ProjectId",
    "DefinitionId",
    "ProjectSummaryRead",
    "ProjectListRead",
    "TargetId",
    "TargetReadVersionPolicy",
    "PaginationRuleRead",
    "McpBehaviorRead",
    "ProjectConfigRead",
    "DeliveryId",
    "RepositoryReferenceRead",
    "RepositoryDeliveryRead",
    "HostedMcpDeliveryRead",
    "DeliveryRead",
    "TargetRead",
    "ProjectRead",
    "UrlDefinitionSourceInput",
    "RepositoryReference",
    "RepositoryDefinitionSourceInput",
    "DefinitionSourceInput",
    "DefinitionPatch",
    "DiagnosticSuppression",
    "DiagnosticPolicy",
    "DefinitionFields",
    "ProjectConfig",
    "RepositoryDeliveryInput",
    "HostedMcpDeliveryInput",
    "DeliveryInput",
    "InitialTargetFields",
    "CreateProjectRequest",
    "DeletedProjectRead",
    "UpdateProjectRequest",
    "DefinitionRevisionId",
    "DiagnosticLocation",
    "DefinitionPatchRead",
    "DiagnosticFixRead",
    "DiagnosticRead",
    "DiagnosticPolicyRead",
    "DiagnosticReferenceRead",
    "DiagnosticEvaluationRead",
    "DiagnosticDeltaRead",
    "DiagnosticReportRead",
    "DiagnosticRemediationRead",
    "DiagnosticRemediationRequest",
    "RepositoryHealthIssueRead",
    "RepositoryHealthRead",
    "RepositoryIntegrationHealthReadRequiredChecks",
    "RepositoryEventHealthRead",
    "RepositoryIntegrationHealthRead",
    "GenerationId",
    "FileStub",
    "GenerationReadProvenance",
    "GenerationRead",
    "GenerationListRead",
    "GenerationFailureRead",
    "GenerationBatchRead",
    "UrlDefinitionSourceRead",
    "RepositoryDefinitionSourceRead",
    "DefinitionSourceRead",
    "GraphqlSettingsReadEnvironmentsItem",
    "GraphqlSettingsRead",
    "DefinitionRead",
    "DefinitionUpdateRequest",
    "TargetListRead",
    "TargetFields",
    "TargetUpdateRequest",
    "TargetReleaseId",
    "TargetReleaseRead",
    "TargetReleaseListRead",
    "DefinitionDocumentId",
    "DefinitionDocumentRead",
    "UrlDefinitionRevisionSourceRead",
    "RepositoryDefinitionRevisionSourceRead",
    "DefinitionRevisionSourceRead",
    "DefinitionRevisionRead",
    "DefinitionRevisionListRead",
    "AccountRead",
    "ApiKeyRead",
    "ApiKeyListRead",
]
