"""typeship — API types.

Generated by typeship — https://typeship.dev — do not edit by hand.
"""
from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union


class GeneratedFile(TypedDict):
    # Repo-relative path inside the generated package.
    path: str
    content: str


OutputId = Literal["typescript-sdk", "python-sdk", "go-sdk", "cli", "mcp"]


class FileStub(TypedDict):
    path: str
    bytes: int


class _GenerationRequired(TypedDict):
    id: str
    object: Literal["generation"]
    status: Literal["succeeded", "failed"]
    trigger: Literal["manual", "webhook", "poll", "preview"]
    # Format: date-time.
    created_at: str


class Generation(_GenerationRequired, total=False):
    # Present and true when the generated output was too large to inline; files_index lists paths, fetched one at a time via GET /generations/{generation_id}/file.
    files_omitted: bool
    files_index: List[FileStub]
    project_id: Optional[str]
    # Language this run generated. Null on generations recorded before projects had a language axis.
    language: Optional[Literal["typescript", "python", "go"]]
    meta: GenerationMeta
    warnings: List[str]
    # Present on retrieve and create; omitted in lists.
    files: List[GeneratedFile]
    error: Optional[str]


class _GenerationMetaRequired(TypedDict):
    title: str
    version: str
    # Detected spec version, "2.0", "3.0", or "3.1".
    oas_version: str
    package_name: str
    client_name: str
    # Customer-selected outputs present in this delivery package.
    outputs: List[OutputId]


class GenerationMeta(_GenerationMetaRequired, total=False):
    spec_format: Literal["openapi", "graphql"]
    # True when the input was Swagger 2.0 and was converted.
    converted: bool
    resource_count: int
    operation_count: int
    schema_count: int
    paginated_operation_count: int
    # Operations beyond the plan's endpoint allowance, not generated.
    omitted_operation_count: int
    # Pull request opened by this regeneration, when one was.
    pr_url: Optional[str]
    pr_number: Optional[int]
    # Why the configured destination pull request was not opened. Generation itself still succeeded; fix this action and regenerate.
    pr_error: str
    # Markdown changelog entry for this regeneration, from the API surface diff. Absent on a first generation or when nothing changed.
    changelog: str
    # Breaking changes in the diff; removed methods and fields, changed types, inputs that became required.
    breaking_count: int
    # What the diff was measured against; "destination" means the .typeship/surface.json merged in the destination repository.
    baseline: Literal["destination", "last-generation", "none"]
    # The typeship/semver verdict on the regeneration pull request; failure means breaking changes without a major version bump.
    semver: Literal["success", "failure"]
    # The verdict in one line, as the commit status describes it.
    semver_note: str
    # The package version the destination had before this regeneration.
    previous_version: str
    file_count: int
    total_lines: int


class _GenerationLimitsRequired(TypedDict):
    # How many operations this generation was allowed to include.
    max_operations: int
    # How many operations in the spec were left out.
    omitted_operations: int
    reason: Literal["anonymous", "free_plan"]
    # Where the cap is lifted.
    upgrade_url: str


class GenerationLimits(_GenerationLimitsRequired, total=False):
    """Present when the generation was capped: by the free plan, or because the call was anonymous. Absent on uncapped generations."""
    # Anonymous calls only. Where to create an account.
    signup_url: str


class GenerationResultClaimVariant1(TypedDict):
    url: str
    # Format: date-time.
    expires_at: str


class _GenerationResultRequired(TypedDict):
    files: List[GeneratedFile]
    warnings: List[str]
    meta: GenerationMeta


class GenerationResult(_GenerationResultRequired, total=False):
    limits: GenerationLimits
    # Anonymous, URL-sourced generations only. A link a signed-in person can open to turn this run into a project in their organization (same spec, outputs, and config). Lasts seven days. Null for inline specs; absent on keyed calls.
    claim: Optional[GenerationResultClaimVariant1]


class SpecInput(TypedDict, total=False):
    """The spec to generate from. Provide exactly one of url or inline."""
    # Publicly reachable URL of an OpenAPI document, a GraphQL SDL file, or a GraphQL endpoint (introspected automatically). Fetched server-side.
    url: str
    # Raw spec text (OpenAPI JSON/YAML or GraphQL SDL). Up to 10MB.
    inline: str


class RetryTuning(TypedDict, total=False):
    """Retry behavior. Top-level fields adjust every operation; operations maps operationId or "METHOD /path" keys to per-operation overrides."""
    max_retries: int
    # Replaces the default retryable set (408, 429, 500, 502, 503, 504).
    statuses: List[int]
    initial_delay_ms: int
    max_delay_ms: int
    # Also retry non-idempotent methods (POST/PATCH).
    retry_non_idempotent: bool
    # Shorthand for max_retries 0.
    disabled: bool
    operations: Dict[str, RetryTuning]


class _PaginationRuleRequired(TypedDict):
    # Response field holding the item array.
    items_field: str


class PaginationRule(_PaginationRuleRequired, total=False):
    style: Literal["cursor", "cursorFromLastId", "page", "offset"]
    cursor_param: str
    next_cursor_field: str
    has_more_field: str
    id_field: str
    page_param: str
    offset_param: str
    limit_param: str


class GraphqlSettingsEnvironmentsItem(TypedDict):
    name: str
    # Format: uri.
    url: str


class GraphqlSettings(TypedDict, total=False):
    """What a GraphQL schema cannot say about itself. Ignored for OpenAPI specs."""
    # The URL every request is POSTed to; the generated client's default baseUrl. Defaults to the URL the schema was fetched from. Without either, baseUrl is a required client option. Format: uri.
    endpoint: str
    # Named endpoints (sandbox, production). Each becomes a client environment; the first is the default unless endpoint is set.
    environments: List[GraphqlSettingsEnvironmentsItem]
    # How requests authenticate. bearer sends Authorization: Bearer; basic is for key-pair APIs (public key as username, private key as password); api_key sends a header named by api_key_header; none generates no auth option.
    auth: Literal["bearer", "basic", "api_key", "none"]
    # Header carrying the key when auth is api_key. Default X-API-Key.
    api_key_header: str
    # The API's name; drives the package and client names ("Braintree" gives braintree and BraintreeClient). Defaults to a name derived from the endpoint's host.
    title: str


class CliBehavior(TypedDict, total=False):
    """How the generated CLI behaves. Part of Config."""
    # resource.method of a zero-argument GET that the generated CLI's whoami command calls. Overrides auto-detection; a value that matches nothing is reported as a generation warning.
    whoami_operation: Optional[str]
    # OAuth client id baked into the generated CLI for device-flow login. Without it, login prompts for a pasted credential.
    oauth_client_id: Optional[str]
    # Scopes requested during device-flow login. Include offline_access if the authorization server gates refresh tokens behind it.
    oauth_scopes: List[str]
    # Audience sent with the device-authorization request, for authorization servers that require one to issue API-valid access tokens.
    oauth_audience: Optional[str]
    # Opt in to a once-a-day registry check that prints an upgrade hint. Off by default; generated code phones nobody unless this is enabled.
    update_notice: bool
    # Where the generated CLI's feedback command sends users. GitHub issues/new URLs get a prefilled title and environment details.
    support_url: Optional[str]
    # Base URL of the browser-approval endpoint pair used by CLI login. The CLI keeps the verifier and receives the credential directly; no key is pasted through a conversation.
    auth_url: Optional[str]
    # Hosted MCP endpoint installed by the generated CLI instead of launching the package's local stdio server.
    mcp_url: Optional[str]
    # GitHub owner/name of the skills package the generated CLI offers to install during init.
    skills_repo: Optional[str]


class McpBehavior(TypedDict, total=False):
    """How the generated MCP server and the hosted endpoint behave. Part of Config."""
    # MCP tool shape. meta collapses per-operation tools into search_docs, read_docs, and execute so large APIs don't flood an agent's context window; auto switches to meta above 100 operations.
    tool_mode: Literal["auto", "operations", "meta"]
    # Guidance appended to the MCP server's instructions, which agents read once when they connect (server/discover): what to call first, conventions the spec does not state, what not to do. Carried by the package's server and the hosted endpoint alike.
    instructions: Optional[str]
    # Hand-written MCP tool descriptions keyed by operationId or "METHOD /path". Each replaces the text typeship derives for that operation (summary, first sentence, method and path, deprecation and auth notes). For flows the spec cannot describe, such as a multi-step upload. Keys that match no operation are reported as generation warnings.
    tool_descriptions: Dict[str, str]


class PackageBehavior(TypedDict, total=False):
    """Published-package metadata the API spec does not own. Use version only when the client intentionally releases on a different cadence from info.version; repository is derived from each destination."""
    # Semantic version for the generated packages. Defaults to info.version.
    version: Optional[str]
    # Homepage written into registry metadata.
    homepage: Optional[str]
    # Copyright line used in generated license files.
    copyright: Optional[str]
    # CLI executable name when it differs from the npm package name.
    bin_name: Optional[str]
    # Go identifier when the destination repository name is unsuitable.
    go_package_name: Optional[str]
    # Official MCP registry name written into package.json.
    mcp_name: Optional[str]


class Config(TypedDict, total=False):
    """Everything typeship needs beyond the spec, in one object: generation customization (globals, retries, pagination) and how the generated tooling behaves (cli, mcp, package, docs_url). Plain configuration. typeship never requires vendor extensions inside the spec itself. The same shape is accepted on a project and on POST /generate."""
    # Wire names of query/header parameters that become settable once on the generated client and auto-apply to every operation that accepts them; per-call values win. Names that match nothing are reported as generation warnings.
    globals: List[str]
    retries: RetryTuning
    # Per-operation pagination control, keyed by operationId or "METHOD /path". Unmatched keys are reported as generation warnings.
    pagination: Dict[str, Union[PaginationRule, bool]]
    graphql: GraphqlSettings
    cli: CliBehavior
    mcp: McpBehavior
    package: PackageBehavior
    # The API's documentation site. Read through its llms.txt by the generated CLI's docs command, the MCP server's docs tools, and the package's AGENTS.md. Defaults to the spec's externalDocs URL.
    docs_url: Optional[str]


class _SourceRequired(TypedDict):
    kind: Literal["url", "repo"]


class Source(_SourceRequired, total=False):
    """Where the project's spec lives."""
    # kind url. Fetched server-side for every generation.
    url: Optional[str]
    # kind repo, "owner/name". Watched via the GitHub App.
    repo: Optional[str]
    # Path of the spec file inside the repository.
    path: Optional[str]


class Destination(TypedDict, total=False):
    """Where regeneration pull requests land."""
    # Defaults to the source repository when the source is a repo.
    repo: Optional[str]
    # Directory the generated package is written to.
    directory: Optional[str]


class PackageDelivery(TypedDict, total=False):
    """Registry identity and reviewed pull-request destination for one delivery package."""
    # npm package name, Python distribution name, or Go module path. Null derives a name from the API title.
    name: Optional[str]
    destination: Optional[Destination]


class Packages(TypedDict, total=False):
    """Delivery packages keyed by registry ecosystem. TypeScript SDK, CLI, and MCP share npm delivery without becoming the same output. Python and Go SDKs use their own package ecosystems."""
    npm: PackageDelivery
    python: PackageDelivery
    go: PackageDelivery


class _SpecPatchRequired(TypedDict):
    op: Literal["set", "append", "remove", "rename"]
    # JSON-Pointer-style path. Pattern segments enable bulk fixes: * (any child), ** (any depth), [key=value] (filter), e.g. /paths/**/parameters/[name=account_id]/schema/type. Renaming a schema under /components/schemas also rewrites its $refs.
    path: str


class SpecPatch(_SpecPatchRequired, total=False):
    """A fix applied to the spec before generation. Targets are JSON Pointers into the document. A patch whose target no longer exists is skipped and reported as a warning on the generation, never silently."""
    # set only; the replacement value.
    value: Any
    # rename only; the new key name.
    to: Optional[str]
    reason: Optional[str]


class _ProjectRequired(TypedDict):
    id: str
    object: Literal["project"]
    name: str
    source: Source
    packages: Packages
    # Regenerate when the spec changes: on every push to the default branch for a repository source, every 30 minutes for a URL source. Off by default: the first generation is always one you asked for. Off means only "generate now" and POST /projects/{project_id}/generations regenerate.
    auto_regen: bool
    # First-class generated outputs. Any non-empty combination is valid. Free keeps every selected output current for the first 25 operations in one linked project. On Pro, each selected output is billed once; shared implementation runtimes are included.
    outputs: List[OutputId]
    # Format: date-time.
    created_at: str


class Project(_ProjectRequired, total=False):
    # The source URL when the source kind is url; null otherwise.
    spec_url: Optional[str]
    spec_patches: List[SpecPatch]
    config: Optional[Config]
    # Whether the hosted MCP endpoint is on. Requires the MCP output and Enterprise; turning the output off turns this off.
    mcp_enabled: bool
    # Path of the hosted MCP endpoint while it is on; read-only.
    mcp_url: Optional[str]
    # Whether the webhook relay is on, letting the generated CLI's webhooks listen command mint relay sessions. Requires the cli output and Pro; turning the output off turns this off.
    relay_enabled: bool


class _ProjectsListResponseRequired(TypedDict):
    data: List[Project]


class ProjectsListResponse(_ProjectsListResponseRequired, total=False):
    next_cursor: Optional[str]


class ProjectsDeleteResponse(TypedDict):
    deleted: Literal[True]


class _ProjectsListGenerationsResponseRequired(TypedDict):
    data: List[Generation]


class ProjectsListGenerationsResponse(_ProjectsListGenerationsResponseRequired, total=False):
    next_cursor: Optional[str]


class GenerationFailure(TypedDict):
    """A language that did not generate in a multi-language run."""
    language: Literal["typescript", "python", "go"]
    status: Literal["failed"]
    error: str


class ProjectsGenerateResponse(TypedDict):
    data: List[Union[Generation, GenerationFailure]]


class McpUsageByToolItem(TypedDict):
    tool: str
    calls: int
    errors: int


class _McpUsageRequired(TypedDict):
    object: Literal["mcp_usage"]
    project_id: str
    # The window these numbers cover.
    days: int
    # Tool calls served, including ones that returned an error.
    calls: int
    # Calls whose result was a tool error (API failures, bad arguments).
    errors: int
    # Calls turned away by the per-caller or per-endpoint limit.
    rate_limited: int
    # Mean upstream request time across served calls.
    avg_duration_ms: int
    by_tool: List[McpUsageByToolItem]


class McpUsage(_McpUsageRequired, total=False):
    # The hosted endpoint URL, or null when it is off.
    mcp_url: Optional[str]


class _SpecVersionRequired(TypedDict):
    id: str
    object: Literal["spec_version"]
    project_id: str
    # sha256 of the raw spec text; the version's identity.
    hash: str
    # Format: date-time.
    created_at: str


class SpecVersion(_SpecVersionRequired, total=False):
    bytes: int
    # Where this spec came from — a URL, or a repo and path.
    source: Optional[Dict[str, Any]]
    # The raw spec text. Present on retrieve, omitted from lists, and replaced by content_omitted when the spec is too large to inline.
    content: str
    # Present and true when the spec was too large to inline; fetch it from /spec_versions/{spec_version_id}/content.
    content_omitted: bool


class _SpecVersionsListResponseRequired(TypedDict):
    data: List[SpecVersion]


class SpecVersionsListResponse(_SpecVersionsListResponseRequired, total=False):
    next_cursor: Optional[str]


class Account(TypedDict):
    """The organization an API key belongs to. Members share its projects, keys, and plan; sign-in identity is not part of the API."""
    id: str
    object: Literal["account"]
    # The organization's display name.
    name: str
    plan: Literal["free", "pro", "enterprise"]
    # Format: date-time.
    created_at: str


class _UsageHostedGenerationsRequired(TypedDict):
    # Cumulative linked-project generations recorded for the organization.
    used: int


class UsageHostedGenerations(_UsageHostedGenerationsRequired, total=False):
    """Cumulative linked-project runs. No plan caps the number of runs; included and remaining are null for every plan."""
    # Always null; retained for response compatibility.
    included: Optional[int]
    # Always null; generations have no count quota.
    remaining: Optional[int]


class UsageRequests(TypedDict):
    """Who called the API in the last 30 days, read from the User-Agent the generated tooling sends: by surface (cli, mcp, sdk, http) and by agent harness (claude-code, codex, cursor, ...), and the share of requests that came through an agent."""
    days: int
    requests: int
    by_surface: Dict[str, int]
    by_harness: Dict[str, int]
    # 0 to 1.
    agent_share: float


class _UsageRequired(TypedDict):
    object: Literal["usage"]
    # Cumulative linked-project runs. No plan caps the number of runs; included and remaining are null for every plan.
    hosted_generations: UsageHostedGenerations
    # Endpoints included before per-endpoint billing applies.
    included_endpoints: int


class Usage(_UsageRequired, total=False):
    # Who called the API in the last 30 days, read from the User-Agent the generated tooling sends: by surface (cli, mcp, sdk, http) and by agent harness (claude-code, codex, cursor, ...), and the share of requests that came through an agent.
    requests: UsageRequests


class _ApiKeyRequired(TypedDict):
    id: str
    object: Literal["api_key"]
    name: str
    # Last four characters of the secret; the secret itself is never stored.
    last4: str
    revoked: bool
    # Format: date-time.
    created_at: str


class ApiKey(_ApiKeyRequired, total=False):
    # Format: date-time.
    last_used_at: Optional[str]


class _ApiKeysListResponseRequired(TypedDict):
    data: List[ApiKey]


class ApiKeysListResponse(_ApiKeysListResponseRequired, total=False):
    next_cursor: Optional[str]


__all__ = [
    "GeneratedFile",
    "OutputId",
    "FileStub",
    "Generation",
    "GenerationMeta",
    "GenerationLimits",
    "GenerationResultClaimVariant1",
    "GenerationResult",
    "SpecInput",
    "RetryTuning",
    "PaginationRule",
    "GraphqlSettingsEnvironmentsItem",
    "GraphqlSettings",
    "CliBehavior",
    "McpBehavior",
    "PackageBehavior",
    "Config",
    "Source",
    "Destination",
    "PackageDelivery",
    "Packages",
    "SpecPatch",
    "Project",
    "ProjectsListResponse",
    "ProjectsDeleteResponse",
    "ProjectsListGenerationsResponse",
    "GenerationFailure",
    "ProjectsGenerateResponse",
    "McpUsageByToolItem",
    "McpUsage",
    "SpecVersion",
    "SpecVersionsListResponse",
    "Account",
    "UsageHostedGenerations",
    "UsageRequests",
    "Usage",
    "ApiKey",
    "ApiKeysListResponse",
]
